# 1. Imports

In [91]:
import os
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from collections import defaultdict
import copy
import pickle
import unicodedata
from tqdm import tqdm

# 2. Methods

## 2.1 Loading Datasets

In [107]:
def get_dataset_dataframe(dataset_folder_name, dataset_sub_folder_name, dataset_file_name):
    # Move up from /notebooks → /Thesis
    base_dir = os.path.dirname(os.getcwd())

    # Full path to your .jsonl file
    file_path = os.path.join(base_dir, "datasets", dataset_folder_name, dataset_sub_folder_name, dataset_file_name)

    # Load with pandas (must use lines=True for .jsonl format)
    df = pd.read_json(file_path, lines=True)

    return df

## 2.2 Extract Golden Evidence

In [4]:
def extract_first_group(evidence_list):
    try:
        return evidence_list[0]  # first group: list of [anno_id, evid_id, page, sent_id]
    except:
        return []

## 2.3 Text Normalization

In [5]:
def normalize(text):
    return unicodedata.normalize("NFC", text) if isinstance(text, str) else text

## 2.4 Check Page Existence After Normalization

In [6]:
def norm_page_exists_in_df(df, target_page):
    norm_page = normalize(target_page)
    for group in df['golden_evidence_group']:
        if not group:
            continue
        for item in group:
            if normalize(item[2]) == norm_page:
                return True
    return False

## 2.5 Extract Evidence Text

In this, we 'll extract the evidence page name & sentence id from given evidence group, which is extracted from fever_df['golden_evidence_group'], which will be fed to the 'enriched_index' (created using fever_index & wiki_index contaning page name, setence id & sentence text) which will give us the required sentence text.

For one evidence group, all the extracted sentences will be joined as returned as a one string.

In [79]:
def extract_evidence_text(evidence_group, enriched_index):
    # Handle NOT ENOUGH INFO (null evidence)
    if not evidence_group or (isinstance(evidence_group[0], list) and evidence_group[0][2] is None):
        return ""
    
    texts = []
    for item in evidence_group:
        try:
            page_name = item[2]
            sentence_id = item[3]

            if page_name in enriched_index and sentence_id in enriched_index[page_name]:
                sentence = enriched_index[page_name][sentence_id]
                texts.append(sentence)
        except Exception as e:
            # Failsafe in case of bad structure
            print(f"Warning while processing evidence item: {item}, error: {e}")
            continue

    return " ".join(texts)

# 3. Preparing Dataset for Pre-processing

## 3.1 Loading fever dataset - Train, Test & Dev

In [4]:
fever_train_df = get_dataset_dataframe("FEVER", "raw", "train.jsonl")
fever_train_df.head()

Reading from: e:\Users\Anirudh\Study\MS\Implementation\Thesis\datasets\FEVER\raw\train.jsonl

,id,verifiable,label,claim,evidence
0,75397,VERIFIABLE,SUPPORTS,Nikolaj Coster-Waldau worked with the Fox Broa...,"[[[92206, 104971, Nikolaj_Coster-Waldau, 7], [..."
1,150448,VERIFIABLE,SUPPORTS,Roman Atwood is a content creator.,"[[[174271, 187498, Roman_Atwood, 1]], [[174271..."
2,214861,VERIFIABLE,SUPPORTS,"History of art includes architecture, dance, s...","[[[255136, 254645, History_of_art, 2]]]"
3,156709,VERIFIABLE,REFUTES,Adrienne Bailon is an accountant.,"[[[180804, 193183, Adrienne_Bailon, 0]]]"
4,83235,NOT VERIFIABLE,NOT ENOUGH INFO,System of a Down briefly disbanded in limbo.,"[[[100277, None, None, None]]]"

In [5]:
fever_train_df.shape

(145449, 5)

In [6]:
fever_paper_test_df = get_dataset_dataframe("FEVER", "raw", "paper_test.jsonl")
fever_paper_test_df.head()

Reading from: e:\Users\Anirudh\Study\MS\Implementation\Thesis\datasets\FEVER\raw\paper_test.jsonl

,id,verifiable,label,claim,evidence
0,113501,NOT VERIFIABLE,NOT ENOUGH INFO,Grease had bad reviews.,"[[[133128, None, None, None]]]"
1,163803,VERIFIABLE,SUPPORTS,Ukrainian Soviet Socialist Republic was a foun...,"[[[296950, 288668, Ukrainian_Soviet_Socialist_..."
2,70041,VERIFIABLE,SUPPORTS,2 Hearts is a musical composition by Minogue.,"[[[225394, 230056, 2_Hearts_-LRB-Kylie_Minogue..."
3,202314,VERIFIABLE,REFUTES,The New Jersey Turnpike has zero shoulders.,"[[[238335, 240393, New_Jersey_Turnpike, 15]]]"
4,57085,NOT VERIFIABLE,NOT ENOUGH INFO,Legendary Entertainment is the owner of Wanda ...,"[[[178035, None, None, None], [182093, None, N..."

In [7]:
fever_paper_test_df.shape

(9999, 5)

In [8]:
fever_paper_dev_df = get_dataset_dataframe("FEVER", "raw", "paper_dev.jsonl")
fever_paper_dev_df.head()

Reading from: e:\Users\Anirudh\Study\MS\Implementation\Thesis\datasets\FEVER\raw\paper_dev.jsonl

,id,verifiable,label,claim,evidence
0,91198,NOT VERIFIABLE,NOT ENOUGH INFO,Colin Kaepernick became a starting quarterback...,"[[[108548, None, None, None]]]"
1,194462,NOT VERIFIABLE,NOT ENOUGH INFO,Tilda Swinton is a vegan.,"[[[227768, None, None, None]]]"
2,137334,VERIFIABLE,SUPPORTS,Fox 2000 Pictures released the film Soul Food.,"[[[289914, 283015, Soul_Food_-LRB-film-RRB-, 0..."
3,166626,NOT VERIFIABLE,NOT ENOUGH INFO,Anne Rice was born in New Jersey.,"[[[191656, None, None, None], [191657, None, N..."
4,111897,VERIFIABLE,REFUTES,Telemundo is a English-language television net...,"[[[131371, 146144, Telemundo, 0]], [[131371, 1..."

In [9]:
fever_paper_dev_df.shape

(9999, 5)

## 3.2 Merging Fever Dataset

In [10]:
FEVER_df = pd.concat([fever_train_df, fever_paper_test_df, fever_paper_dev_df], ignore_index=True)
FEVER_df.head()

,id,verifiable,label,claim,evidence
0,75397,VERIFIABLE,SUPPORTS,Nikolaj Coster-Waldau worked with the Fox Broa...,"[[[92206, 104971, Nikolaj_Coster-Waldau, 7], [..."
1,150448,VERIFIABLE,SUPPORTS,Roman Atwood is a content creator.,"[[[174271, 187498, Roman_Atwood, 1]], [[174271..."
2,214861,VERIFIABLE,SUPPORTS,"History of art includes architecture, dance, s...","[[[255136, 254645, History_of_art, 2]]]"
3,156709,VERIFIABLE,REFUTES,Adrienne Bailon is an accountant.,"[[[180804, 193183, Adrienne_Bailon, 0]]]"
4,83235,NOT VERIFIABLE,NOT ENOUGH INFO,System of a Down briefly disbanded in limbo.,"[[[100277, None, None, None]]]"

In [11]:
FEVER_df.shape

(165447, 5)

Verifying whether the dataset merged correctly or we missed anything.

Train + Test + Dev = 145449 + 9999 + 9999 = 165447

This is exactly what we have in the merged dataset. Therefore, merging is done successfully.

Data Description:
1. id: The ID of the claim
2. label: The annotated label for the claim - SUPPORTS|REFUTES|NOT ENOUGH INFO.
3. claim: The text of the claim.
4. evidence: 

    A list of evidence sets like this
    
    [
        [[Annotation ID, Evidence ID, Wikipedia URL/ Page Name, sentence ID] , ...], # evidence set 1
        [[Annotation ID, Evidence ID, Wikipedia URL/ Page Name, sentence ID] , ...], # evidence set 2
        ...
    ]
     
     or

    A [Annotation ID, Evidence ID, null, null] tuple if the label is NOT ENOUGH INFO.

5. verifiable: There are 2 kind of values - 'VERIFIABLE' & 'NOT VERIFIABLE'
    - Whenever a claim is verified ,i.e. either supports or refutes, with the given evidence, then, that comes under 'VERIFIABLE', whereas
    - When a claim can't be verified, i.e. neither supports nor refutes, in the absence or the appropriate evidence, then, that comes under 'NOT VERIFIABLE'.

## 3.3 Saving Merged Dataset

In [ ]:
output_path = os.path.join("..", "datasets", "FEVER", "pre-processed", "FEVER_Merged.jsonl")
FEVER_df.to_json(output_path, orient="records", lines=True)

# 4. Data Preprocessing

In [13]:
FEVER_df = get_dataset_dataframe("FEVER", "pre-processed", "FEVER_Merged.jsonl")
FEVER_df.head()

Reading from: e:\Users\Anirudh\Study\MS\Implementation\Thesis\datasets\FEVER\pre-processed\FEVER_Merged.jsonl

,id,verifiable,label,claim,evidence
0,75397,VERIFIABLE,SUPPORTS,Nikolaj Coster-Waldau worked with the Fox Broa...,"[[[92206, 104971, Nikolaj_Coster-Waldau, 7], [..."
1,150448,VERIFIABLE,SUPPORTS,Roman Atwood is a content creator.,"[[[174271, 187498, Roman_Atwood, 1]], [[174271..."
2,214861,VERIFIABLE,SUPPORTS,"History of art includes architecture, dance, s...","[[[255136, 254645, History_of_art, 2]]]"
3,156709,VERIFIABLE,REFUTES,Adrienne Bailon is an accountant.,"[[[180804, 193183, Adrienne_Bailon, 0]]]"
4,83235,NOT VERIFIABLE,NOT ENOUGH INFO,System of a Down briefly disbanded in limbo.,"[[[100277, None, None, None]]]"

## 4.1 Dropping irrelevant column - 'verifiable'

In [14]:
# Dropping the 'verifiable' column as we already have the 'label' column
FEVER_df = FEVER_df.drop(columns=['verifiable'])
FEVER_df.head()

,id,label,claim,evidence
0,75397,SUPPORTS,Nikolaj Coster-Waldau worked with the Fox Broa...,"[[[92206, 104971, Nikolaj_Coster-Waldau, 7], [..."
1,150448,SUPPORTS,Roman Atwood is a content creator.,"[[[174271, 187498, Roman_Atwood, 1]], [[174271..."
2,214861,SUPPORTS,"History of art includes architecture, dance, s...","[[[255136, 254645, History_of_art, 2]]]"
3,156709,REFUTES,Adrienne Bailon is an accountant.,"[[[180804, 193183, Adrienne_Bailon, 0]]]"
4,83235,NOT ENOUGH INFO,System of a Down briefly disbanded in limbo.,"[[[100277, None, None, None]]]"

## 4.2 Multi-evidence to Single-evidence Conversion

Here, we are converting the multi-evidence fever dataset to single-evidence by extracting the first evidence group and storing it as a golden evidence group.

In [15]:
FEVER_df['golden_evidence_group'] = FEVER_df['evidence'].apply(extract_first_group)
FEVER_df.head()

,id,label,claim,evidence,golden_evidence_group
0,75397,SUPPORTS,Nikolaj Coster-Waldau worked with the Fox Broa...,"[[[92206, 104971, Nikolaj_Coster-Waldau, 7], [...","[[92206, 104971, Nikolaj_Coster-Waldau, 7], [9..."
1,150448,SUPPORTS,Roman Atwood is a content creator.,"[[[174271, 187498, Roman_Atwood, 1]], [[174271...","[[174271, 187498, Roman_Atwood, 1]]"
2,214861,SUPPORTS,"History of art includes architecture, dance, s...","[[[255136, 254645, History_of_art, 2]]]","[[255136, 254645, History_of_art, 2]]"
3,156709,REFUTES,Adrienne Bailon is an accountant.,"[[[180804, 193183, Adrienne_Bailon, 0]]]","[[180804, 193183, Adrienne_Bailon, 0]]"
4,83235,NOT ENOUGH INFO,System of a Down briefly disbanded in limbo.,"[[[100277, None, None, None]]]","[[100277, None, None, None]]"

## 4.3 Formating 'golden_evidence_group' column

Let's explore this newly created column for all 3 label types:
1. 'SUPPORTS'
2. 'REFUTES'
3. 'NOT ENOUGH INFO'

In [16]:
FEVER_df[FEVER_df['label'] == 'SUPPORTS']['golden_evidence_group']

0         [[92206, 104971, Nikolaj_Coster-Waldau, 7], [9...
1                       [[174271, 187498, Roman_Atwood, 1]]
2                     [[255136, 254645, History_of_art, 2]]
5         [[151831, 166598, Homeland_-LRB-TV_series-RRB-...
8                       [[49158, 58489, Boston_Celtics, 3]]
                                ...
165432                 [[259746, 258294, Hanford_Site, 23]]
165434                     [[241367, 242917, Brad_Wilk, 4]]
165437                   [[83064, 94959, Reign_Over_Me, 1]]
165440                    [[21784, 26782, Miranda_Otto, 1]]
165441    [[138793, 153853, NAACP_Image_Award_for_Outsta...
Name: golden_evidence_group, Length: 86701, dtype: object

In [17]:
FEVER_df[FEVER_df['label'] == 'REFUTES']['golden_evidence_group']

3                    [[180804, 193183, Adrienne_Bailon, 0]]
14                   [[161295, 175782, Stranger_Things, 5]]
16                        [[89957, 102650, Puerto_Rico, 0]]
26        [[31205, 37902, Peggy_Sue_Got_Married, 0], [31...
27                        [[73660, 84912, Andy_Roddick, 7]]
                                ...
165412    [[169207, 182867, A_River_Runs_Through_It_-LRB...
165418                       [[160200, 174721, Arizona, 0]]
165420    [[88467, 101093, Winter's_Tale_-LRB-novel-RRB-...
165433            [[252357, 252156, Harvard_University, 8]]
165435      [[108293, 121833, Kerplunk_-LRB-album-RRB-, 2]]
Name: golden_evidence_group, Length: 36441, dtype: object

In [ ]:
FEVER_df[FEVER_df['label'] == 'NOT ENOUGH INFO']['golden_evidence_group']

4                              [[100277, None, None, None]]
6                              [[173384, None, None, None]]
7                              [[273626, None, None, None]]
21                             [[160895, None, None, None]]
23                             [[248748, None, None, None]]
                                ...
165442    [[284225, None, None, None], [285168, None, No...
165443                          [[71922, None, None, None]]
165444                          [[49508, None, None, None]]
165445                         [[246624, None, None, None]]
165446                          [[92386, None, None, None]]
Name: golden_evidence_group, Length: 42305, dtype: object

Findings:
1. For 'SUPPORTS' & 'REFUTES', we saw that even in a single evidence group, we have multiple evidences which means when we extract all the sentences, we 'll merge those sentences into one evidence.
2. For 'NOT ENOUGH INFO', we saw that even in this we have multiple evidences which doesn't make sense and having just one evidence in the evidence group is sufficient as anyhow it's a null value.

Before processessing, let's verify whether any of the golden evidence group has any non-null values.

In [19]:
# Checking if any of the golden evidence group where claim = 'NOT ENOUGH INFO' has any non-null values

temp_df = FEVER_df[FEVER_df['label'] == 'NOT ENOUGH INFO']['golden_evidence_group']

for group_list in temp_df:
    for each_group in group_list:
        if each_group[2] is not None or each_group[3] is not None: 
            print(each_group[2], each_group[3])

Since, nothing gets printed which means all the values are none. So, there is no point of keeping multiple evidences info and we should only keep the info of the first evidence only.

In [20]:
# Replacing the 'golden_evidence_group' for 'NOT ENOUGH INFO' label with the first evidence info only
for idx, row in FEVER_df.iterrows():
    if row['label'] == 'NOT ENOUGH INFO':
        FEVER_df.at[idx, 'golden_evidence_group'] = [row['golden_evidence_group'][0]]

In [21]:
FEVER_df[FEVER_df['label'] == 'NOT ENOUGH INFO']['golden_evidence_group']

4         [[100277, None, None, None]]
6         [[173384, None, None, None]]
7         [[273626, None, None, None]]
21        [[160895, None, None, None]]
23        [[248748, None, None, None]]
                      ...
165442    [[284225, None, None, None]]
165443     [[71922, None, None, None]]
165444     [[49508, None, None, None]]
165445    [[246624, None, None, None]]
165446     [[92386, None, None, None]]
Name: golden_evidence_group, Length: 42305, dtype: object

From the data at index '165442', it is clear that the multiple evidences are removed.

### 4.3.1 Saving the pre-processed FEVER dataset with golden evidence group

In [24]:
output_path = os.path.join("..", "datasets", "FEVER", "pre-processed", "FEVER_Merged_with_Golden_Evidence.jsonl")
FEVER_df.to_json(output_path, orient="records", lines=True)

## 4.4 Creating fever lookup dictionary

In [7]:
FEVER_df = get_dataset_dataframe("FEVER", "pre-processed", "FEVER_Merged_with_Golden_Evidence.jsonl")
FEVER_df.head()

Reading from: e:\Users\Anirudh\Study\MS\Implementation\Thesis\datasets\FEVER\pre-processed\FEVER_Merged_with_Golden_Evidence.jsonl

,id,label,claim,evidence,golden_evidence_group
0,75397,SUPPORTS,Nikolaj Coster-Waldau worked with the Fox Broa...,"[[[92206, 104971, Nikolaj_Coster-Waldau, 7], [...","[[92206, 104971, Nikolaj_Coster-Waldau, 7], [9..."
1,150448,SUPPORTS,Roman Atwood is a content creator.,"[[[174271, 187498, Roman_Atwood, 1]], [[174271...","[[174271, 187498, Roman_Atwood, 1]]"
2,214861,SUPPORTS,"History of art includes architecture, dance, s...","[[[255136, 254645, History_of_art, 2]]]","[[255136, 254645, History_of_art, 2]]"
3,156709,REFUTES,Adrienne Bailon is an accountant.,"[[[180804, 193183, Adrienne_Bailon, 0]]]","[[180804, 193183, Adrienne_Bailon, 0]]"
4,83235,NOT ENOUGH INFO,System of a Down briefly disbanded in limbo.,"[[[100277, None, None, None]]]","[[100277, None, None, None]]"

Since, the structure of the 'golden_evidence_group' where claim is either 'SUPPORTS' or 'REFUTES' is like this 

[
    [Annotation ID, Evidence ID, Page Name, Sentence ID],
    [Annotation ID, Evidence ID, Page Name, Sentence ID],
    [Annotation ID, Evidence ID, Page Name, Sentence ID],
    .
    .
    .
    [Annotation ID, Evidence ID, Page Name, Sentence ID]
]

Since, this is for one claim, so there 'll mutliple sentences (evidences) from the same page (or with same page name) and they might be spread over the entire data which means same data is being repeated multiple time.

Since, we need to find the corresponding sentences from wiki dump data so it is better to create a look-up dictionary. In this, all the 'Sentence ID' belongs to one page will come under one page name at one place. 

Later on, we 'll use this dictionary to add the sentence along with it which makes the lookup faster.

In [8]:
FEVER_df['golden_evidence_group'].head()

0    [[92206, 104971, Nikolaj_Coster-Waldau, 7], [9...
1                  [[174271, 187498, Roman_Atwood, 1]]
2                [[255136, 254645, History_of_art, 2]]
3               [[180804, 193183, Adrienne_Bailon, 0]]
4                         [[100277, None, None, None]]
Name: golden_evidence_group, dtype: object

In [30]:
fever_lookup = defaultdict(set)

for _, row in FEVER_df.iterrows():
    group = row['golden_evidence_group']
    if not group:
        continue
    for list_item in group:
        page, sent_id = list_item[2], list_item[3]
        if page and sent_id is not None:
            fever_lookup[page].add(sent_id)

fever_lookup

defaultdict(set,
            {'Nikolaj_Coster-Waldau': {0, 2, 3, 7, 8},
             'Fox_Broadcasting_Company': {0, 1, 2},
             'Roman_Atwood': {0, 1},
             'History_of_art': {0, 2},
             'Adrienne_Bailon': {0, 1, 8},
             'Homeland_-LRB-TV_series-RRB-': {0, 3},
             'Prisoners_of_War_-LRB-TV_series-RRB-': {0},
             'Boston_Celtics': {0, 3},
             'The_Ten_Commandments_-LRB-1956_film-RRB-': {0},
             'Tetris': {0, 18},
             'Cyndi_Lauper': {0, 2, 7, 21, 26},
             'The_Hunger_Games_-LRB-film-RRB-': {0,
              1,
              2,
              3,
              4,
              8,
              16,
              18,
              19,
              21,
              24,
              27},
             'Ryan_Gosling': {0, 3, 6, 7, 8, 9, 12, 17},
             'Chad': {0},
             'Stranger_Things': {0, 1, 2, 5, 6, 9, 13, 14, 16},
             'Ryan_Seacrest': {0},
             'Puerto_Rico': {0, 3, 6},
             'Michael_Giacchino': {0, 1},
             'Stranger_than_Fiction_-LRB-2006_film-RRB-': {0},
             'Chris_Hemsworth': {0, 1, 2, 7},
             'Selena': {0, 8, 15, 28, 33},
             "Robert_J._O'Neill_-LRB-U.S._Navy_SEAL-RRB-": {0, 1},
             'The_Silence_of_the_Lambs_-LRB-film-RRB-': {0, 1, 2, 5, 6},
             'Peggy_Sue_Got_Married': {0},
             'Francis_Ford_Coppola': {0, 4, 5, 8, 9, 10, 12},
             'Andy_Roddick': {0, 3, 7, 8, 11, 12},
             'Bed-In': {0, 1},
             'Tupac_Shakur': {0, 3, 4, 5, 11, 14, 15},
             'The_Jim_Henson_Company': {0, 1, 5},
             'Slovenia': {0, 1, 3, 7, 9, 17, 19, 29},
             'Eurozone': {0, 5},
             'Midwestern_United_States': {0, 4, 8, 9},
             'Saratoga_-LRB-film-RRB-': {0, 1, 4, 5},
             'J._Howard_Marshall': {0},
             'Infant': {0},
             'Grace_Jones': {0, 1, 7, 13, 14, 15, 17, 21, 22},
             'Lisbon': {0, 1, 19, 23},
             'Willie_Nelson': {0, 1, 2, 3, 6, 7, 8, 9, 23, 26, 33, 36, 37, 39},
             'Malcolm_Young': {0, 1, 8},
             'Newfoundland_and_Labrador': {0, 1, 3, 4, 5},
             'Furia_-LRB-film-RRB-': {0},
             'United_States': {0,
              2,
              3,
              4,
              5,
              7,
              10,
              12,
              16,
              17,
              18,
              19,
              28,
              29,
              30,
              35},
             'Sophie_Turner': {0, 1, 2, 5, 6},
             'Mother_Teresa': {0, 1, 2, 10, 11},
             'The_Smurfs_-LRB-film-RRB-': {0, 6, 7, 10},
             'C._S._Forester': {0},
             'Kong-COLON-_Skull_Island': {0, 1, 2, 3, 8},
             'The_Challenge_-LRB-TV_series-RRB-': {0, 5, 6, 17},
             'Berlin': {0, 1, 2, 3, 7, 17, 23},
             'South_Korea': {0, 2, 9, 10, 16, 19, 24, 27},
             'Hacksaw_Ridge': {0, 4, 5, 8},
             'Michael_Fassbender': {0, 1, 2, 3, 8, 9},
             'Red_Headed_Stranger': {0, 11, 21},
             'Paul_Bettany': {1, 2, 8},
             'Scotland': {0, 1, 2},
             'Hebrides': {0},
             'Uzbekistan': {10, 14, 15, 18},
             'Charles,_Prince_of_Wales': {0, 1, 5, 16, 17, 18},
             'Chester_Bennington': {0, 1, 2, 10},
             'Vincent_Cassel': {0, 1},
             'Pope_John_Paul_II_-LRB-miniseries-RRB-': {0, 11},
             'David_Beckham': {0, 1, 2, 3, 11, 12, 13, 14, 19, 24, 25, 26},
             'Indiana_Jones': {0, 1, 7, 14},
             'Brian_Wilson': {0, 6, 7, 22},
             'The_Great_Gatsby': {0, 1, 2, 7, 14},
             'Iron_Man_3': {0, 1, 2, 8},
             'La_La_Anthony': {0, 3, 4, 7},
             'Led_Zeppelin': {0, 1, 5, 6, 15, 23, 24},
             'Richard_Harris': {0, 1},
             'The_Fosters_-LRB-2013_TV_series-RRB-': {0, 1, 4},
             'Jonathan_Hensleigh': {0},
             'Filmfare': {0, 1, 2},
             'Buckingham_Palace': {0, 1, 7, 8, 15},
             'Sarah_Paulson': {0, 1, 2, 3, 4, 8, 9, 14},
             'David_Harbour': {0, 1},
             'Kazakhstan': {2, 4, 5, 10, 12, 13, 22, 33},
             'José_María_Chacón': {0, 1},
             'Liverpool_F.C.': {0, 1, 2, 5, 7, 8, 11, 12, 19},
             'Land_Rover': {0, 5, 7, 11},
             'Sully_-LRB-film-RRB-': {0, 1, 6},
             'Stanley_Tucci': {0, 3, 4},
             'Monk_-LRB-TV_series-RRB-': {0},
             'Brock_Lesnar': {0, 1, 5, 6, 9, 11, 15, 16, 17, 18, 23},
             'Khmer_Empire': {0, 1, 5},
             'On_the_Road_-LRB-film-RRB-': {1, 3, 5, 7},
             'Paramore_-LRB-album-RRB-': {0, 1, 2, 3, 13, 19},
             'Peter_Davison': {0, 1, 2, 3},
             '21_Jump_Street_-LRB-film-RRB-': {0, 4},
             'Philadelphia_Museum_of_Art': {2},
             'Dustin_Hoffman': {0, 1, 2, 5, 6, 9, 13},
             'Deadpool_-LRB-film-RRB-': {0, 1, 2, 5, 8, 13, 14, 17},
             'Stephon_Marbury': {0, 1},
             'Cerebral_palsy': {0, 1, 13, 20, 30, 31, 32, 33},
             'Alfred_Hitchcock': {0, 1, 2, 3, 6, 9, 19, 23},
             'Julius_Caesar_-LRB-1953_film-RRB-': {0, 2},
             'Pulp_Fiction': {0, 5, 13, 19},
             'Quentin_Tarantino': {0, 1, 2, 5, 6, 7, 9, 13, 14, 17, 21, 22},
             'Absolute_Beginners_-LRB-film-RRB-': {0, 1, 7, 9},
             'No_Reservations_-LRB-film-RRB-': {0, 1, 2, 5},
             'Claire_Danes': {1, 15},
             'Hugh_Dancy': {0, 1},
             'Dangerous_Liaisons': {0, 4, 5},
             'Academy_Awards': {0, 1, 2, 5, 7, 8, 11},
             'Academy_of_Motion_Picture_Arts_and_Sciences': {0, 8},
             'Hubert_Humphrey': {0, 1, 10, 11, 15},
             'Minneapolis': {0, 1, 5, 6, 7, 14},
             'Alex_Rodriguez': {0, 1, 3, 4, 6, 10, 21, 24, 25, 26},
             'Friendship': {2},
             'Judd_Apatow': {0, 1, 5, 8},
             'Massachusetts': {0, 1, 5, 7, 19, 23},
             'Giancarlo_Stanton': {0, 4, 5},
             'Chris_Pine': {0, 1, 2},
             'Trevor_Noah': {0, 6, 9},
             'Lucas_-LRB-film-RRB-': {0, 2},
             'Corey_Haim': {0, 10},
             'Ryan_Phillippe': {0, 1, 2, 7, 8},
             'Sean_Connery': {0, 1, 4, 5, 6},
             'Venom_-LRB-comics-RRB-': {0, 1, 2, 14},
             'Overwatch_-LRB-video_game-RRB-': {0,
              1,
              4,
              5,
              6,
              8,
              11,
              18,
              20,
              21,
              23},
             'Lily_James': {0, 1, 4, 6},
             'Jing_Tian': {0, 3},
             'Jennifer_Aniston': {0, 1, 2, 14, 17},
             'Sparta': {2, 6, 8, 19},
             'Isis': {0, 15},
             'International_relations': {0, 1, 9, 10},
             'Régine_Chassagne': {0, 1},
             'John_McCain': {0, 1, 13, 16, 17, 18, 19, 22, 23},
             'Farrah_Fawcett': {0, 1, 5, 6, 14, 15, 16, 17, 20, 23, 26},
             'The_Who': {0, 1, 2, 6, 7, 8, 20},
             'Planet_of_the_Apes_-LRB-1968_film-RRB-': {0,
              2,
              3,
              4,
              12,
              13,
              15,
              19},
             'Star_vs._the_Forces_of_Evil': {0},
             'Galaxy_Quest': {0},
             'Friends_with_Benefits_-LRB-film-RRB-': {0, 1},
             'Glenn_Close': {0, 2, 5, 8, 16, 21, 22, 23},
             'The_Real_Thing_-LRB-play-RRB-': {0, 1},
             'Zooey_Deschanel': {0, 4, 7, 8},
             'Seven_Days_in_May': {0, 1, 2},
             'Kirk_Douglas': {0, 1, 2, 3, 15},
             'Ava_Gardner': {0},
             'Burt_Lancaster': {0, 2},
             'Winnipeg': {0, 16},
             'Mark_Zuckerberg': {0, 1, 2, 5, 6, 16, 17},
             'Facebook': {0, 1, 4, 6, 23},
             'Rick_and_Morty': {0, 3, 8, 9},
             'Paul_Walker': {0, 2, 4, 12},
             'Clint_Eastwood': {0, 1, 2, 5, 6, 7, 10, 19},
             'Shonen_Jump_-LRB-magazine-RRB-': {0},
             'North_America': {0, 2},
             'Gilmore_Girls': {0, 1, 2, 3, 6, 19},
             'Honest_-LRB-Future_album-RRB-': {0, 6},
             'Pranab_Mukherjee': {0, 1},
             'Anonymous_-LRB-group-RRB-': {0, 1, 2, 5, 6, 10},
             'San_Francisco': {0, 1, 2, 3, 4, 7, 18, 19},
             'Laadla_-LRB-1994_film-RRB-': {0, 1},
             'Lily_Collins': {0, 2, 3, 4, 5, 8, 9, 10, 16},
             'Bangladesh': {0, 1, 2, 4, 5, 9, 10, 18, 21, 24, 30, 31, 34, 40},
             'Lisa_Lopes': {0, 1, 5, 8},
             'TLC_-LRB-group-RRB-': {0},
             'The_Formula_-LRB-1980_film-RRB-': {0},
             'John_G._Avildsen': {0},
             'Janet_Jackson': {0, 5, 12},
             'Transformers-COLON-_The_Last_Knight': {0, 2},
             'Morena_Baccarin': {0, 1, 2},
             'Ori_-LRB-Stargate-RRB-': {0},
             'Firefly_-LRB-TV_series-RRB-': {0},
             'Naturi_Naughton': {0, 1},
             'Paul_Pogba': {0, 4, 6},
             'Mel_Gibson': {0, 1, 4, 7, 8, 9, 13, 14, 15, 16},
             'WALL-E': {0, 2, 13},
             'Generation_X': {0, 1, 6, 9},
             'Islam': {1, 2, 3, 4, 5, 8, 20},
             'Jackie_Chan': {0, 2, 3, 8},
             'Earth': {0, 1, 6, 13, 21, 22, 23},
             'Larry_Junstrom': {0},
             'Canada': {0, 2, 3, 4, 10, 11, 17, 18, 22, 24, 25, 28, 29, 30},
             'Constitution_Act,_1982': {0},
             'Renaissance': {0, 1, 5, 12, 15},
             'Pluto': {0, 1, 6, 11, 12, 13, 19, 23, 24, 25},
             'Steve_Buscemi': {0, 1, 2, 6, 7, 8, 10},
             'Twenty_One_Pilots': {0, 1, 7},
             'Selena_Gomez': {0, 1, 4, 5, 6, 9, 10, 14, 15, 19, 20},
             'Big_Boi': {0, 1},
             'Outkast': {0, 4},
             'Priyanka_Chopra': {0, 1, 2, 19},
             'Chris_Pérez': {0, 1, 2, 4, 5, 6},
             'Tate_Ellington': {1, 2, 4},
             'Mr._Sunshine_-LRB-2011_TV_series-RRB-': {0, 2},
             'Dolly_Parton': {0, 1, 3, 14, 15, 17},
             'The_Amanda_Show': {0},
             '19th_G7_summit': {4, 5},
             'Ethiopia': {0, 2, 7, 9, 13, 22, 23, 24, 25, 29, 30, 37, 38},
             'Ted_Kaczynski': {0, 1, 2, 5, 6, 9, 17, 23},
             'Keith_Urban': {0, 1, 2, 5, 7, 8, 9, 12, 14, 15, 18, 20, 24},
             'Eminem': {0, 1, 2, 3, 4, 8, 9, 12, 16, 17, 20},
             'Connaught_Tunnel': {0, 2, 3, 5, 13, 24, 28, 29},
             'Ilkhanate': {0, 1, 2, 4, 5},
             'True_Blood': {0, 2, 5, 7},
             'Jordan_Knight': {0},
             'Adam_Driver': {0, 1, 6},
             'Thor-COLON-_The_Dark_World': {0, 1, 4, 12, 15, 16, 17},
             'Loki': {0, 1, 2},
             'Amsterdam': {0, 2, 3, 9, 23},
             'Inspectah_Deck': {0},
             'Tender_Mercies': {0, 2, 16, 17},
             'Cristiano_Ronaldo': {0, 2, 9, 10, 16, 19, 24, 28, 29, 30},
             'Paul_Simon': {0, 1, 11, 12, 15, 16},
             'Baby_Driver': {0, 4},
             'David_Dhawan': {0, 4},
             'Rumi': {0, 1, 3, 8, 10},
             'Swedish_Empire': {0, 1, 5},
             'Gustavus_Adolphus_of_Sweden': {0, 11},
             'Her_-LRB-film-RRB-': {0, 2, 3, 14, 15, 16, 17},
             'Las_Vegas': {0, 1, 2, 3, 14, 15},
             'Spread_-LRB-food-RRB-': {0, 3, 6},
             'Octavia_Spencer': {4},
             'Ramayanam_-LRB-film-RRB-': {0},
             'Man_of_Steel_-LRB-film-RRB-': {0, 4, 9, 11, 13, 16},
             'Leukemia': {0, 2, 3, 7, 9, 10, 21, 25, 26, 27, 28},
             'Judy_Garland': {0, 1, 5, 6, 9, 12, 13, 14},
             'Judgment_at_Nuremberg': {0},
             'Until_Dawn': {0, 1, 4, 6, 9},
             'Timothy_Olyphant': {0, 1, 10},
             'Telangana': {0, 1, 2, 3, 4, 7, 9, 10, 11},
             'Cheaper_by_the_Dozen_-LRB-2003_film-RRB-': {0, 1, 2},
             'House_of_Lusignan': {0, 6},
             'Ten_Commandments': {0, 1},
             'The_Hangover_Part_III': {0, 3, 4},
             'Ariana_Grande': {0, 1, 3, 6, 7, 11, 13, 15, 21, 23},
             'Ted_Bundy': {0, 7, 12, 13, 14, 17},
             'Chinese_people': {0},
             "Schindler's_List": {0, 18, 20},
             'Zeus': {0, 5},
             'List_of_thunder_gods': {1},
             'Escape_from_Planet_Earth': {0},
             'Venus_Williams': {0, 3, 7, 14, 15, 16, 17, 18, 29, 40},
             'The_Beatles': {0, 1, 2, 3, 6, 7, 9, 11, 12, 13, 16, 18, 21},
             '50_First_Dates': {0, 1},
             'A_Nightmare_on_Elm_Street': {0, 6, 7, 8},
             'Charlize_Theron': {0, 1, 4, 11},
             'The_Burning_Plain': {0, 1},
             'Jemaine_Clement': {0},
             'Usain_Bolt': {0, 1, 2, 3, 4, 7, 8, 9, 16, 17, 18, 19, 20},
             'Internet': {0, 1, 5, 6, 7},
             'Sarrainodu': {0, 1, 4},
             'Jawbreaker_-LRB-film-RRB-': {0, 1, 7},
             'Rose_McGowan': {0},
             'Kurt_Sutter': {0, 1, 2, 4},
             'Lisa_Marie_Presley': {0, 1},
             'Kingdom_Hearts_III': {0, 1, 2, 6},
             'Kingdom_Hearts': {0, 4, 5, 6},
             'Keanu_Reeves': {0, 3, 4, 5, 10, 11, 12, 16, 17, 18},
             'Dwayne_Johnson': {0, 1, 4, 5, 6, 9, 10, 11, 12, 21, 23, 26},
             'Heartland_-LRB-Canadian_TV_series-RRB-': {0},
             'Mango': {0, 4, 7},
             'William_Jennings_Bryan': {0, 1, 14, 15},
             'Democratic_Party_-LRB-United_States-RRB-': {0, 1, 9, 23, 30},
             'Iris_Murdoch': {0, 1},
             'David_Koepp': {0, 1, 7, 8},
             'Block_-LRB-basketball-RRB-': {0, 10},
             'Leroy_Jethro_Gibbs': {0, 1},
             'Leslie_Howard_-LRB-actor-RRB-': {0, 3},
             'Catching_Fire': {0, 1, 2, 5},
             'Avatar-COLON-_The_Last_Airbender': {0, 6},
             'Hopman_Cup': {4},
             'Frank_Zappa': {0, 2, 7, 10, 26},
             'Ruth_Negga': {0, 1, 2, 5},
             'Warcraft_-LRB-film-RRB-': {0, 7},
             'George_VI': {0, 8, 27, 28},
             'Psychology': {0, 1, 5, 8, 13, 16},
             'Humanities': {0},
             'The_Beach_Boys': {0, 1, 3, 8, 18, 22, 23},
             'Billy_Bob_Thornton': {0, 3, 4, 16},
             'The_Ren_&_Stimpy_Show': {0, 2},
             'Courteney_Cox': {1},
             'Ronin_-LRB-film-RRB-': {0},
             'Abraham_Lincoln': {0, 1, 2, 5, 7, 8, 9, 10, 22, 33},
             'Fred_Savage': {0},
             'Al_Capone': {0, 12, 17, 19, 20, 23, 24},
             'Neurosyphilis': {0},
             'Boston': {0, 7, 9, 11, 12, 15, 17, 18},
             'Shawmut_Peninsula': {0},
             'Interstellar_-LRB-film-RRB-': {3, 4, 18},
             'Britney_Spears': {0, 1, 2, 3, 4, 6, 7, 11, 13},
             'Mike_Tyson': {0, 1, 7, 9, 10, 17, 18, 21, 22, 27},
             'Hermetic_Order_of_the_Golden_Dawn': {0, 9},
             'Ellen_Burstyn': {0, 1, 4, 5, 8, 11, 15},
             'Princess_Agents': {0, 2},
             'Gwen_Stefani': {0, 1, 6, 14, 15, 16, 17, 18, 21},
             'James_Marsden': {0, 1, 2, 6},
             'Hairspray_-LRB-2007_film-RRB-': {1},
             'Carrie_Fisher': {0, 1, 4, 5, 6, 11},
             'Ice_hockey': {0, 4, 5, 6, 7, 8, 21},
             'The_Fifth_Element': {0, 2, 8, 14, 15},
             'Audi': {0, 13, 14, 15},
             'Indonesia': {0, 1, 3, 4, 9, 12, 13, 29},
             'Wyatt_Earp': {0, 1, 5, 6, 7, 8, 12, 13, 14, 15, 22, 34, 41, 44},
             'Brave_-LRB-2012_film-RRB-': {0, 1, 14},
             'Winter_Passing': {0, 3},
             'Audrey_Horne': {0, 1, 2, 3},
             'Pilot_-LRB-Twin_Peaks-RRB-': {0},
             'Line_of_Duty': {0, 1},
             'Dayton_Agreement': {0},
             'National_Security_Agency': {0, 1},
             'Gold': {0, 1, 2, 9, 15, 21, 22, 23, 28, 31},
             'Paleogene': {0},
             'Cher': {0, 1, 5, 7, 11, 15, 16, 21, 22, 25, 26},
             'Bernard_Madoff': {7, 8, 24},
             'Donkey_-LRB-Shrek-RRB-': {0, 1},
             'O._J._Simpson': {0, 3, 5, 9, 10, 13, 17, 18, 19},
             'Ketogenic_diet': {0, 13},
             'Dennis_Quaid': {0, 1, 2},
             'Thandie_Newton': {0, 1},
             'Reese_Witherspoon': {0, 1, 2, 3, 6, 7, 8, 10, 14, 15},
             'Jenni_Rivera': {0, 8, 9, 10, 11, 13, 16, 19},
             'Lo_Nuestro_Award_for_Regional_Mexican_Female_Artist_of_the_Year': {0},
             'Curly_Top_-LRB-film-RRB-': {0},
             'Edgar_Allan_Poe': {0},
             'Danny_DeVito': {0, 1, 4, 13, 17},
             'PageRank': {1, 3},
             'Jeffrey_Dahmer': {0, 1, 5, 9},
             'Naomi_Scott': {1, 2},
             'Minnesota_Vikings': {0, 1, 3},
             'L.A._Law': {0, 8},
             'Paradise_-LRB-Lana_Del_Rey_EP-RRB-': {0},
             'Dirt_-LRB-TV_series-RRB-': {0, 9, 12},
             'Arsenic_and_Old_Lace_-LRB-film-RRB-': {0, 2, 5},
             'The_Belko_Experiment': {0, 3},
             'Apple_Inc.': {0, 1, 2, 6, 7, 16, 22, 23},
             'Moscow': {0, 1, 4, 11, 16},
             'Cult_film': {4},
             'September_11_attacks': {0, 3, 4, 7, 8, 10, 12, 24},
             'Richard_III_-LRB-play-RRB-': {0, 7},
             'Kathy_Bates': {0, 1, 2, 3},
             'Joseph_Barbera': {0},
             'Penny_Dreadful_-LRB-TV_series-RRB-': {0, 1, 2, 3, 4, 8},
             'The_Lion_King': {0, 2, 4, 5, 9, 15, 22},
             'Before_We_Go': {0, 1, 2},
             'Stevie_Nicks': {0, 3, 5, 15, 21},
             'Andrew_Wood_-LRB-singer-RRB-': {0, 4, 6, 7, 10, 16},
             'James_McAvoy': {0, 1, 2, 5, 6, 12, 16, 18},
             'John_Constantine': {0, 1, 3, 8, 12, 13},
             'Portuguese_Empire': {0, 1, 4},
             'Eddie_Vedder': {0, 1, 5, 6},
             'Kenny_Rogers': {8, 9, 10, 13},
             'Kenny_-LRB-album-RRB-': {0},
             'Larry_Buttrose': {2},
             'Elementary_-LRB-TV_series-RRB-': {0, 1, 2, 12},
             'Lucy_Liu': {0, 8},
             'X-Men-COLON-_Days_of_Future_Past': {0, 2, 13},
             'San_Junipero': {0, 1},
             'John_F._Kennedy': {0, 2, 5, 6, 7, 11, 16, 17, 25, 26, 27},
             'Gift_of_the_Night_Fury': {0, 6},
             'Jay_Baruchel': {0},
             'Juana_la_virgen': {0},
             'The_Champ_-LRB-1979_film-RRB-': {0, 1},
             'Monarch_of_the_Glen_-LRB-TV_series-RRB-': {0},
             'Robert_Redford': {0, 4, 5, 16, 18, 22, 25},
             'Beasts_of_the_Southern_Wild': {0, 5, 6},
             'Los_Angeles_Lakers': {0, 1, 3, 8, 9, 10, 15, 16, 17, 24},
             'Philippines': {0, 1, 3, 11, 18, 27, 32},
             'Joe_Manganiello': {1, 5},
             'Veronika_Decides_to_Die_-LRB-film-RRB-': {0, 1},
             'Walter_Matthau': {0, 1, 2},
             'Lisa_Kudrow': {0, 1, 6, 11},
             'Myles_Kennedy': {0, 5, 6, 7, 10},
             'Jane_Fonda': {0, 5, 6, 8, 21},
             'Imagine_Dragons': {0, 1, 2, 3, 4, 5, 8, 9},
             'Mike_Love': {0, 5, 10, 11, 12, 15},
             'Star_Search': {0, 1},
             'System_of_a_Down': {4, 6, 7},
             'Peyton_Manning': {0, 1, 3, 8, 11, 12},
             'Davis_Entertainment': {0, 3},
             'Kafka_-LRB-film-RRB-': {2},
             'Ian_Holm': {0},
             'Charles_Marie_de_La_Condamine': {0},
             'Giada_De_Laurentiis': {0, 1},
             'Today_-LRB-U.S._TV_program-RRB-': {0},
             'Bohemian_Rhapsody': {0, 1, 2, 4, 7, 18},
             'Hugh_Jackman': {0, 1, 2, 3, 6, 8},
             'The_Prestige_-LRB-film-RRB-': {0, 1, 3, 4, 5, 8, 9},
             'Cate_Blanchett': {0, 1, 2, 3, 4, 7, 8, 9, 15, 16, 18},
             'Slash_-LRB-musician-RRB-': {0, 1, 2, 3, 5},
             'Drake_-LRB-musician-RRB-': {0, 2, 6, 7},
             'R._Madhavan': {0, 6, 7, 13, 14, 20},
             'James_and_the_Giant_Peach_-LRB-film-RRB-': {0, 1, 3},
             'Ayn_Rand': {0, 1, 3, 11},
             'Anne_Hathaway': {0, 1, 2, 3, 7, 8, 9, 14},
             'Oh_Yeon-seo': {0, 1},
             'Ben_Stiller': {0, 4, 5, 6, 10, 12},

### 4.4.1 Saving this dictionary

In [31]:
# Define path to save the pickle file
output_path = r"E:\Users\Anirudh\Study\MS\Implementation\Thesis\datasets\FEVER\pre-processed\fever_lookup.pkl"

# Save the dictionary
with open(output_path, "wb") as f:
    pickle.dump(fever_lookup, f)

print(f"fever_lookup saved to: {output_path}")

fever_lookup saved to: E:\Users\Anirudh\Study\MS\Implementation\Thesis\datasets\FEVER\pre-processed\fever_lookup.pkl

## 4.5 Creating 'wiki_index' file

For creating this, we 'll using wiki dump files. There are total 109 files in the JSONL format.

We have formated & converted these JSONL files to pickle file to get the data in required structure and for faster processing.

Raw format is like this: {"id": "", "text": "", "lines": ""}

Example:

{
 "id": "1928_in_association_football",
 "text": "The following are the football -LRB- soccer -RRB- events of the year 1928 throughout the world . ",
 "lines": "0\tThe following are the football -LRB- soccer -RRB- events of the year 1928 throughout the world .\n1\t"
}

Formatted pickle file structure: {'page name': 
                                    {
                                        <sentence_id>: <sentence text string>,
                                        <sentence_id>: <sentence text string>,
                                        <sentence_id>: <sentence text string>,
                                        .
                                        .
                                        .
                                        <sentence_id>: <sentence text string>,
                                    },

                                 'page name': 
                                    {
                                        <sentence_id>: <sentence text string>,
                                        <sentence_id>: <sentence text string>,
                                        <sentence_id>: <sentence text string>,
                                        .
                                        .
                                        .
                                        <sentence_id>: <sentence text string>,
                                    } 
                                 }

Example:

defaultdict(dict,
            {'1928_in_association_football':
                {
                    0: 'The following are the football -LRB- soccer -RRB- events of the year 1928 throughout the world .'
                },
             '1986_NBA_Finals': 
                {
                    0: 'The 1986 NBA Finals was the championship round of the 1985 -- 86 NBA season .\tNBA\tNational Basketball Association',

                    1: "It pitted the Eastern Conference champion Boston Celtics against the Western Conference champion Houston Rockets , in a rematch of the 1981 Finals -LRB- only Allen Leavell and Robert Reid remained from the Rockets ' 1981 team -RRB- .\tHouston Rockets\tHouston Rockets\tBoston Celtics\tBoston Celtics\tEastern Conference\tEastern Conference (NBA)\tWestern Conference\tWestern Conference (NBA)\tAllen Leavell\tAllen Leavell\tRobert Reid\tRobert Reid (basketball)\tRockets\tHouston Rockets\tCeltics\tBoston Celtics",

                    2: 'The Celtics defeated the Rockets four games to two to win their 16th NBA championship .\tNBA\tNational Basketball Association\tRockets\tHouston Rockets\tCeltics\tBoston Celtics',

                    3: "The championship...
                }
            })

There are data in this format in 109 pickle files. Now, the sentence we are looking for might not be present in one file so to find a sentence, in the worst case scenario, we might need to go through all the files.

Doing this for finding each sentence for fever_loopup is very computationally heavy. So, for this as well, we 'll create a wiki lookup or wiki index of all these 109 files which have the following format.

dict{
    <page name>:
        {
            sentence_id: <sentence text string>,
            sentence_id: <sentence text string>,
            .
            .
            .
            sentence_id: <sentence text string>,
        },
        .
        .
        .
    <page name>:
        {
            sentence_id: <sentence text string>,
            sentence_id: <sentence text string>,
            .
            .
            .
            sentence_id: <sentence text string>,
        }
}

Example:
defaultdict(dict,
            {'Fredvang_Bridges': {0: 'The Fredvang Bridges -LRB- Fredvangbruene -RRB- are two cantilever bridges that connect the fishing village of Fredvang on Moskenesøya island with the neighboring island of Flakstadøya .\tcantilever bridges\tcantilever bridges\tfishing village\tfishing village\tFredvang\tFredvang\tMoskenesøya\tMoskenesøya\tFlakstadøya\tFlakstadøya',
              1: 'The bridges are located in the municipality of Flakstad in Nordland county , Norway .\tFlakstad\tFlakstad\tNorway\tNorway\tNordland\tNordland',
              2: '',
              3: '',
              4: 'The south bridge is called Kubholmleia Bridge -LRB- Kubholmleia bru -RRB- and the north bridge is Røssøystraumen Bridge -LRB- Røssøystraumen bru -RRB- .',
              5: 'Both bridges are 240 m long and have a main span of 115 m.',

I formatted and converted the jsonl to pickle file using a python script 'wiki_jsonl_to_pkl.py'.

Because of the computational constrating, I created 'wiki_index' on kaggle notebook using the below code.

In [ ]:
'''
wiki_pickle_dir = r"E:\Users\Anirudh\Study\MS\Implementation\Thesis\datasets\Wiki-Dump\pickle_file"
wiki_index = defaultdict(dict)

for file_name in os.listdir(wiki_pickle_dir):
    if not file_name.endswith(".pkl"):
        continue

    file_path = os.path.join(wiki_pickle_dir, file_name)
    with open(file_path, "rb") as f:
        page_dict = pickle.load(f)

    for page, sentences in page_dict.items():
        for sent_id, text in sentences.items():
            if sent_id not in wiki_index[page]:
                wiki_index[page][sent_id] = text
            elif wiki_index[page][sent_id] != text:
                print(f"Warning: Conflicting text for {page} at sentence {sent_id}")
'''

## 4.6 Loading 'wiki_index' file

In [13]:
with open(r"E:\Users\Anirudh\Study\MS\Implementation\Thesis\datasets\Wiki-Dump\processed\old_wiki_index(with_metadata).pkl", "rb") as f:
    wiki_index = pickle.load(f)

wiki_index

defaultdict(dict,
            {'Fredvang_Bridges': {0: 'The Fredvang Bridges -LRB- Fredvangbruene -RRB- are two cantilever bridges that connect the fishing village of Fredvang on Moskenesøya island with the neighboring island of Flakstadøya .\tcantilever bridges\tcantilever bridges\tfishing village\tfishing village\tFredvang\tFredvang\tMoskenesøya\tMoskenesøya\tFlakstadøya\tFlakstadøya',
              1: 'The bridges are located in the municipality of Flakstad in Nordland county , Norway .\tFlakstad\tFlakstad\tNorway\tNorway\tNordland\tNordland',
              2: '',
              3: '',
              4: 'The south bridge is called Kubholmleia Bridge -LRB- Kubholmleia bru -RRB- and the north bridge is Røssøystraumen Bridge -LRB- Røssøystraumen bru -RRB- .',
              5: 'Both bridges are 240 m long and have a main span of 115 m.',
              6: '',
              7: '',
              8: 'The bridges were opened in 1988 .',
              9: 'They are among many bridges that connect the islands of the Lofoten archipelago to each other .\tLofoten\tLofoten\tarchipelago\tarchipelago',
              10: 'The only other bridge connecting these two islands is the Kåkern Bridge .\tKåkern Bridge\tKåkern Bridge'},
             'Fort_Cassin_Formation': {0: 'The Fort Cassin Formation is a geologic formation in New York .\tFormation\tFormation (stratigraphy)\tgeologic formation\tFormation (stratigraphy)\tNew York\tNew York (state)',
              1: 'It preserves fossils dating back to the Ordovician period .\tOrdovician\tOrdovician\tfossils\tfossils\tperiod\tPeriod (geology)'},
             'Frederick_Kerseboom': {0: 'Frederick Kerseboom -LRB- 1632 -- 1690 -RRB- was a German painter , sometimes called Frederick Casaubon in England .'},
             'Franciszek_Fornalski': {0: "Franciszek Fornalski -LRB- 1781-1863 -RRB- was a Polish soldier during Napoleonic Wars , chevalier of French Legion d'honneur and Polish Virtuti Militari .\tNapoleonic Wars\tNapoleonic Wars\tLegion d'honneur\tLegion d'honneur\tVirtuti Militari\tVirtuti Militari"},
             'Frank_M._and_Annie_G._Covert_House': {0: 'The Frank M. and Annie G. Covert House is a historic home in the Hyde Park Historic District in Austin , Texas , United States .\tHyde Park Historic District\tHyde Park (Austin, Texas)',
              1: 'It is also a part of the Shadow Lawn Historic District , a subdivision within the Hyde Park neighborhood established by Hyde Park founder Monroe Shipe .\tShadow Lawn Historic District\tShadow Lawn Historic District (Austin, Texas)\tMonroe Shipe\tMonroe Shipe',
              2: '',
              3: '',
              4: 'The building was completed near the turn of the 20th century by local real estate broker and auto dealer Frank Covert .',
              5: 'Like other homes in the neighborhood , it includes an eclectic combination of styles , including a Queen Anne form and Romanesque and Classical Revival details .\tQueen Anne\tQueen Anne style architecture in the United States\tRomanesque\tRomanesque architecture\tClassical Revival\tClassical Revival',
              6: 'The house features irregular massing , a two story wraparound veranda and masonry construction , unusual in Hyde Park .',
              7: '',
              8: '',
              9: 'According to information compiled by Peter Flagg Maxson , architectural historian , the Covert House had many owners in the 20th century .',
              10: 'Under the Sassman ownership -LRB- 1917 -- 1945 -RRB- it was rented out to , among others , Robert Winslow and the House of the Holy Infancy , a home for unwed mothers .\thome for unwed mothers\thome for unwed mothers',
              11: '',
              12: '',
              13: 'In the 1970s the Covert House was acquired by several families , who tried group living there .',
              14: 'After a period of some neglect , the property was acquired by Dr. John and Ann Horan , who beautifully restored it .',
              15: 'It has since been sold on to another person .',
              16: '',
              17: '',
              18: 'The house is located at 3912 Avenue G , across from the Page-Gilbert House .\tPage-Gilbert House\tPage-Gilbert House',
              19: 'It was added to the National Register of Historic Places in 1990 .\tNational Register of Historic Places\tNational Register of Historic Places',
              20: '',
              21: '',
              22: 'Category : Houses in Austin , Texas',
              23: '',
              24: 'Category : Houses on the National Register of Historic Places in Texas\tNational Register of Historic Places\tNational Register of Historic Places',
              25: '',
              26: 'Category : National Register of Historic Places in Austin , Texas\tNational Register of Historic Places\tNational Register of Historic Places'},
             'Franjo_Bučar_State_Award_for_Sport': {0: "Franjo Bučar State Award for Sport -LRB- Državna nagrada za šport `` Franjo Bučar '' -RRB- is the highest recognition that Republic of Croatia gives for extraordinary achievements and contributions of remarkable meaning for the development of sport in Croatia .\tRepublic of Croatia\tRepublic of Croatia\tsport\tsport\tFranjo Bučar\tFranjo Bučar",
              1: '',
              2: '',
              3: 'This award has been given since 1991 .\taward\taward',
              4: 'It came as successor of awards of SR Croatia : Majska nagrada fizičke kulture and Republička nagrada fizičke kulture .\tSR Croatia\tSR Croatia',
              5: '',
              6: '',
              7: 'This award is given to professional and public workers in the area of sport , sportsmen , legal and physical entities the perform sports activity , as well as other entities whose work is meritorious for the development of sport .\tsport\tsport\taward\taward',
              8: '',
              9: '',
              10: 'It is named after Croatian writer and sports activist Franjo Bučar , person that popularized sport in Croatia in many ways .\tsport\tsport\tFranjo Bučar\tFranjo Bučar'},
             'Frédéric_Collignon': {0: 'Frédéric Collignon -LRB- born 13 December 1975 -RRB- is a table football player from Liege , Belgium .\ttable football\ttable football\tLiege\tLiège\tBelgium\tBelgium',
              1: '',
              2: '',
              3: 'In the 15 year period from 1997-2012 , Collignon was the dominant player in table football worldwide , winning the ITSF multi-table World Championships on 7 occasions ; World Championships on Tornado tables on 5 occasions , and other ITSF recognised tables including Bonzini , Garlando , Leonhart , Roberto Sport , Jupiter , Eurosoccer , etc. .\ttable football\ttable football',
              4: 'In doubles tournaments in the United States , Collignon established a dominant partnership with Todd Loffredo , winning Open Doubles in the Tornado World Championships on 7 occasions .\tTodd Loffredo\tTodd Loffredo',
              5: '',
              6: '',
              7: 'Having won more world championships on more tables , than any other player in history , and additionally being the only European player ever to have been dominant in the United States , Collignon is regarded by most as the greatest player in the history of the sport , although Collignon himself instead regards Loffredo as the greatest , however .',
              8: '',
              9: '',
              10: 'Collignon announced his retirement at the end of 2012 , at a point when he was the reigning ITSF multi-table World Champion in Singles and Doubles ; Tornado World Champion ; and having led Belgium to the World Cup .\tBelgium\tBelgium',
              11: 'Nevertheless , from semi-retirement he continues to win whenever he plays , including the 2013 Leonhart and P4P World Championships , and 2014 Bonzini World Championships .'},
             'Floribunda_-LRB-horse-RRB-': {0: 'Floribunda -LRB- 1958 -- 1979 -RRB- was a British-bred Irish-trained Thoroughbred racehorse and sire .\tThoroughbred\tThoroughbred\tsire\tHorse breeding#Terminology',
              1: 'A specialist sprinter , he won his first three races -LRB- including the New Stakes by wide margins before his two-year-old season was curtailed by injury .\tNew Stakes\tNew Stakes',
              2: 'In 1961 he was beaten in his first two races before returning to his best to win the King George Stakes and Nunthorpe Stakes .\tKing George Stakes\tKing George Stakes\tNunthorpe Stakes\tNunthorpe Stakes',
              3: 'He was retired to stud at the end of the season and had mixed success as a sire of winners .\tsire\tHorse breeding#Terminology'},
             'Francis_Barsan': {0: 'Francis Barsan is a South Sudanese politician .',
              1: 'As of 2011 , he is the Minister of Culture , Information , Youth , Sports , Hotels and Tourism of Central Equatoria .\tCentral Equatoria\tCentral Equatoria'},
             'Frank_Owen,_III': {0: 'Frank Owen III -LRB- February 25 , 1926 -- February 20 , 1999 -RRB- was a Texas legislator .\tTexas\tTexas',
              1: '',
              2: '',
              3: 'Born in El Paso , Texas , Owen served in the Texas House of Representatives from 1951 to 1955 and in the Texas State Senate from 1955 to 1965 .\tTexas\tTexas'},
             'Forks_Baddeck,_Nova_Scotia': {0: 'Forks Baddeck is a small community in the Canadian province of Nova Scotia , located in Victoria County on Cape Breton Island .\tNova Scotia\tNova Scotia\tCanadian\tCanada\tVictoria County\tVictoria County, Nova Scotia\tCape Breton Island\tCape Breton Island'},
             'G25': {0: 'G25 may refer to :',
              1: '',
              2: 'Logitech G25 , an electronic steering wheel designed for Sim racing video games on the PC , PS2 and PS3\tLogitech G25\tLogitech G25',
              3: '',
              4: 'Zenoah G-25 , a single cylinder , two stroke , carburetted aircraft engine\tZenoah G-25\tZenoah G-25',
              5: '',
              6: 'HMAS Nepal -LRB- G25 -RRB- , a 1941 N class destroyer of the Royal Australian Navy',
              7: '',
              8: 'G25 Changchun -- Shenzhen Expressway in China'},
             'Fork_Lake,_Alberta': {0: 'Fork Lake is an unincorporated community in northern Alberta , Canada .\tAlberta\tAlberta\tunincorporated community\tunincorporated community\tnorthern Alberta\tnorthern Alberta',
              1: 'It is located in Lac La Biche County , 6 km south of Highway 55 and 93 km west of Cold Lake .\tLac La Biche County\tLac La Biche County\tHighway 55\tAlberta Highway 55\tCold Lake\tCold Lake, Alberta',
              2: '',
              3: '',
              4: 'The community was named for a nearby , fork-shaped lake .'},
             'Fredrik_Riis': {0: 'Fredrik Riis -LRB- 29 January 1789 -- 22 October 1845 -RRB- was a Norwegian civil servant .\tNorwegian\tNorway\tcivil servant\tCivil service',
              1: '',
              2: '',
              3: 'He was born in Christiania , enrolled as a student in 1806 and graduated as cand.jur .\tChristiania\tOslo',
              4: 'in 1809 .',
              5: 'He worked as a police attorney from 1810 , police secretary from 1813 and stipendiary magistrate from 1816 .\tstipendiary magistrate\tstipendiary magistrate',
              6: '',
              7: '',
              8: 'He then held positions as County Governor in several Norwegian counties : in Nordre Bergenhus amt -LRB- today named Sogn og Fjordane -RRB- from 1831 to 1832 , Søndre Trondhjems amt -LRB- today named Sør-Trøndelag -RRB- 1832 -- 1840 and Akershus 1840 -- 1842 .\tNorwegian\tNorway\tCounty Governor\tCounty governor (Norway)\tcounties\tCounties of Norway\tAkershus\tList of County Governors of Akershus',
              9: '',
              10: '',
              11: 'When the county of Christiania stiftamt -LRB- today named Oslo -RRB- , which had shared governor with Akershus , got its own governor in 1842 , Riis was appointed to this position .\tChristiania\tOslo\tAkershus\tList of County Governors of Akershus',
              12: 'This post he held until his death in 1845 .',
              13: 'In Trondhjem he was a member of the Royal Norwegian Society of Sciences and Letters .\tNorwegian\tNorway\tRoyal Norwegian Society of Sciences and Letters\tRoyal Norwegian Society of Sciences and Letters'},
             'GAF_Materials_Corporation': {0: 'GAF is a company based in Parsippany , New Jersey , that has roots dating back to the late 19th century .\tParsippany\tParsippany-Troy Hills, New Jersey\tNew Jersey\tNew Jersey',
              1: 'The GAF acronym stands for General Aniline & Film .',
              2: 'The company has historically been primarily focused on manufacturing of roofing materials for residential and commercial applications .',
              3: 'At one time GAF was also active in manufacturing photographic film as well as cameras and projectors -LRB- both still and motion picture -RRB- , and was the manufacturer of the View-Master , the famous line of 3D transparencies , viewers and projectors .\tView-Master\tView-Master',
              4: "Briefly in the 1970s , it was the official film of Disneyland and at this time , actor Henry Fonda served as the company 's spokesman in several television commercials including one that featured Jodie Foster in her first acting role .\tDisneyland\tDisneyland\tHenry Fonda\tHenry Fonda\tJodie Foster\tJodie Foster"},
             'Frank_Drea': {0: "James Francis `` Frank '' Drea -LRB- July 7 , 1933 -- January 15 , 2003 -RRB- was a Canadian journalist , broadcaster , politician and racehorse enthusiast .\tCanadian\tCanada\tracehorse\tracehorse",
              1: 'He was a Progressive Conservative member of the Legislative Assembly of Ontario from 1971 to 1985 representing the riding of Scarborough Centre .\tScarborough Centre\tScarborough Centre (provincial electoral district)\tProgressive Conservative\tProgressive Conservative Party of Ontario\tOntario\tOntario\tLegislative Assembly of Ontario\tLegislative Assembly of Ontario',
              2: 'He served as a cabinet minister in the government of Premier Bill Davis .\tBill Davis\tBill Davis'},
             'Ford_Model_F': {0: 'The Ford Model F is an automobile produced by Ford .\tFord\tFord Motor Company\tautomobile\tautomobile',
              1: 'It was a development of the Model A and Model C , but was larger , more modern , and more luxurious .\tModel A\tFord Model A (1903)\tModel C\tFord Model C',
              2: 'Production started in 1905 and ended in 1906 after about 1,000 were made .',
              3: 'It was built at the Ford Piquette Avenue Plant .\tFord\tFord Motor Company\tFord Piquette Avenue Plant\tFord Piquette Avenue Plant',
              4: 'It was a four-seater phaeton with running boards and a side-entrance tonneau standard .\tphaeton\tPhaeton body\ttonneau\ttonneau',
              5: 'It was priced from to ; by contrast , the Colt Runabout was $ 1,500 , the FAL was $ 1,750 , the Cole 30 $ 1,500 , the Enger 40 $ 2,000 , and the Lozier Light Six Metropolitan $ 3,250 .\tColt Runabout\tColt Runabout Company\tFAL\tFal-Car\tCole 30\tCole (car company)\tEnger 40\tEnger Motor Car Company\tLozier\tLozier',
              6: 'All had green bodies .'},
             'Futaba_Channel': {0: ', or Futaba for short , is an imageboard in Japan .\timageboard\timageboard',
              1: 'It is a popular Japanese imageboard dealing in otaku and underground culture .\timageboard\timageboard\totaku\totaku\tunderground culture\tSubculture'},
             'Florence_Carlyle': {0: 'Florence Carlyle -LRB- 1864 -- May 2 , 1923 -RRB- was a Canadian figure and portrait painter in the modernist style , known especially as a colorist .\tCanadian\tCanadian\tportrait painter\tportrait painter\tcolorist\tcolorist',
              1: '',
              2: '',
              3: 'Born in Galt , Ontario , she was raised in Woodstock , Ontario , where her father , William Carlyle , was the county inspector of schools .',
              4: "William 's uncle -LRB- and Florence 's great-uncle -RRB- was the Scottish historian and philosopher Thomas Carlyle ; and William was said by a contemporary writer to have inherited `` much of the cleverness and the abstraction '' of his celebrated forebear .\tThomas Carlyle\tThomas Carlyle",
              5: "But it was Florence 's mother who , sensing her daughter 's art talent , arranged for an art teacher from New York City to provide lessons in an art studio set up to encourage her talents .",
              6: '',
              7: '',
              8: "Known throughout her life as `` Bird '' to family and friends , in 1890 , at age 26 , Florence Carlyle went to Paris where she studied at the Académie Julian under William Bouguereau , Jules Lefebvre and Tony Robert-Fleury .\tAcadémie Julian\tAcadémie Julian\tWilliam Bouguereau\tWilliam Bouguereau\tTony Robert-Fleury\tTony Robert-Fleury",
              9: 'In 1893 she exhibited her paintings at the Royal Academy , and three years later she returned to Canada .',
              10: '',
              11: '',
              12: 'She had studios in London and Woodstock , and in 1897 became the first woman to be elected an Associate of the Royal Canadian Academy .\tCanadian\tCanadian\tRoyal Canadian Academy\tRoyal Canadian Academy',
              13: 'In 1899 , she established a studio in New York City .',
              14: '',
              15: '',
              16: "The last twenty years of her life were spent in Crowborough , Sussex , England where she and a friend , Julie Hastings , bought an English cottage they called `` Sweet Haws '' .\tCrowborough\tCrowborough\tSussex\tSussex",
              17: '',
              18: '',
              19: 'Florence Carlyle died at Crowborough in the spring of 1923 .\tCrowborough\tCrowborough',
              20: 'Most of her work is in the collection of the Woodstock Art Gallery in Woodstock , Ontario .'},
             'Flora_Lewis': {0: 'Flora Lewis -LRB- 25 July 1922 -- June 2 , 2002 -RRB- was an American journalist .\tAmerican\tUnited States\tjournalist\tjournalist'},
             'Fułki': {0: 'Fułki -LSB- ` fuUki -RSB- is a village in the administrative district of Gmina Dalików , within Poddębice County , Łódź Voivodeship , in central Poland .\tVoivodeship\tVoivodeships of Poland\tŁódź\tŁódź\tCounty\tPowiat\tPoddębice\tPoddębice\tGmina\tGmina\tDalików\tDalików\tvillage\tvillage\tGmina Dalików\tGmina Dalików\tPoddębice County\tPoddębice County\tŁódź Voivodeship\tŁódź Voivodeship',
              1: 'It lies approximately 6 km south-west of Dalików , 8 km south-east of Poddębice , and 30 km west of the regional capital Łódź .\tŁódź\tŁódź\tPoddębice\tPoddębice\tDalików\tDalików'},
             'Francisco_Antón': {0: 'Francisco Antón Sanz -LRB- 1906 -- 14 January 1976 -RRB- was a Spanish communist leader .',
              1: 'He is known as the lover of Dolores Ibárruri during and after the Spanish Civil War -LRB- 1936 -- 39 -RRB- .\tDolores Ibárruri\tDolores Ibárruri\tSpanish Civil War\tSpanish Civil War',
              2: '',
              3: 'After the Republican defeat in 1939 he went into exile in France , Moscow , Mexico , Poland and Czechoslovakia .',
              4: '',
              5: 'During an internal power struggle in the early 1950s he was ousted from the leadership of the Spanish Communist Party -LRB- PCE -RRB- , but was later rehabilitated .\tSpanish Communist Party\tSpanish Communist Party'},
             'Fox_River_-LRB-Manitoba-RRB-': {0: 'The Fox River is a river in northern Manitoba , Canada .\tManitoba\tManitoba',
              1: 'It flows east-northeast parallel to and between the Nelson River to the north and the Hayes River to the south .\tNelson River\tNelson River\tHayes River\tHayes River',
              2: 'It joins the Hayes about 75 mi southeast of its mouth on Hudson Bay .',

In [14]:
wiki_index['Nikolaj_Coster-Waldau']

{0: 'Nikolaj Coster-Waldau -LRB- -LSB- neɡ̊olaɪ̯ kʰʌsd̥ɐ ˈʋald̥ɑʊ̯ -RSB- ; born 27 July 1970 -RRB- is a Danish actor , producer and screenwriter .',
 1: 'He graduated from Danish National School of Theatre in Copenhagen in 1993 .\tDanish National School of Theatre\tDanish National School of Theatre and Contemporary Dance\tCopenhagen\tCopenhagen',
 2: "Coster-Waldau 's breakthrough performance in Denmark was his role in the film Nightwatch -LRB- 1994 -RRB- .\tNightwatch\tNightwatch (1994 film)",
 3: 'Since then he has appeared in numerous films in his native Scandinavia and Europe in general , including Headhunters -LRB- 2011 -RRB- and A Thousand Times Good Night -LRB- 2013 -RRB- .\tHeadhunters\tHeadhunters (film)\tA Thousand Times Good Night\tA Thousand Times Good Night',
 4: '',
 5: '',
 6: 'In the United States , his debut film role was in the war film Black Hawk Down -LRB- 2001 -RRB- , playing Medal of Honor recipient Gary Gordon .\tBlack Hawk Down\tBlack Hawk Down (film)\tGary Gordon\tGary Gordon',
 7: 'He then played Detective John Amsterdam in the short-lived Fox television series New Amsterdam -LRB- 2008 -RRB- , as well as appearing as Frank Pike in the 2009 Fox television film Virtuality , originally intended as a pilot .\tFox television\tFox Broadcasting Company\tNew Amsterdam\tNew Amsterdam (TV series)\tVirtuality\tVirtuality (TV series)',
 8: 'He became widely known to a broad audience for his current role as Ser Jaime Lannister , in the HBO series Game of Thrones .\tJaime Lannister\tJaime Lannister\tHBO\tHBO\tGame of Thrones\tGame of Thrones',
 9: 'In 2017 , he became one of the highest paid actors on television and earned # 2 million per episode of Game of Thrones .\tGame of Thrones\tGame of Thrones\thighest paid actors on television\tList of highest paid American television stars'}

In [15]:
wiki_index['Fredvang_Bridges']

{0: 'The Fredvang Bridges -LRB- Fredvangbruene -RRB- are two cantilever bridges that connect the fishing village of Fredvang on Moskenesøya island with the neighboring island of Flakstadøya .\tcantilever bridges\tcantilever bridges\tfishing village\tfishing village\tFredvang\tFredvang\tMoskenesøya\tMoskenesøya\tFlakstadøya\tFlakstadøya',
 1: 'The bridges are located in the municipality of Flakstad in Nordland county , Norway .\tFlakstad\tFlakstad\tNorway\tNorway\tNordland\tNordland',
 2: '',
 3: '',
 4: 'The south bridge is called Kubholmleia Bridge -LRB- Kubholmleia bru -RRB- and the north bridge is Røssøystraumen Bridge -LRB- Røssøystraumen bru -RRB- .',
 5: 'Both bridges are 240 m long and have a main span of 115 m.',
 6: '',
 7: '',
 8: 'The bridges were opened in 1988 .',
 9: 'They are among many bridges that connect the islands of the Lofoten archipelago to each other .\tLofoten\tLofoten\tarchipelago\tarchipelago',
 10: 'The only other bridge connecting these two islands is the Kåkern Bridge .\tKåkern Bridge\tKåkern Bridge'}

In [16]:
wiki_index['Fredvang_Bridges'][0]

'The Fredvang Bridges -LRB- Fredvangbruene -RRB- are two cantilever bridges that connect the fishing village of Fredvang on Moskenesøya island with the neighboring island of Flakstadøya .\tcantilever bridges\tcantilever bridges\tfishing village\tfishing village\tFredvang\tFredvang\tMoskenesøya\tMoskenesøya\tFlakstadøya\tFlakstadøya'

We may notice that the sentence text is not entirely the text. The structure is something like this

<sentence_text> \t <mention1> \t <entity1> \t <mention2> \t <entity2> ...

This mention-entity is the sentence metadata which we don't need. Therefore, we 'll remove the metadata and just keep the sentence.

### 4.6.1 Removing Metadata from 'wiki_index' Sentences

In [17]:
# Removing Metadata from the sentences
for page, sentences in wiki_index.items():
    for sent_id, full_text in sentences.items():
        if full_text:
            wiki_index[page][sent_id] = full_text.split('\t')[0].strip()

In [18]:
wiki_index['Fredvang_Bridges'][0]

'The Fredvang Bridges -LRB- Fredvangbruene -RRB- are two cantilever bridges that connect the fishing village of Fredvang on Moskenesøya island with the neighboring island of Flakstadøya .'

In [19]:
# Saving the cleaned version
with open(r"E:\Users\Anirudh\Study\MS\Implementation\Thesis\datasets\Wiki-Dump\processed\wiki_index.pkl", "wb") as f:
    pickle.dump(wiki_index, f)

print("Overwriting the existing file with this cleaned version")

Overwriting the existing file with this cleaned version

## 4.7 Creating enriched_fever_index

Now, we have both the required files - fever_lookup & wiki_index to extract the required sentence and create a new dictionary 'enriched_fever_index' having the following structure

{
    <page name string>: [
        (<sentence_id>, <sentence_text_string>),
        (<sentence_id>, <sentence_text_string>),
        .
        .
        .
        (<sentence_id>, <sentence_text_string>),
    ],
    .
    .
    .
    <page name string>: [
        (<sentence_id>, <sentence_text_string>),
        (<sentence_id>, <sentence_text_string>),
        .
        .
        .
        (<sentence_id>, <sentence_text_string>),
    ],
}

To create this dictionary, we 'll extract the 'page name' & 'sentence id' from fever_index (loaded variable of fever_lookup) and use those to find the sentence from wiki_inedx. 

With all this information, we 'll create the above a dictionary as stated above.

In [20]:
# Loading the fever_lookup dictionary from the pickle file

with open(r"E:\Users\Anirudh\Study\MS\Implementation\Thesis\datasets\FEVER\pre-processed\fever_lookup.pkl", "rb") as f:
    fever_index = pickle.load(f)

fever_index

defaultdict(set,
            {'Nikolaj_Coster-Waldau': {0, 2, 3, 7, 8},
             'Fox_Broadcasting_Company': {0, 1, 2},
             'Roman_Atwood': {0, 1},
             'History_of_art': {0, 2},
             'Adrienne_Bailon': {0, 1, 8},
             'Homeland_-LRB-TV_series-RRB-': {0, 3},
             'Prisoners_of_War_-LRB-TV_series-RRB-': {0},
             'Boston_Celtics': {0, 3},
             'The_Ten_Commandments_-LRB-1956_film-RRB-': {0},
             'Tetris': {0, 18},
             'Cyndi_Lauper': {0, 2, 7, 21, 26},
             'The_Hunger_Games_-LRB-film-RRB-': {0,
              1,
              2,
              3,
              4,
              8,
              16,
              18,
              19,
              21,
              24,
              27},
             'Ryan_Gosling': {0, 3, 6, 7, 8, 9, 12, 17},
             'Chad': {0},
             'Stranger_Things': {0, 1, 2, 5, 6, 9, 13, 14, 16},
             'Ryan_Seacrest': {0},
             'Puerto_Rico': {0, 3, 6},
             'Michael_Giacchino': {0, 1},
             'Stranger_than_Fiction_-LRB-2006_film-RRB-': {0},
             'Chris_Hemsworth': {0, 1, 2, 7},
             'Selena': {0, 8, 15, 28, 33},
             "Robert_J._O'Neill_-LRB-U.S._Navy_SEAL-RRB-": {0, 1},
             'The_Silence_of_the_Lambs_-LRB-film-RRB-': {0, 1, 2, 5, 6},
             'Peggy_Sue_Got_Married': {0},
             'Francis_Ford_Coppola': {0, 4, 5, 8, 9, 10, 12},
             'Andy_Roddick': {0, 3, 7, 8, 11, 12},
             'Bed-In': {0, 1},
             'Tupac_Shakur': {0, 3, 4, 5, 11, 14, 15},
             'The_Jim_Henson_Company': {0, 1, 5},
             'Slovenia': {0, 1, 3, 7, 9, 17, 19, 29},
             'Eurozone': {0, 5},
             'Midwestern_United_States': {0, 4, 8, 9},
             'Saratoga_-LRB-film-RRB-': {0, 1, 4, 5},
             'J._Howard_Marshall': {0},
             'Infant': {0},
             'Grace_Jones': {0, 1, 7, 13, 14, 15, 17, 21, 22},
             'Lisbon': {0, 1, 19, 23},
             'Willie_Nelson': {0, 1, 2, 3, 6, 7, 8, 9, 23, 26, 33, 36, 37, 39},
             'Malcolm_Young': {0, 1, 8},
             'Newfoundland_and_Labrador': {0, 1, 3, 4, 5},
             'Furia_-LRB-film-RRB-': {0},
             'United_States': {0,
              2,
              3,
              4,
              5,
              7,
              10,
              12,
              16,
              17,
              18,
              19,
              28,
              29,
              30,
              35},
             'Sophie_Turner': {0, 1, 2, 5, 6},
             'Mother_Teresa': {0, 1, 2, 10, 11},
             'The_Smurfs_-LRB-film-RRB-': {0, 6, 7, 10},
             'C._S._Forester': {0},
             'Kong-COLON-_Skull_Island': {0, 1, 2, 3, 8},
             'The_Challenge_-LRB-TV_series-RRB-': {0, 5, 6, 17},
             'Berlin': {0, 1, 2, 3, 7, 17, 23},
             'South_Korea': {0, 2, 9, 10, 16, 19, 24, 27},
             'Hacksaw_Ridge': {0, 4, 5, 8},
             'Michael_Fassbender': {0, 1, 2, 3, 8, 9},
             'Red_Headed_Stranger': {0, 11, 21},
             'Paul_Bettany': {1, 2, 8},
             'Scotland': {0, 1, 2},
             'Hebrides': {0},
             'Uzbekistan': {10, 14, 15, 18},
             'Charles,_Prince_of_Wales': {0, 1, 5, 16, 17, 18},
             'Chester_Bennington': {0, 1, 2, 10},
             'Vincent_Cassel': {0, 1},
             'Pope_John_Paul_II_-LRB-miniseries-RRB-': {0, 11},
             'David_Beckham': {0, 1, 2, 3, 11, 12, 13, 14, 19, 24, 25, 26},
             'Indiana_Jones': {0, 1, 7, 14},
             'Brian_Wilson': {0, 6, 7, 22},
             'The_Great_Gatsby': {0, 1, 2, 7, 14},
             'Iron_Man_3': {0, 1, 2, 8},
             'La_La_Anthony': {0, 3, 4, 7},
             'Led_Zeppelin': {0, 1, 5, 6, 15, 23, 24},
             'Richard_Harris': {0, 1},
             'The_Fosters_-LRB-2013_TV_series-RRB-': {0, 1, 4},
             'Jonathan_Hensleigh': {0},
             'Filmfare': {0, 1, 2},
             'Buckingham_Palace': {0, 1, 7, 8, 15},
             'Sarah_Paulson': {0, 1, 2, 3, 4, 8, 9, 14},
             'David_Harbour': {0, 1},
             'Kazakhstan': {2, 4, 5, 10, 12, 13, 22, 33},
             'José_María_Chacón': {0, 1},
             'Liverpool_F.C.': {0, 1, 2, 5, 7, 8, 11, 12, 19},
             'Land_Rover': {0, 5, 7, 11},
             'Sully_-LRB-film-RRB-': {0, 1, 6},
             'Stanley_Tucci': {0, 3, 4},
             'Monk_-LRB-TV_series-RRB-': {0},
             'Brock_Lesnar': {0, 1, 5, 6, 9, 11, 15, 16, 17, 18, 23},
             'Khmer_Empire': {0, 1, 5},
             'On_the_Road_-LRB-film-RRB-': {1, 3, 5, 7},
             'Paramore_-LRB-album-RRB-': {0, 1, 2, 3, 13, 19},
             'Peter_Davison': {0, 1, 2, 3},
             '21_Jump_Street_-LRB-film-RRB-': {0, 4},
             'Philadelphia_Museum_of_Art': {2},
             'Dustin_Hoffman': {0, 1, 2, 5, 6, 9, 13},
             'Deadpool_-LRB-film-RRB-': {0, 1, 2, 5, 8, 13, 14, 17},
             'Stephon_Marbury': {0, 1},
             'Cerebral_palsy': {0, 1, 13, 20, 30, 31, 32, 33},
             'Alfred_Hitchcock': {0, 1, 2, 3, 6, 9, 19, 23},
             'Julius_Caesar_-LRB-1953_film-RRB-': {0, 2},
             'Pulp_Fiction': {0, 5, 13, 19},
             'Quentin_Tarantino': {0, 1, 2, 5, 6, 7, 9, 13, 14, 17, 21, 22},
             'Absolute_Beginners_-LRB-film-RRB-': {0, 1, 7, 9},
             'No_Reservations_-LRB-film-RRB-': {0, 1, 2, 5},
             'Claire_Danes': {1, 15},
             'Hugh_Dancy': {0, 1},
             'Dangerous_Liaisons': {0, 4, 5},
             'Academy_Awards': {0, 1, 2, 5, 7, 8, 11},
             'Academy_of_Motion_Picture_Arts_and_Sciences': {0, 8},
             'Hubert_Humphrey': {0, 1, 10, 11, 15},
             'Minneapolis': {0, 1, 5, 6, 7, 14},
             'Alex_Rodriguez': {0, 1, 3, 4, 6, 10, 21, 24, 25, 26},
             'Friendship': {2},
             'Judd_Apatow': {0, 1, 5, 8},
             'Massachusetts': {0, 1, 5, 7, 19, 23},
             'Giancarlo_Stanton': {0, 4, 5},
             'Chris_Pine': {0, 1, 2},
             'Trevor_Noah': {0, 6, 9},
             'Lucas_-LRB-film-RRB-': {0, 2},
             'Corey_Haim': {0, 10},
             'Ryan_Phillippe': {0, 1, 2, 7, 8},
             'Sean_Connery': {0, 1, 4, 5, 6},
             'Venom_-LRB-comics-RRB-': {0, 1, 2, 14},
             'Overwatch_-LRB-video_game-RRB-': {0,
              1,
              4,
              5,
              6,
              8,
              11,
              18,
              20,
              21,
              23},
             'Lily_James': {0, 1, 4, 6},
             'Jing_Tian': {0, 3},
             'Jennifer_Aniston': {0, 1, 2, 14, 17},
             'Sparta': {2, 6, 8, 19},
             'Isis': {0, 15},
             'International_relations': {0, 1, 9, 10},
             'Régine_Chassagne': {0, 1},
             'John_McCain': {0, 1, 13, 16, 17, 18, 19, 22, 23},
             'Farrah_Fawcett': {0, 1, 5, 6, 14, 15, 16, 17, 20, 23, 26},
             'The_Who': {0, 1, 2, 6, 7, 8, 20},
             'Planet_of_the_Apes_-LRB-1968_film-RRB-': {0,
              2,
              3,
              4,
              12,
              13,
              15,
              19},
             'Star_vs._the_Forces_of_Evil': {0},
             'Galaxy_Quest': {0},
             'Friends_with_Benefits_-LRB-film-RRB-': {0, 1},
             'Glenn_Close': {0, 2, 5, 8, 16, 21, 22, 23},
             'The_Real_Thing_-LRB-play-RRB-': {0, 1},
             'Zooey_Deschanel': {0, 4, 7, 8},
             'Seven_Days_in_May': {0, 1, 2},
             'Kirk_Douglas': {0, 1, 2, 3, 15},
             'Ava_Gardner': {0},
             'Burt_Lancaster': {0, 2},
             'Winnipeg': {0, 16},
             'Mark_Zuckerberg': {0, 1, 2, 5, 6, 16, 17},
             'Facebook': {0, 1, 4, 6, 23},
             'Rick_and_Morty': {0, 3, 8, 9},
             'Paul_Walker': {0, 2, 4, 12},
             'Clint_Eastwood': {0, 1, 2, 5, 6, 7, 10, 19},
             'Shonen_Jump_-LRB-magazine-RRB-': {0},
             'North_America': {0, 2},
             'Gilmore_Girls': {0, 1, 2, 3, 6, 19},
             'Honest_-LRB-Future_album-RRB-': {0, 6},
             'Pranab_Mukherjee': {0, 1},
             'Anonymous_-LRB-group-RRB-': {0, 1, 2, 5, 6, 10},
             'San_Francisco': {0, 1, 2, 3, 4, 7, 18, 19},
             'Laadla_-LRB-1994_film-RRB-': {0, 1},
             'Lily_Collins': {0, 2, 3, 4, 5, 8, 9, 10, 16},
             'Bangladesh': {0, 1, 2, 4, 5, 9, 10, 18, 21, 24, 30, 31, 34, 40},
             'Lisa_Lopes': {0, 1, 5, 8},
             'TLC_-LRB-group-RRB-': {0},
             'The_Formula_-LRB-1980_film-RRB-': {0},
             'John_G._Avildsen': {0},
             'Janet_Jackson': {0, 5, 12},
             'Transformers-COLON-_The_Last_Knight': {0, 2},
             'Morena_Baccarin': {0, 1, 2},
             'Ori_-LRB-Stargate-RRB-': {0},
             'Firefly_-LRB-TV_series-RRB-': {0},
             'Naturi_Naughton': {0, 1},
             'Paul_Pogba': {0, 4, 6},
             'Mel_Gibson': {0, 1, 4, 7, 8, 9, 13, 14, 15, 16},
             'WALL-E': {0, 2, 13},
             'Generation_X': {0, 1, 6, 9},
             'Islam': {1, 2, 3, 4, 5, 8, 20},
             'Jackie_Chan': {0, 2, 3, 8},
             'Earth': {0, 1, 6, 13, 21, 22, 23},
             'Larry_Junstrom': {0},
             'Canada': {0, 2, 3, 4, 10, 11, 17, 18, 22, 24, 25, 28, 29, 30},
             'Constitution_Act,_1982': {0},
             'Renaissance': {0, 1, 5, 12, 15},
             'Pluto': {0, 1, 6, 11, 12, 13, 19, 23, 24, 25},
             'Steve_Buscemi': {0, 1, 2, 6, 7, 8, 10},
             'Twenty_One_Pilots': {0, 1, 7},
             'Selena_Gomez': {0, 1, 4, 5, 6, 9, 10, 14, 15, 19, 20},
             'Big_Boi': {0, 1},
             'Outkast': {0, 4},
             'Priyanka_Chopra': {0, 1, 2, 19},
             'Chris_Pérez': {0, 1, 2, 4, 5, 6},
             'Tate_Ellington': {1, 2, 4},
             'Mr._Sunshine_-LRB-2011_TV_series-RRB-': {0, 2},
             'Dolly_Parton': {0, 1, 3, 14, 15, 17},
             'The_Amanda_Show': {0},
             '19th_G7_summit': {4, 5},
             'Ethiopia': {0, 2, 7, 9, 13, 22, 23, 24, 25, 29, 30, 37, 38},
             'Ted_Kaczynski': {0, 1, 2, 5, 6, 9, 17, 23},
             'Keith_Urban': {0, 1, 2, 5, 7, 8, 9, 12, 14, 15, 18, 20, 24},
             'Eminem': {0, 1, 2, 3, 4, 8, 9, 12, 16, 17, 20},
             'Connaught_Tunnel': {0, 2, 3, 5, 13, 24, 28, 29},
             'Ilkhanate': {0, 1, 2, 4, 5},
             'True_Blood': {0, 2, 5, 7},
             'Jordan_Knight': {0},
             'Adam_Driver': {0, 1, 6},
             'Thor-COLON-_The_Dark_World': {0, 1, 4, 12, 15, 16, 17},
             'Loki': {0, 1, 2},
             'Amsterdam': {0, 2, 3, 9, 23},
             'Inspectah_Deck': {0},
             'Tender_Mercies': {0, 2, 16, 17},
             'Cristiano_Ronaldo': {0, 2, 9, 10, 16, 19, 24, 28, 29, 30},
             'Paul_Simon': {0, 1, 11, 12, 15, 16},
             'Baby_Driver': {0, 4},
             'David_Dhawan': {0, 4},
             'Rumi': {0, 1, 3, 8, 10},
             'Swedish_Empire': {0, 1, 5},
             'Gustavus_Adolphus_of_Sweden': {0, 11},
             'Her_-LRB-film-RRB-': {0, 2, 3, 14, 15, 16, 17},
             'Las_Vegas': {0, 1, 2, 3, 14, 15},
             'Spread_-LRB-food-RRB-': {0, 3, 6},
             'Octavia_Spencer': {4},
             'Ramayanam_-LRB-film-RRB-': {0},
             'Man_of_Steel_-LRB-film-RRB-': {0, 4, 9, 11, 13, 16},
             'Leukemia': {0, 2, 3, 7, 9, 10, 21, 25, 26, 27, 28},
             'Judy_Garland': {0, 1, 5, 6, 9, 12, 13, 14},
             'Judgment_at_Nuremberg': {0},
             'Until_Dawn': {0, 1, 4, 6, 9},
             'Timothy_Olyphant': {0, 1, 10},
             'Telangana': {0, 1, 2, 3, 4, 7, 9, 10, 11},
             'Cheaper_by_the_Dozen_-LRB-2003_film-RRB-': {0, 1, 2},
             'House_of_Lusignan': {0, 6},
             'Ten_Commandments': {0, 1},
             'The_Hangover_Part_III': {0, 3, 4},
             'Ariana_Grande': {0, 1, 3, 6, 7, 11, 13, 15, 21, 23},
             'Ted_Bundy': {0, 7, 12, 13, 14, 17},
             'Chinese_people': {0},
             "Schindler's_List": {0, 18, 20},
             'Zeus': {0, 5},
             'List_of_thunder_gods': {1},
             'Escape_from_Planet_Earth': {0},
             'Venus_Williams': {0, 3, 7, 14, 15, 16, 17, 18, 29, 40},
             'The_Beatles': {0, 1, 2, 3, 6, 7, 9, 11, 12, 13, 16, 18, 21},
             '50_First_Dates': {0, 1},
             'A_Nightmare_on_Elm_Street': {0, 6, 7, 8},
             'Charlize_Theron': {0, 1, 4, 11},
             'The_Burning_Plain': {0, 1},
             'Jemaine_Clement': {0},
             'Usain_Bolt': {0, 1, 2, 3, 4, 7, 8, 9, 16, 17, 18, 19, 20},
             'Internet': {0, 1, 5, 6, 7},
             'Sarrainodu': {0, 1, 4},
             'Jawbreaker_-LRB-film-RRB-': {0, 1, 7},
             'Rose_McGowan': {0},
             'Kurt_Sutter': {0, 1, 2, 4},
             'Lisa_Marie_Presley': {0, 1},
             'Kingdom_Hearts_III': {0, 1, 2, 6},
             'Kingdom_Hearts': {0, 4, 5, 6},
             'Keanu_Reeves': {0, 3, 4, 5, 10, 11, 12, 16, 17, 18},
             'Dwayne_Johnson': {0, 1, 4, 5, 6, 9, 10, 11, 12, 21, 23, 26},
             'Heartland_-LRB-Canadian_TV_series-RRB-': {0},
             'Mango': {0, 4, 7},
             'William_Jennings_Bryan': {0, 1, 14, 15},
             'Democratic_Party_-LRB-United_States-RRB-': {0, 1, 9, 23, 30},
             'Iris_Murdoch': {0, 1},
             'David_Koepp': {0, 1, 7, 8},
             'Block_-LRB-basketball-RRB-': {0, 10},
             'Leroy_Jethro_Gibbs': {0, 1},
             'Leslie_Howard_-LRB-actor-RRB-': {0, 3},
             'Catching_Fire': {0, 1, 2, 5},
             'Avatar-COLON-_The_Last_Airbender': {0, 6},
             'Hopman_Cup': {4},
             'Frank_Zappa': {0, 2, 7, 10, 26},
             'Ruth_Negga': {0, 1, 2, 5},
             'Warcraft_-LRB-film-RRB-': {0, 7},
             'George_VI': {0, 8, 27, 28},
             'Psychology': {0, 1, 5, 8, 13, 16},
             'Humanities': {0},
             'The_Beach_Boys': {0, 1, 3, 8, 18, 22, 23},
             'Billy_Bob_Thornton': {0, 3, 4, 16},
             'The_Ren_&_Stimpy_Show': {0, 2},
             'Courteney_Cox': {1},
             'Ronin_-LRB-film-RRB-': {0},
             'Abraham_Lincoln': {0, 1, 2, 5, 7, 8, 9, 10, 22, 33},
             'Fred_Savage': {0},
             'Al_Capone': {0, 12, 17, 19, 20, 23, 24},
             'Neurosyphilis': {0},
             'Boston': {0, 7, 9, 11, 12, 15, 17, 18},
             'Shawmut_Peninsula': {0},
             'Interstellar_-LRB-film-RRB-': {3, 4, 18},
             'Britney_Spears': {0, 1, 2, 3, 4, 6, 7, 11, 13},
             'Mike_Tyson': {0, 1, 7, 9, 10, 17, 18, 21, 22, 27},
             'Hermetic_Order_of_the_Golden_Dawn': {0, 9},
             'Ellen_Burstyn': {0, 1, 4, 5, 8, 11, 15},
             'Princess_Agents': {0, 2},
             'Gwen_Stefani': {0, 1, 6, 14, 15, 16, 17, 18, 21},
             'James_Marsden': {0, 1, 2, 6},
             'Hairspray_-LRB-2007_film-RRB-': {1},
             'Carrie_Fisher': {0, 1, 4, 5, 6, 11},
             'Ice_hockey': {0, 4, 5, 6, 7, 8, 21},
             'The_Fifth_Element': {0, 2, 8, 14, 15},
             'Audi': {0, 13, 14, 15},
             'Indonesia': {0, 1, 3, 4, 9, 12, 13, 29},
             'Wyatt_Earp': {0, 1, 5, 6, 7, 8, 12, 13, 14, 15, 22, 34, 41, 44},
             'Brave_-LRB-2012_film-RRB-': {0, 1, 14},
             'Winter_Passing': {0, 3},
             'Audrey_Horne': {0, 1, 2, 3},
             'Pilot_-LRB-Twin_Peaks-RRB-': {0},
             'Line_of_Duty': {0, 1},
             'Dayton_Agreement': {0},
             'National_Security_Agency': {0, 1},
             'Gold': {0, 1, 2, 9, 15, 21, 22, 23, 28, 31},
             'Paleogene': {0},
             'Cher': {0, 1, 5, 7, 11, 15, 16, 21, 22, 25, 26},
             'Bernard_Madoff': {7, 8, 24},
             'Donkey_-LRB-Shrek-RRB-': {0, 1},
             'O._J._Simpson': {0, 3, 5, 9, 10, 13, 17, 18, 19},
             'Ketogenic_diet': {0, 13},
             'Dennis_Quaid': {0, 1, 2},
             'Thandie_Newton': {0, 1},
             'Reese_Witherspoon': {0, 1, 2, 3, 6, 7, 8, 10, 14, 15},
             'Jenni_Rivera': {0, 8, 9, 10, 11, 13, 16, 19},
             'Lo_Nuestro_Award_for_Regional_Mexican_Female_Artist_of_the_Year': {0},
             'Curly_Top_-LRB-film-RRB-': {0},
             'Edgar_Allan_Poe': {0},
             'Danny_DeVito': {0, 1, 4, 13, 17},
             'PageRank': {1, 3},
             'Jeffrey_Dahmer': {0, 1, 5, 9},
             'Naomi_Scott': {1, 2},
             'Minnesota_Vikings': {0, 1, 3},
             'L.A._Law': {0, 8},
             'Paradise_-LRB-Lana_Del_Rey_EP-RRB-': {0},
             'Dirt_-LRB-TV_series-RRB-': {0, 9, 12},
             'Arsenic_and_Old_Lace_-LRB-film-RRB-': {0, 2, 5},
             'The_Belko_Experiment': {0, 3},
             'Apple_Inc.': {0, 1, 2, 6, 7, 16, 22, 23},
             'Moscow': {0, 1, 4, 11, 16},
             'Cult_film': {4},
             'September_11_attacks': {0, 3, 4, 7, 8, 10, 12, 24},
             'Richard_III_-LRB-play-RRB-': {0, 7},
             'Kathy_Bates': {0, 1, 2, 3},
             'Joseph_Barbera': {0},
             'Penny_Dreadful_-LRB-TV_series-RRB-': {0, 1, 2, 3, 4, 8},
             'The_Lion_King': {0, 2, 4, 5, 9, 15, 22},
             'Before_We_Go': {0, 1, 2},
             'Stevie_Nicks': {0, 3, 5, 15, 21},
             'Andrew_Wood_-LRB-singer-RRB-': {0, 4, 6, 7, 10, 16},
             'James_McAvoy': {0, 1, 2, 5, 6, 12, 16, 18},
             'John_Constantine': {0, 1, 3, 8, 12, 13},
             'Portuguese_Empire': {0, 1, 4},
             'Eddie_Vedder': {0, 1, 5, 6},
             'Kenny_Rogers': {8, 9, 10, 13},
             'Kenny_-LRB-album-RRB-': {0},
             'Larry_Buttrose': {2},
             'Elementary_-LRB-TV_series-RRB-': {0, 1, 2, 12},
             'Lucy_Liu': {0, 8},
             'X-Men-COLON-_Days_of_Future_Past': {0, 2, 13},
             'San_Junipero': {0, 1},
             'John_F._Kennedy': {0, 2, 5, 6, 7, 11, 16, 17, 25, 26, 27},
             'Gift_of_the_Night_Fury': {0, 6},
             'Jay_Baruchel': {0},
             'Juana_la_virgen': {0},
             'The_Champ_-LRB-1979_film-RRB-': {0, 1},
             'Monarch_of_the_Glen_-LRB-TV_series-RRB-': {0},
             'Robert_Redford': {0, 4, 5, 16, 18, 22, 25},
             'Beasts_of_the_Southern_Wild': {0, 5, 6},
             'Los_Angeles_Lakers': {0, 1, 3, 8, 9, 10, 15, 16, 17, 24},
             'Philippines': {0, 1, 3, 11, 18, 27, 32},
             'Joe_Manganiello': {1, 5},
             'Veronika_Decides_to_Die_-LRB-film-RRB-': {0, 1},
             'Walter_Matthau': {0, 1, 2},
             'Lisa_Kudrow': {0, 1, 6, 11},
             'Myles_Kennedy': {0, 5, 6, 7, 10},
             'Jane_Fonda': {0, 5, 6, 8, 21},
             'Imagine_Dragons': {0, 1, 2, 3, 4, 5, 8, 9},
             'Mike_Love': {0, 5, 10, 11, 12, 15},
             'Star_Search': {0, 1},
             'System_of_a_Down': {4, 6, 7},
             'Peyton_Manning': {0, 1, 3, 8, 11, 12},
             'Davis_Entertainment': {0, 3},
             'Kafka_-LRB-film-RRB-': {2},
             'Ian_Holm': {0},
             'Charles_Marie_de_La_Condamine': {0},
             'Giada_De_Laurentiis': {0, 1},
             'Today_-LRB-U.S._TV_program-RRB-': {0},
             'Bohemian_Rhapsody': {0, 1, 2, 4, 7, 18},
             'Hugh_Jackman': {0, 1, 2, 3, 6, 8},
             'The_Prestige_-LRB-film-RRB-': {0, 1, 3, 4, 5, 8, 9},
             'Cate_Blanchett': {0, 1, 2, 3, 4, 7, 8, 9, 15, 16, 18},
             'Slash_-LRB-musician-RRB-': {0, 1, 2, 3, 5},
             'Drake_-LRB-musician-RRB-': {0, 2, 6, 7},
             'R._Madhavan': {0, 6, 7, 13, 14, 20},
             'James_and_the_Giant_Peach_-LRB-film-RRB-': {0, 1, 3},
             'Ayn_Rand': {0, 1, 3, 11},
             'Anne_Hathaway': {0, 1, 2, 3, 7, 8, 9, 14},
             'Oh_Yeon-seo': {0, 1},
             'Ben_Stiller': {0, 4, 5, 6, 10, 12},

In [21]:
enriched_fever_index = defaultdict(list)

# count how many lookups fail
missing_sentences = 0

for page, sentence_ids in fever_index.items():
    for sentence_id in sentence_ids:
        try:
            sent_text = wiki_index[page][sentence_id]
            enriched_fever_index[page].append((sentence_id, sent_text))
        except KeyError:
            enriched_fever_index[page].append((sentence_id, None))
            missing_sentences += 1
        
print(f"Enrichment complete. {missing_sentences} sentence(s) were not found.")

Enrichment complete. 165 sentence(s) were not found.

In [22]:
enriched_fever_index

defaultdict(list,
            {'Nikolaj_Coster-Waldau': [(0,
               'Nikolaj Coster-Waldau -LRB- -LSB- neɡ̊olaɪ̯ kʰʌsd̥ɐ ˈʋald̥ɑʊ̯ -RSB- ; born 27 July 1970 -RRB- is a Danish actor , producer and screenwriter .'),
              (2,
               "Coster-Waldau 's breakthrough performance in Denmark was his role in the film Nightwatch -LRB- 1994 -RRB- ."),
              (3,
               'Since then he has appeared in numerous films in his native Scandinavia and Europe in general , including Headhunters -LRB- 2011 -RRB- and A Thousand Times Good Night -LRB- 2013 -RRB- .'),
              (7,
               'He then played Detective John Amsterdam in the short-lived Fox television series New Amsterdam -LRB- 2008 -RRB- , as well as appearing as Frank Pike in the 2009 Fox television film Virtuality , originally intended as a pilot .'),
              (8,
               'He became widely known to a broad audience for his current role as Ser Jaime Lannister , in the HBO series Game of Thrones .')],
             'Fox_Broadcasting_Company': [(0,
               'The Fox Broadcasting Company -LRB- often shortened to Fox and stylized as FOX -RRB- is an American English language commercial broadcast television network that is owned by the Fox Entertainment Group subsidiary of 21st Century Fox .'),
              (1,
               'The network is headquartered at the 20th Century Fox studio lot on Pico Boulevard in the Century City section of Los Angeles , with additional major offices and production facilities at the Fox Television Center in nearby West Los Angeles and the Fox Broadcasting Center in the Yorkville neighborhood of Manhattan , New York City .'),
              (2,
               'It is the third largest major television network in the world based on total revenues , assets , and international coverage .')],
             'Roman_Atwood': [(0,
               'Roman Bernard Atwood -LRB- born May 28 , 1983 -RRB- is an American YouTube personality , comedian , vlogger and pranker .'),
              (1,
               'He is best known for his vlogs , where he posts updates about his life on a daily basis .')],
             'History_of_art': [(0,
               'The history of art is the history of any activity or product made by humans in a visual form for aesthetical or communicative purposes , expressing ideas , emotions or , in general , a worldview .'),
              (2,
               'The subsequent expansion of the list of principal arts in the 20th century reached to nine : architecture , dance , sculpture , music , painting , poetry -LRB- described broadly as a form of literature with aesthetic purpose or function , which also includes the distinct genres of theatre and narrative -RRB- , film , photography and graphic arts .')],
             'Adrienne_Bailon': [(0,
               'Adrienne Eliza Houghton -LRB- née Bailon ; born October 24 , 1983 -RRB- is an American singer-songwriter , recording artist , actress , dancer and television personality .'),
              (8,
               "Aside from her work in 3LW and The Cheetah Girls , Bailon went on to develop her own acting career with roles in The Cheetah Girls films , Coach Carter and the MTV film All You 've Got ."),
              (1,
               "Adrienne Bailon first became publicly known when she rose to fame as one of the founding members and singer of both 3LW -LRB- 1999 -- 2007 -RRB- and Disney 's The Cheetah Girls -LRB- 2003 -- 2008 -RRB- .")],
             'Homeland_-LRB-TV_series-RRB-': [(0,
               "Homeland is an American spy thriller television series developed by Howard Gordon and Alex Gansa based on the Israeli series Prisoners of War -LRB- Original title חטופים Hatufim , literally `` Abductees '' -RRB- , which was created by Gideon Raff ."),
              (3,
               'The series stars Claire Danes as Carrie Mathison , a Central Intelligence Agency officer with bipolar disorder , and Damian Lewis as Nicholas Brody , a U.S. Marine Corps Scout Sniper .')],
             'Prisoners_of_War_-LRB-TV_series-RRB-': [(0,
               "Prisoners of War -LRB- original title in -RRB- is an Israeli television drama series made by Keshet and originally aired on Israel 's Channel 2 from March to May 2010 .")],
             'Boston_Celtics': [(0,
               'The Boston Celtics -LRB- -LSB- ˈsɛltɪks -RSB- -RRB- are an American professional basketball team based in Boston , Massachusetts .'),
              (3,
               "The Celtics play their home games at the TD Garden , which they share with the National Hockey League -LRB- NHL -RRB- 's Boston Bruins .")],
             'The_Ten_Commandments_-LRB-1956_film-RRB-': [(0,
               'The Ten Commandments is a 1956 American biblical epic film produced , directed , and narrated by Cecil B. DeMille , shot in VistaVision -LRB- color by Technicolor -RRB- , and released by Paramount Pictures .')],
             'Tetris': [(0,
               'Tetris -LRB- , pronounced -LSB- ˈtɛtrʲɪs -RSB- -RRB- is a tile-matching puzzle video game , originally designed and programmed by Russian game designer Alexey Pajitnov .'),
              (18,
               'In January 2010 , it was announced that the Tetris franchise had sold more than 170 million copies , approximately 70 million physical copies and over 100 million copies for cell phones , making it the best selling paid-downloaded game of all time .')],
             'Cyndi_Lauper': [(0,
               "Cynthia Ann Stephanie `` Cyndi '' Lauper -LRB- born June 22 , 1953 -RRB- is an American singer , songwriter , actress and LGBTQ activist ."),
              (2,
               "Her debut solo album She 's So Unusual -LRB- 1983 -RRB- was the first debut female album to chart four top-five hits on the Billboard Hot 100 -- `` Girls Just Want to Have Fun '' , `` Time After Time '' , `` She Bop '' , and `` All Through the Night '' -- and earned Lauper the Best New Artist award at the 27th Grammy Awards in 1985 ."),
              (7,
               'Since 1989 , Lauper has released nine studio albums and participated in many other projects .'),
              (21,
               "Her debut album is included in Rolling Stone '' 's list of the 500 Greatest Albums of All Time , while Time After Time is included in Vh1 's list of the 100 Best Songs of the Past 25 years ."),
              (26,
               "Her charitable efforts were acknowledged in 2013 when the singer was invited as a special guest to attend US President Barack Obama 's second-term inaugural .")],
             'The_Hunger_Games_-LRB-film-RRB-': [(0,
               'The Hunger Games is a 2012 American dystopian science fiction adventure film directed by Gary Ross and based on the novel of the same name by Suzanne Collins .'),
              (1,
               'It is the first installment in The Hunger Games film series and was produced by Nina Jacobson and Jon Kilik , with a screenplay by Ross , Collins , and Billy Ray .'),
              (2,
               'The film stars Jennifer Lawrence , Josh Hutcherson , Liam Hemsworth , Woody Harrelson , Elizabeth Banks , Lenny Kravitz , Stanley Tucci , and Donald Sutherland .'),
              (3,
               "The story takes place in a dystopian post-apocalyptic future in the nation of Panem , where boys and girls between the ages of 12 and 18 must take part in the Hunger Games , a televised annual event in which the `` tributes '' are required to fight to the death until there is only one survivor ."),
              (4,
               "Katniss Everdeen -LRB- Lawrence -RRB- volunteers to take her younger sister 's place ."),
              (8,
               'Development of The Hunger Games began in March 2009 when Lions Gate Entertainment entered into a co-production agreement with Color Force , which had acquired the rights a few weeks earlier .'),
              (16,
               'The film was released on March 21 , 2012 , in some European countries and in the US on March 23 , 2012 , in both conventional theaters and digital IMAX theaters .'),
              (18,
               'When the film released , it set records for opening day -LRB- $ 67.3 million -RRB- and opening weekend for a non-sequel .'),
              (19,
               "At the time of its release , the film 's opening weekend gross -LRB- $ 152.5 million -RRB- was the third-largest of any movie in North America ."),
              (21,
               'The film was a massive box-office success by grossing over $ 694 million worldwide against its budget of $ 78 million , making it the third-highest-grossing film in the United States and ninth-highest-grossing worldwide of 2012 .'),
              (24,
               'A sequel , The Hunger Games : Catching Fire , was released on November 22 , 2013 , in the United States .'),
              (27,
               "The Hunger Games received positive reviews from critics , with praise for its themes and messages , as well as Jennifer Lawrence 's portrayal of Katniss , though there was criticism of the film 's use of shaky cam in the action sequences .")],
             'Ryan_Gosling': [(0,
               'Ryan Thomas Gosling -LRB- born November 12 , 1980 -RRB- is a Canadian actor and musician .'),
              (3,
               'His first starring film role was as a Jewish neo-Nazi in The Believer -LRB- 2001 -RRB- , and he went on to star in several independent films , including Murder by Numbers -LRB- 2002 -RRB- , The Slaughter Rule -LRB- 2002 -RRB- , and The United States of Leland -LRB- 2003 -RRB- .'),
              (6,
               'Gosling came to the attention of a wider audience in 2004 with a leading role in the commercially successful romantic drama The Notebook .'),
              (7,
               'His performance as a drug-addicted teacher in Half Nelson -LRB- 2006 -RRB- was nominated for an Academy Award and his performance as a socially inept loner in Lars and the Real Girl -LRB- 2007 -RRB- was nominated for a Golden Globe Award .'),
              (8,
               'After a three-year acting hiatus , Gosling starred in the marital drama Blue Valentine -LRB- 2010 -RRB- , earning him a second Golden Globe nomination .'),
              (9,
               'Gosling co-starred in three mainstream films in 2011the romantic comedy-drama Crazy , Stupid , Love , the political drama The Ides of March , and the action thriller Driveand received two more Golden Globe nominations .'),
              (12,
               'For the latter , he won a Golden Globe Award and received a second Oscar nomination .'),
              (17,
               'He is a supporter of PETA , Invisible Children and the Enough Project and has traveled to Chad , Uganda and eastern Congo to raise awareness about conflicts in the regions .')],
             'Chad': [(0,
               "Chad -LRB- -LSB- tʃæd -RSB- تشاد ; Tchad -LSB- tʃa -LRB- d -RRB- -RSB- -RRB- , officially the Republic of Chad -LRB- ; `` Republic of the Chad '' -RRB- , is a landlocked country in Central Africa .")],
             'Stranger_Things': [(0,
               'Stranger Things is an American science fiction-horror web television series created , written , directed and co-executive produced by the Duffer Brothers , as well as co-executive-produced by Shawn Levy and Dan Cohen .'),
              (1,
               'The first season stars Winona Ryder , David Harbour , Finn Wolfhard , Millie Bobby Brown , Gaten Matarazzo , Caleb McLaughlin , Natalia Dyer , Charlie Heaton , Cara Buono , and Matthew Modine , with Noah Schnapp and Joe Keery in recurring roles .'),
              (2,
               'The second season will see Schnapp and Keery promoted to series regulars , along with the addition of Sadie Sink and Dacre Montgomery .'),
              (5,
               "Set in the fictional town of Hawkins , Indiana in the 1980s , the first season focuses on the investigation into the disappearance of a young boy by his friends , older brother and traumatized mother and the local police chief , amid supernatural events occurring around the town including the appearance of a psychokinetic girl who helps the missing boy 's friends in their own search ."),
              (6,
               'The second season is set a year after the first , and deals with attempts of the characters to return to normal and consequences from that season .'),
              (9,
               'The Duffer Brothers developed the series as a mix of investigative drama alongside supernatural elements with childlike sensibilities , establishing its time frame in the 1980s and creating a homage #Noun to pop culture of that decade .'),
              (13, 'The series was released on Netflix on July 15 , 2016 .'),
              (14,
               'It received critical acclaim for its characterization , pacing , atmosphere , acting , soundtrack , directing , writing and homages to 1980s genre films .'),
              (16,
               'On August 31 , 2016 , Netflix renewed the series for a second season of nine episodes , which is set to be released on October 31 , 2017 .')],
             'Ryan_Seacrest': [(0,
               'Ryan John Seacrest -LRB- born December 24 , 1974 -RRB- is an American radio personality , television host and producer .')],
             'Puerto_Rico': [(0,
               "Puerto Rico -LRB- Spanish for `` Rich Port '' -RRB- , officially the Commonwealth of Puerto Rico -LRB- Estado Libre Asociado de Puerto Rico , `` Free Associated State of Puerto Rico '' -RRB- and briefly called Porto Rico , is an unincorporated territory of the United States located in the northeast Caribbean Sea ."),
              (3,
               'It is an archipelago that includes the main island of Puerto Rico and a number of smaller ones such as Mona , Culebra , and Vieques .'),
              (6, "The island 's population is approximately 3.4 million .")],
             'Michael_Giacchino': [(0,
               'Michael Giacchino -LRB- -LSB- dʒakˈkiːno -RSB- ; born October 10 , 1967 -RRB- is an American composer of music for films , television and video games .'),
              (1,
               "He composed the scores to the television series Lost , Alias and Fringe , the video ' game series Medal of Honor and Call of Duty and many films such as The Incredibles , Ratatouille , Up , Mission : Impossible - Ghost Protocol , Dawn of the Planet of the Apes , Jurassic World , Inside Out , Star Trek Beyond , Doctor Strange , Rogue One and Spider-Man : Homecoming .")],
             'Stranger_than_Fiction_-LRB-2006_film-RRB-': [(0,
               'Stranger than Fiction is a 2006 American fantasy comedy-drama film directed by Marc Forster , produced by Lindsay Doran , and written by Zach Helm .')],
             'Chris_Hemsworth': [(0,
               'Chris Hemsworth -LRB- born 11 August 1983 -RRB- is an Australian actor .'),
              (1,
               'He is known for playing Kim Hyde in the Australian TV series Home and Away -LRB- 2004-07 -RRB- and Thor in the Marvel Cinematic Universe since 2011 .'),
              (2,
               'Hemsworth has also appeared in the science fiction action film Star Trek -LRB- 2009 -RRB- , the thriller adventure A Perfect Getaway -LRB- 2009 -RRB- , the horror comedy The Cabin in the Woods -LRB- 2012 -RRB- , the dark-fantasy action film Snow White and the Huntsman -LRB- 2012 -RRB- , the war film Red Dawn -LRB- 2012 -RRB- , and the biographical sports drama film Rush -LRB- 2013 -RRB- .'),
              (7,
               'Hemsworth will reprise his role as George Kirk in the upcoming Star Trek sequel .')],
             'Selena': [(0,
               'Selena Quintanilla-Pérez -LRB- -LSB- seˈlena kintaˈniʝa ˈpeɾes -RSB- or -LSB- seˈlena kintaˈniʎa ˈpeɾeθ -RSB- April 16 , 1971 -- March 31 , 1995 -RRB- was an American singer , songwriter , spokesperson , model , actress , and fashion designer .'),
              (33,
               'In 1997 , Warner Bros. released Selena , a film about her life and career , which starred Jennifer Lopez as Selena and Lupe Ontiveros as Saldívar .'),
              (8, 'Selena began recording professionally in 1982 .'),
              (15,
               "The album 's commercial success led music critics to call the album the `` breakthrough '' recording of her musical career ."),
              (28,
               'On March 31 , 1995 , Selena was shot dead by Yolanda Saldívar , her friend and former employee of her Selena Etc. boutiques .')],
             "Robert_J._O'Neill_-LRB-U.S._Navy_SEAL-RRB-": [(0,
               "Robert J. `` Rob '' O'Neill -LRB- born April 10 , 1976 -RRB- is a former United States Navy sailor ."),
              (1,
               "A former U.S. Navy SEAL and special warfare operator , O'Neill is best known for claiming to have fired the head shots that killed Osama bin Laden during the raid on his Abbottabad compound on May 1 , 2011 .")],
             'The_Silence_of_the_Lambs_-LRB-film-RRB-': [(0,
               'The Silence of the Lambs is a 1991 American horror-thriller film directed by Jonathan Demme and starring Jodie Foster , Anthony Hopkins , and Scott Glenn .'),
              (1,
               'Adapted by Ted Tally from the 1988 novel of the same name by Thomas Harris , his second to feature the character of Dr. Hannibal Lecter ; a brilliant psychiatrist and cannibalistic serial killer , the film was the second adaptation of a Harris novel featuring Lecter , preceded by the Michael Mann-directed Manhunter in 1986 .'),
              (2,
               "In the film , Clarice Starling , a young U.S. FBI trainee , seeks the advice of the imprisoned Dr. Lecter to apprehend another serial killer , known only as `` Buffalo Bill '' ."),
              (5,
               'The Silence of the Lambs was released on February 14 , 1991 , and grossed $ 272.7 million worldwide against its $ 19 million budget .'),
              (6,
               "It was only the third film , the other two being It Happened One Night and One Flew Over the Cuckoo 's Nest , to win Academy Awards in all the top five categories : Best Picture , Best Actor , Best Actress , Best Director , and Adapted Screenplay .")],
             'Peggy_Sue_Got_Married': [(0,
               'Peggy Sue Got Married is a 1986 American comedy-drama film directed by Francis Ford Coppola starring Kathleen Turner as a woman on the verge of a divorce , who finds herself transported back to the days of her senior year in high school in 1960 .')],
             'Francis_Ford_Coppola': [(0,
               'Francis Ford Coppola -LRB- -LSB- pronˈkoʊpələ -RSB- born April 7 , 1939 -RRB- , also credited as Francis Coppola , is a semi-retired American film director , producer , and screenwriter .'),
              (4,
               'After directing The Rain People -LRB- 1969 -RRB- , he co-wrote the 1970 film Patton , earning the Academy Award for Best Original Screenplay along with co-writer Edmund H. North .'),
              (5,
               'His directorial prominence was cemented with the release in 1972 of The Godfather , a film which revolutionized movie-making in the gangster genre , earning praise from both critics and the public before winning three Academy Awards -- including his second Oscar -LRB- Best Adapted Screenplay , with Mario Puzo -RRB- , Best Picture , and his first nomination for Best Director .'),
              (8,
               'He followed with The Godfather Part II in 1974 , which became the first sequel to win the Academy Award for Best Picture .'),
              (9,
               'Highly regarded by critics , it brought him three more Academy Awards : Best Adapted Screenplay , Best Director and Best Picture , and made him the second director , after Billy Wilder , to be honored three times for the same film .'),
              (10,

### 4.7.1 Inspect Missing Entries

In [23]:
missing_entries = []

for page, entries in enriched_fever_index.items():
    for sent_id, sentence in entries:
        if sentence is None:
            missing_entries.append((page, sent_id))

# Show first few missing entries
for entry in missing_entries[:10]:
    print(f"Missing: Page = {entry[0]}, Sentence ID = {entry[1]}")

print(f"\nTotal entries with missing sentence: {len(missing_entries)}")

Missing: Page = José_María_Chacón, Sentence ID = 0
Missing: Page = José_María_Chacón, Sentence ID = 1
Missing: Page = Régine_Chassagne, Sentence ID = 0
Missing: Page = Régine_Chassagne, Sentence ID = 1
Missing: Page = Chris_Pérez, Sentence ID = 0
Missing: Page = Chris_Pérez, Sentence ID = 1
Missing: Page = Chris_Pérez, Sentence ID = 2
Missing: Page = Chris_Pérez, Sentence ID = 4
Missing: Page = Chris_Pérez, Sentence ID = 5
Missing: Page = Chris_Pérez, Sentence ID = 6

Total entries with missing sentence: 165

In [24]:
missing_entries

[('José_María_Chacón', 0),
 ('José_María_Chacón', 1),
 ('Régine_Chassagne', 0),
 ('Régine_Chassagne', 1),
 ('Chris_Pérez', 0),
 ('Chris_Pérez', 1),
 ('Chris_Pérez', 2),
 ('Chris_Pérez', 4),
 ('Chris_Pérez', 5),
 ('Chris_Pérez', 6),
 ('Beyoncé', 0),
 ('Beyoncé', 1),
 ('Beyoncé', 3),
 ('Beyoncé', 6),
 ('Beyoncé', 7),
 ('Beyoncé', 16),
 ('Beyoncé', 17),
 ('Beyoncé', 18),
 ('Beyoncé', 19),
 ('Beyoncé', 20),
 ('Frédéric_Auguste_Bartholdi', 0),
 ('Björn_Borg', 0),
 ('Citadelle_Laferrière', 0),
 ('Édith_Piaf', 0),
 ('Peer_Åström', 0),
 ('Peer_Åström', 1),
 ('Peer_Åström', 2),
 ('Peer_Åström', 8),
 ('Peer_Åström', 13),
 ('Christine_Daaé', 0),
 ('Ólafur_Arnalds', 0),
 ('Thérèse_Raquin', 0),
 ('Henri_Poincaré', 0),
 ('Daniela_Hantuchová', 0),
 ('Daniela_Hantuchová', 1),
 ('Daniela_Hantuchová', 9),
 ('2011_Vuelta_a_España', 16),
 ('Sofía_Vergara', 0),
 ('Sofía_Vergara', 11),
 ('Sofía_Vergara', 4),
 ('José_Aldo', 0),
 ('José_Aldo', 1),
 ('José_Aldo', 2),
 ('José_Aldo', 4),
 ('Ātman_-LRB-Hinduism-RRB-', 0),
 ('Ātman_-LRB-Hinduism-RRB-', 1),
 ('François_de_Belleforest', 0),
 ('François_de_Belleforest', 9),
 ('François_de_Belleforest', 10),
 ('François_de_Belleforest', 5),
 ('Grégory_Levasseur', 0),
 ('Thénardiers', 0),
 ('Nord-du-Québec', 4),
 ('2011_Copa_América', 0),
 ('Chéri_-LRB-film-RRB-', 0),
 ('Night_Attack_at_Târgovişte', 0),
 ('Night_Attack_at_Târgovişte', 10),
 ('Supercopa_de_España', 0),
 ('Tré_Cool', 0),
 ('Zlatan_Ibrahimović', 0),
 ('Zlatan_Ibrahimović', 7),
 ('Zlatan_Ibrahimović', 8),
 ('Zlatan_Ibrahimović', 10),
 ('Zlatan_Ibrahimović', 11),
 ('Zlatan_Ibrahimović', 20),
 ('Zlatan_Ibrahimović', 21),
 ('Ingólfr_Arnarson', 0),
 ("Coup_d'état", 0),
 ('Björk', 16),
 ('Björk', 1),
 ('Björk', 13),
 ('Charlotte_Brontë', 0),
 ('Charlotte_Brontë', 1),
 ('Julio_Cortázar', 0),
 ('Stellan_Skarsgård', 0),
 ('Sophia_Abrahão', 0),
 ('Perla_Farías', 0),
 ('Reichsführer-SS', 0),
 ("Musée_National_d'Art_Moderne", 0),
 ("Musée_National_d'Art_Moderne", 1),
 ('Grande_Armée', 0),
 ('Jean-Claude_Mézières', 0),
 ('Jean-Claude_Mézières', 6),
 ('Jean-Claude_Mézières', 7),
 ('Pedro_Álvares_Cabral', 0),
 ('Penélope_Cruz', 0),
 ('Penélope_Cruz', 12),
 ('Michael_Peña', 0),
 ('Björn_Ulvaeus', 0),
 ('Stefan_Kapičić', 0),
 ('Université_Laval', 0),
 ('Lasse_Hallström', 1),
 ('Chloë_Sevigny', 0),
 ("1991_Soviet_coup_d'état_attempt", 1),
 ('Chloë_Grace_Moretz', 0),
 ('Róisín_Murphy', 0),
 ('Padmé_Amidala', 0),
 ('Valérian_and_Laureline', 0),
 ('Ruy_López_de_Villalobos', 0),
 ('Dohány_Street_Synagogue', 0),
 ('Dohány_Street_Synagogue', 1),
 ('Yolanda_Saldívar', 0),
 ('Éomer', 0),
 ('François_Truffaut', 0),
 ('François_Truffaut', 4),
 ('Patrice_Chéreau', 0),
 ('École_Polytechnique_de_Montréal', 0),
 ('École_Polytechnique_de_Montréal', 2),
 ('Shōnen_manga', 0),
 ('Shōnen_manga', 3),
 ('Árpád', 0),
 ('Árpád', 1),
 ('İstanbul_Başakşehir_F.K.', 0),
 ('André_Téchiné', 0),
 ('Khloé_Kardashian', 3),
 ('Landnámabók', 0),
 ('Galápagos_Islands', 0),
 ('Býleistr', 0),
 ('Andy_García', 0),
 ('Andy_García', 1),
 ('Andy_García', 2),
 ('Andy_García', 5),
 ('Andy_García', 6),
 ('Paraná_River', 1),
 ('Condé_Nast', 0),
 ('Führer', 1),
 ('Recep_Tayyip_Erdoğan', 0),
 ('Fárbauti', 2),
 ('Rafael_Benítez', 0),
 ('Franco-Provençal_language', 0),
 ('Les_Misérables_-LRB-2012_film-RRB-', 0),
 ('Elizabeth_Báthory', 0),
 ("2014_Thai_coup_d'état", 1),
 ('Cédula_de_identidad', 0),
 ('Mélanie_Laurent', 0),
 ('Ricardo_Montalbán', 0),
 ('Ricardo_Montalbán', 4),
 ('Raven-Symoné', 0),
 ('Raven-Symoné', 23),
 ('Cléopâtre', 0),
 ('Cléopâtre', 1),
 ('Cléopâtre', 4),
 ('Sacré-Cœur,_Paris', 0),
 ('Sacré-Cœur,_Paris', 2),
 ('Édouard_Séguin', 0),
 ('Édouard_Séguin', 1),
 ('Selma_Lagerlöf', 0),
 ("1974_Cypriot_coup_d'état", 0),
 ('Opéra_de_Monte-Carlo', 0),
 ('Eugène_Ionesco', 0),
 ('Jacques_Clément', 6),
 ('Curaçao', 0),
 ('René_Goscinny', 0),
 ('Simón_Bolívar', 0),
 ('Janelle_Monáe', 0),
 ('José_Ferrer', 0),
 ('José_Ferrer', 4),
 ('Café_Society_-LRB-film-RRB-', 0),
 ('Raúl_Castro', 7),
 ('Noël_Coward', 0),
 ('Luis_Guzmán', 0),
 ("L'Oréal", 0),
 ("L'Oréal", 1),
 ('Víctor_Manuelle', 0),
 ('Pablo_Larraín', 0)]

This means that these 'page name' exist in fever_index but there is no match in the wiki_index.

Since, the fever_index is created out of the golden evidences of the fever dataset. Therefore, I should be able to find these in the 'FEVER_Merged_with_Golden_Evidence.jsonl' but when I try finding manually using 'ctrl + f', there is no result.

This might be because the names like 'José_María_Chacón' which includes characters like é, í, etc need to be normalized because "José_María_Chacón" != "José_María_Chacón" when compared byte-for-byte, even though they look the same because of the way they stored - NGD or NFC. 

Therefore, let's normalize the pages before we access them.

### 4.7.2 'Page Name' Normalization

In [25]:
fever_index

defaultdict(set,
            {'Nikolaj_Coster-Waldau': {0, 2, 3, 7, 8},
             'Fox_Broadcasting_Company': {0, 1, 2},
             'Roman_Atwood': {0, 1},
             'History_of_art': {0, 2},
             'Adrienne_Bailon': {0, 1, 8},
             'Homeland_-LRB-TV_series-RRB-': {0, 3},
             'Prisoners_of_War_-LRB-TV_series-RRB-': {0},
             'Boston_Celtics': {0, 3},
             'The_Ten_Commandments_-LRB-1956_film-RRB-': {0},
             'Tetris': {0, 18},
             'Cyndi_Lauper': {0, 2, 7, 21, 26},
             'The_Hunger_Games_-LRB-film-RRB-': {0,
              1,
              2,
              3,
              4,
              8,
              16,
              18,
              19,
              21,
              24,
              27},
             'Ryan_Gosling': {0, 3, 6, 7, 8, 9, 12, 17},
             'Chad': {0},
             'Stranger_Things': {0, 1, 2, 5, 6, 9, 13, 14, 16},
             'Ryan_Seacrest': {0},
             'Puerto_Rico': {0, 3, 6},
             'Michael_Giacchino': {0, 1},
             'Stranger_than_Fiction_-LRB-2006_film-RRB-': {0},
             'Chris_Hemsworth': {0, 1, 2, 7},
             'Selena': {0, 8, 15, 28, 33},
             "Robert_J._O'Neill_-LRB-U.S._Navy_SEAL-RRB-": {0, 1},
             'The_Silence_of_the_Lambs_-LRB-film-RRB-': {0, 1, 2, 5, 6},
             'Peggy_Sue_Got_Married': {0},
             'Francis_Ford_Coppola': {0, 4, 5, 8, 9, 10, 12},
             'Andy_Roddick': {0, 3, 7, 8, 11, 12},
             'Bed-In': {0, 1},
             'Tupac_Shakur': {0, 3, 4, 5, 11, 14, 15},
             'The_Jim_Henson_Company': {0, 1, 5},
             'Slovenia': {0, 1, 3, 7, 9, 17, 19, 29},
             'Eurozone': {0, 5},
             'Midwestern_United_States': {0, 4, 8, 9},
             'Saratoga_-LRB-film-RRB-': {0, 1, 4, 5},
             'J._Howard_Marshall': {0},
             'Infant': {0},
             'Grace_Jones': {0, 1, 7, 13, 14, 15, 17, 21, 22},
             'Lisbon': {0, 1, 19, 23},
             'Willie_Nelson': {0, 1, 2, 3, 6, 7, 8, 9, 23, 26, 33, 36, 37, 39},
             'Malcolm_Young': {0, 1, 8},
             'Newfoundland_and_Labrador': {0, 1, 3, 4, 5},
             'Furia_-LRB-film-RRB-': {0},
             'United_States': {0,
              2,
              3,
              4,
              5,
              7,
              10,
              12,
              16,
              17,
              18,
              19,
              28,
              29,
              30,
              35},
             'Sophie_Turner': {0, 1, 2, 5, 6},
             'Mother_Teresa': {0, 1, 2, 10, 11},
             'The_Smurfs_-LRB-film-RRB-': {0, 6, 7, 10},
             'C._S._Forester': {0},
             'Kong-COLON-_Skull_Island': {0, 1, 2, 3, 8},
             'The_Challenge_-LRB-TV_series-RRB-': {0, 5, 6, 17},
             'Berlin': {0, 1, 2, 3, 7, 17, 23},
             'South_Korea': {0, 2, 9, 10, 16, 19, 24, 27},
             'Hacksaw_Ridge': {0, 4, 5, 8},
             'Michael_Fassbender': {0, 1, 2, 3, 8, 9},
             'Red_Headed_Stranger': {0, 11, 21},
             'Paul_Bettany': {1, 2, 8},
             'Scotland': {0, 1, 2},
             'Hebrides': {0},
             'Uzbekistan': {10, 14, 15, 18},
             'Charles,_Prince_of_Wales': {0, 1, 5, 16, 17, 18},
             'Chester_Bennington': {0, 1, 2, 10},
             'Vincent_Cassel': {0, 1},
             'Pope_John_Paul_II_-LRB-miniseries-RRB-': {0, 11},
             'David_Beckham': {0, 1, 2, 3, 11, 12, 13, 14, 19, 24, 25, 26},
             'Indiana_Jones': {0, 1, 7, 14},
             'Brian_Wilson': {0, 6, 7, 22},
             'The_Great_Gatsby': {0, 1, 2, 7, 14},
             'Iron_Man_3': {0, 1, 2, 8},
             'La_La_Anthony': {0, 3, 4, 7},
             'Led_Zeppelin': {0, 1, 5, 6, 15, 23, 24},
             'Richard_Harris': {0, 1},
             'The_Fosters_-LRB-2013_TV_series-RRB-': {0, 1, 4},
             'Jonathan_Hensleigh': {0},
             'Filmfare': {0, 1, 2},
             'Buckingham_Palace': {0, 1, 7, 8, 15},
             'Sarah_Paulson': {0, 1, 2, 3, 4, 8, 9, 14},
             'David_Harbour': {0, 1},
             'Kazakhstan': {2, 4, 5, 10, 12, 13, 22, 33},
             'José_María_Chacón': {0, 1},
             'Liverpool_F.C.': {0, 1, 2, 5, 7, 8, 11, 12, 19},
             'Land_Rover': {0, 5, 7, 11},
             'Sully_-LRB-film-RRB-': {0, 1, 6},
             'Stanley_Tucci': {0, 3, 4},
             'Monk_-LRB-TV_series-RRB-': {0},
             'Brock_Lesnar': {0, 1, 5, 6, 9, 11, 15, 16, 17, 18, 23},
             'Khmer_Empire': {0, 1, 5},
             'On_the_Road_-LRB-film-RRB-': {1, 3, 5, 7},
             'Paramore_-LRB-album-RRB-': {0, 1, 2, 3, 13, 19},
             'Peter_Davison': {0, 1, 2, 3},
             '21_Jump_Street_-LRB-film-RRB-': {0, 4},
             'Philadelphia_Museum_of_Art': {2},
             'Dustin_Hoffman': {0, 1, 2, 5, 6, 9, 13},
             'Deadpool_-LRB-film-RRB-': {0, 1, 2, 5, 8, 13, 14, 17},
             'Stephon_Marbury': {0, 1},
             'Cerebral_palsy': {0, 1, 13, 20, 30, 31, 32, 33},
             'Alfred_Hitchcock': {0, 1, 2, 3, 6, 9, 19, 23},
             'Julius_Caesar_-LRB-1953_film-RRB-': {0, 2},
             'Pulp_Fiction': {0, 5, 13, 19},
             'Quentin_Tarantino': {0, 1, 2, 5, 6, 7, 9, 13, 14, 17, 21, 22},
             'Absolute_Beginners_-LRB-film-RRB-': {0, 1, 7, 9},
             'No_Reservations_-LRB-film-RRB-': {0, 1, 2, 5},
             'Claire_Danes': {1, 15},
             'Hugh_Dancy': {0, 1},
             'Dangerous_Liaisons': {0, 4, 5},
             'Academy_Awards': {0, 1, 2, 5, 7, 8, 11},
             'Academy_of_Motion_Picture_Arts_and_Sciences': {0, 8},
             'Hubert_Humphrey': {0, 1, 10, 11, 15},
             'Minneapolis': {0, 1, 5, 6, 7, 14},
             'Alex_Rodriguez': {0, 1, 3, 4, 6, 10, 21, 24, 25, 26},
             'Friendship': {2},
             'Judd_Apatow': {0, 1, 5, 8},
             'Massachusetts': {0, 1, 5, 7, 19, 23},
             'Giancarlo_Stanton': {0, 4, 5},
             'Chris_Pine': {0, 1, 2},
             'Trevor_Noah': {0, 6, 9},
             'Lucas_-LRB-film-RRB-': {0, 2},
             'Corey_Haim': {0, 10},
             'Ryan_Phillippe': {0, 1, 2, 7, 8},
             'Sean_Connery': {0, 1, 4, 5, 6},
             'Venom_-LRB-comics-RRB-': {0, 1, 2, 14},
             'Overwatch_-LRB-video_game-RRB-': {0,
              1,
              4,
              5,
              6,
              8,
              11,
              18,
              20,
              21,
              23},
             'Lily_James': {0, 1, 4, 6},
             'Jing_Tian': {0, 3},
             'Jennifer_Aniston': {0, 1, 2, 14, 17},
             'Sparta': {2, 6, 8, 19},
             'Isis': {0, 15},
             'International_relations': {0, 1, 9, 10},
             'Régine_Chassagne': {0, 1},
             'John_McCain': {0, 1, 13, 16, 17, 18, 19, 22, 23},
             'Farrah_Fawcett': {0, 1, 5, 6, 14, 15, 16, 17, 20, 23, 26},
             'The_Who': {0, 1, 2, 6, 7, 8, 20},
             'Planet_of_the_Apes_-LRB-1968_film-RRB-': {0,
              2,
              3,
              4,
              12,
              13,
              15,
              19},
             'Star_vs._the_Forces_of_Evil': {0},
             'Galaxy_Quest': {0},
             'Friends_with_Benefits_-LRB-film-RRB-': {0, 1},
             'Glenn_Close': {0, 2, 5, 8, 16, 21, 22, 23},
             'The_Real_Thing_-LRB-play-RRB-': {0, 1},
             'Zooey_Deschanel': {0, 4, 7, 8},
             'Seven_Days_in_May': {0, 1, 2},
             'Kirk_Douglas': {0, 1, 2, 3, 15},
             'Ava_Gardner': {0},
             'Burt_Lancaster': {0, 2},
             'Winnipeg': {0, 16},
             'Mark_Zuckerberg': {0, 1, 2, 5, 6, 16, 17},
             'Facebook': {0, 1, 4, 6, 23},
             'Rick_and_Morty': {0, 3, 8, 9},
             'Paul_Walker': {0, 2, 4, 12},
             'Clint_Eastwood': {0, 1, 2, 5, 6, 7, 10, 19},
             'Shonen_Jump_-LRB-magazine-RRB-': {0},
             'North_America': {0, 2},
             'Gilmore_Girls': {0, 1, 2, 3, 6, 19},
             'Honest_-LRB-Future_album-RRB-': {0, 6},
             'Pranab_Mukherjee': {0, 1},
             'Anonymous_-LRB-group-RRB-': {0, 1, 2, 5, 6, 10},
             'San_Francisco': {0, 1, 2, 3, 4, 7, 18, 19},
             'Laadla_-LRB-1994_film-RRB-': {0, 1},
             'Lily_Collins': {0, 2, 3, 4, 5, 8, 9, 10, 16},
             'Bangladesh': {0, 1, 2, 4, 5, 9, 10, 18, 21, 24, 30, 31, 34, 40},
             'Lisa_Lopes': {0, 1, 5, 8},
             'TLC_-LRB-group-RRB-': {0},
             'The_Formula_-LRB-1980_film-RRB-': {0},
             'John_G._Avildsen': {0},
             'Janet_Jackson': {0, 5, 12},
             'Transformers-COLON-_The_Last_Knight': {0, 2},
             'Morena_Baccarin': {0, 1, 2},
             'Ori_-LRB-Stargate-RRB-': {0},
             'Firefly_-LRB-TV_series-RRB-': {0},
             'Naturi_Naughton': {0, 1},
             'Paul_Pogba': {0, 4, 6},
             'Mel_Gibson': {0, 1, 4, 7, 8, 9, 13, 14, 15, 16},
             'WALL-E': {0, 2, 13},
             'Generation_X': {0, 1, 6, 9},
             'Islam': {1, 2, 3, 4, 5, 8, 20},
             'Jackie_Chan': {0, 2, 3, 8},
             'Earth': {0, 1, 6, 13, 21, 22, 23},
             'Larry_Junstrom': {0},
             'Canada': {0, 2, 3, 4, 10, 11, 17, 18, 22, 24, 25, 28, 29, 30},
             'Constitution_Act,_1982': {0},
             'Renaissance': {0, 1, 5, 12, 15},
             'Pluto': {0, 1, 6, 11, 12, 13, 19, 23, 24, 25},
             'Steve_Buscemi': {0, 1, 2, 6, 7, 8, 10},
             'Twenty_One_Pilots': {0, 1, 7},
             'Selena_Gomez': {0, 1, 4, 5, 6, 9, 10, 14, 15, 19, 20},
             'Big_Boi': {0, 1},
             'Outkast': {0, 4},
             'Priyanka_Chopra': {0, 1, 2, 19},
             'Chris_Pérez': {0, 1, 2, 4, 5, 6},
             'Tate_Ellington': {1, 2, 4},
             'Mr._Sunshine_-LRB-2011_TV_series-RRB-': {0, 2},
             'Dolly_Parton': {0, 1, 3, 14, 15, 17},
             'The_Amanda_Show': {0},
             '19th_G7_summit': {4, 5},
             'Ethiopia': {0, 2, 7, 9, 13, 22, 23, 24, 25, 29, 30, 37, 38},
             'Ted_Kaczynski': {0, 1, 2, 5, 6, 9, 17, 23},
             'Keith_Urban': {0, 1, 2, 5, 7, 8, 9, 12, 14, 15, 18, 20, 24},
             'Eminem': {0, 1, 2, 3, 4, 8, 9, 12, 16, 17, 20},
             'Connaught_Tunnel': {0, 2, 3, 5, 13, 24, 28, 29},
             'Ilkhanate': {0, 1, 2, 4, 5},
             'True_Blood': {0, 2, 5, 7},
             'Jordan_Knight': {0},
             'Adam_Driver': {0, 1, 6},
             'Thor-COLON-_The_Dark_World': {0, 1, 4, 12, 15, 16, 17},
             'Loki': {0, 1, 2},
             'Amsterdam': {0, 2, 3, 9, 23},
             'Inspectah_Deck': {0},
             'Tender_Mercies': {0, 2, 16, 17},
             'Cristiano_Ronaldo': {0, 2, 9, 10, 16, 19, 24, 28, 29, 30},
             'Paul_Simon': {0, 1, 11, 12, 15, 16},
             'Baby_Driver': {0, 4},
             'David_Dhawan': {0, 4},
             'Rumi': {0, 1, 3, 8, 10},
             'Swedish_Empire': {0, 1, 5},
             'Gustavus_Adolphus_of_Sweden': {0, 11},
             'Her_-LRB-film-RRB-': {0, 2, 3, 14, 15, 16, 17},
             'Las_Vegas': {0, 1, 2, 3, 14, 15},
             'Spread_-LRB-food-RRB-': {0, 3, 6},
             'Octavia_Spencer': {4},
             'Ramayanam_-LRB-film-RRB-': {0},
             'Man_of_Steel_-LRB-film-RRB-': {0, 4, 9, 11, 13, 16},
             'Leukemia': {0, 2, 3, 7, 9, 10, 21, 25, 26, 27, 28},
             'Judy_Garland': {0, 1, 5, 6, 9, 12, 13, 14},
             'Judgment_at_Nuremberg': {0},
             'Until_Dawn': {0, 1, 4, 6, 9},
             'Timothy_Olyphant': {0, 1, 10},
             'Telangana': {0, 1, 2, 3, 4, 7, 9, 10, 11},
             'Cheaper_by_the_Dozen_-LRB-2003_film-RRB-': {0, 1, 2},
             'House_of_Lusignan': {0, 6},
             'Ten_Commandments': {0, 1},
             'The_Hangover_Part_III': {0, 3, 4},
             'Ariana_Grande': {0, 1, 3, 6, 7, 11, 13, 15, 21, 23},
             'Ted_Bundy': {0, 7, 12, 13, 14, 17},
             'Chinese_people': {0},
             "Schindler's_List": {0, 18, 20},
             'Zeus': {0, 5},
             'List_of_thunder_gods': {1},
             'Escape_from_Planet_Earth': {0},
             'Venus_Williams': {0, 3, 7, 14, 15, 16, 17, 18, 29, 40},
             'The_Beatles': {0, 1, 2, 3, 6, 7, 9, 11, 12, 13, 16, 18, 21},
             '50_First_Dates': {0, 1},
             'A_Nightmare_on_Elm_Street': {0, 6, 7, 8},
             'Charlize_Theron': {0, 1, 4, 11},
             'The_Burning_Plain': {0, 1},
             'Jemaine_Clement': {0},
             'Usain_Bolt': {0, 1, 2, 3, 4, 7, 8, 9, 16, 17, 18, 19, 20},
             'Internet': {0, 1, 5, 6, 7},
             'Sarrainodu': {0, 1, 4},
             'Jawbreaker_-LRB-film-RRB-': {0, 1, 7},
             'Rose_McGowan': {0},
             'Kurt_Sutter': {0, 1, 2, 4},
             'Lisa_Marie_Presley': {0, 1},
             'Kingdom_Hearts_III': {0, 1, 2, 6},
             'Kingdom_Hearts': {0, 4, 5, 6},
             'Keanu_Reeves': {0, 3, 4, 5, 10, 11, 12, 16, 17, 18},
             'Dwayne_Johnson': {0, 1, 4, 5, 6, 9, 10, 11, 12, 21, 23, 26},
             'Heartland_-LRB-Canadian_TV_series-RRB-': {0},
             'Mango': {0, 4, 7},
             'William_Jennings_Bryan': {0, 1, 14, 15},
             'Democratic_Party_-LRB-United_States-RRB-': {0, 1, 9, 23, 30},
             'Iris_Murdoch': {0, 1},
             'David_Koepp': {0, 1, 7, 8},
             'Block_-LRB-basketball-RRB-': {0, 10},
             'Leroy_Jethro_Gibbs': {0, 1},
             'Leslie_Howard_-LRB-actor-RRB-': {0, 3},
             'Catching_Fire': {0, 1, 2, 5},
             'Avatar-COLON-_The_Last_Airbender': {0, 6},
             'Hopman_Cup': {4},
             'Frank_Zappa': {0, 2, 7, 10, 26},
             'Ruth_Negga': {0, 1, 2, 5},
             'Warcraft_-LRB-film-RRB-': {0, 7},
             'George_VI': {0, 8, 27, 28},
             'Psychology': {0, 1, 5, 8, 13, 16},
             'Humanities': {0},
             'The_Beach_Boys': {0, 1, 3, 8, 18, 22, 23},
             'Billy_Bob_Thornton': {0, 3, 4, 16},
             'The_Ren_&_Stimpy_Show': {0, 2},
             'Courteney_Cox': {1},
             'Ronin_-LRB-film-RRB-': {0},
             'Abraham_Lincoln': {0, 1, 2, 5, 7, 8, 9, 10, 22, 33},
             'Fred_Savage': {0},
             'Al_Capone': {0, 12, 17, 19, 20, 23, 24},
             'Neurosyphilis': {0},
             'Boston': {0, 7, 9, 11, 12, 15, 17, 18},
             'Shawmut_Peninsula': {0},
             'Interstellar_-LRB-film-RRB-': {3, 4, 18},
             'Britney_Spears': {0, 1, 2, 3, 4, 6, 7, 11, 13},
             'Mike_Tyson': {0, 1, 7, 9, 10, 17, 18, 21, 22, 27},
             'Hermetic_Order_of_the_Golden_Dawn': {0, 9},
             'Ellen_Burstyn': {0, 1, 4, 5, 8, 11, 15},
             'Princess_Agents': {0, 2},
             'Gwen_Stefani': {0, 1, 6, 14, 15, 16, 17, 18, 21},
             'James_Marsden': {0, 1, 2, 6},
             'Hairspray_-LRB-2007_film-RRB-': {1},
             'Carrie_Fisher': {0, 1, 4, 5, 6, 11},
             'Ice_hockey': {0, 4, 5, 6, 7, 8, 21},
             'The_Fifth_Element': {0, 2, 8, 14, 15},
             'Audi': {0, 13, 14, 15},
             'Indonesia': {0, 1, 3, 4, 9, 12, 13, 29},
             'Wyatt_Earp': {0, 1, 5, 6, 7, 8, 12, 13, 14, 15, 22, 34, 41, 44},
             'Brave_-LRB-2012_film-RRB-': {0, 1, 14},
             'Winter_Passing': {0, 3},
             'Audrey_Horne': {0, 1, 2, 3},
             'Pilot_-LRB-Twin_Peaks-RRB-': {0},
             'Line_of_Duty': {0, 1},
             'Dayton_Agreement': {0},
             'National_Security_Agency': {0, 1},
             'Gold': {0, 1, 2, 9, 15, 21, 22, 23, 28, 31},
             'Paleogene': {0},
             'Cher': {0, 1, 5, 7, 11, 15, 16, 21, 22, 25, 26},
             'Bernard_Madoff': {7, 8, 24},
             'Donkey_-LRB-Shrek-RRB-': {0, 1},
             'O._J._Simpson': {0, 3, 5, 9, 10, 13, 17, 18, 19},
             'Ketogenic_diet': {0, 13},
             'Dennis_Quaid': {0, 1, 2},
             'Thandie_Newton': {0, 1},
             'Reese_Witherspoon': {0, 1, 2, 3, 6, 7, 8, 10, 14, 15},
             'Jenni_Rivera': {0, 8, 9, 10, 11, 13, 16, 19},
             'Lo_Nuestro_Award_for_Regional_Mexican_Female_Artist_of_the_Year': {0},
             'Curly_Top_-LRB-film-RRB-': {0},
             'Edgar_Allan_Poe': {0},
             'Danny_DeVito': {0, 1, 4, 13, 17},
             'PageRank': {1, 3},
             'Jeffrey_Dahmer': {0, 1, 5, 9},
             'Naomi_Scott': {1, 2},
             'Minnesota_Vikings': {0, 1, 3},
             'L.A._Law': {0, 8},
             'Paradise_-LRB-Lana_Del_Rey_EP-RRB-': {0},
             'Dirt_-LRB-TV_series-RRB-': {0, 9, 12},
             'Arsenic_and_Old_Lace_-LRB-film-RRB-': {0, 2, 5},
             'The_Belko_Experiment': {0, 3},
             'Apple_Inc.': {0, 1, 2, 6, 7, 16, 22, 23},
             'Moscow': {0, 1, 4, 11, 16},
             'Cult_film': {4},
             'September_11_attacks': {0, 3, 4, 7, 8, 10, 12, 24},
             'Richard_III_-LRB-play-RRB-': {0, 7},
             'Kathy_Bates': {0, 1, 2, 3},
             'Joseph_Barbera': {0},
             'Penny_Dreadful_-LRB-TV_series-RRB-': {0, 1, 2, 3, 4, 8},
             'The_Lion_King': {0, 2, 4, 5, 9, 15, 22},
             'Before_We_Go': {0, 1, 2},
             'Stevie_Nicks': {0, 3, 5, 15, 21},
             'Andrew_Wood_-LRB-singer-RRB-': {0, 4, 6, 7, 10, 16},
             'James_McAvoy': {0, 1, 2, 5, 6, 12, 16, 18},
             'John_Constantine': {0, 1, 3, 8, 12, 13},
             'Portuguese_Empire': {0, 1, 4},
             'Eddie_Vedder': {0, 1, 5, 6},
             'Kenny_Rogers': {8, 9, 10, 13},
             'Kenny_-LRB-album-RRB-': {0},
             'Larry_Buttrose': {2},
             'Elementary_-LRB-TV_series-RRB-': {0, 1, 2, 12},
             'Lucy_Liu': {0, 8},
             'X-Men-COLON-_Days_of_Future_Past': {0, 2, 13},
             'San_Junipero': {0, 1},
             'John_F._Kennedy': {0, 2, 5, 6, 7, 11, 16, 17, 25, 26, 27},
             'Gift_of_the_Night_Fury': {0, 6},
             'Jay_Baruchel': {0},
             'Juana_la_virgen': {0},
             'The_Champ_-LRB-1979_film-RRB-': {0, 1},
             'Monarch_of_the_Glen_-LRB-TV_series-RRB-': {0},
             'Robert_Redford': {0, 4, 5, 16, 18, 22, 25},
             'Beasts_of_the_Southern_Wild': {0, 5, 6},
             'Los_Angeles_Lakers': {0, 1, 3, 8, 9, 10, 15, 16, 17, 24},
             'Philippines': {0, 1, 3, 11, 18, 27, 32},
             'Joe_Manganiello': {1, 5},
             'Veronika_Decides_to_Die_-LRB-film-RRB-': {0, 1},
             'Walter_Matthau': {0, 1, 2},
             'Lisa_Kudrow': {0, 1, 6, 11},
             'Myles_Kennedy': {0, 5, 6, 7, 10},
             'Jane_Fonda': {0, 5, 6, 8, 21},
             'Imagine_Dragons': {0, 1, 2, 3, 4, 5, 8, 9},
             'Mike_Love': {0, 5, 10, 11, 12, 15},
             'Star_Search': {0, 1},
             'System_of_a_Down': {4, 6, 7},
             'Peyton_Manning': {0, 1, 3, 8, 11, 12},
             'Davis_Entertainment': {0, 3},
             'Kafka_-LRB-film-RRB-': {2},
             'Ian_Holm': {0},
             'Charles_Marie_de_La_Condamine': {0},
             'Giada_De_Laurentiis': {0, 1},
             'Today_-LRB-U.S._TV_program-RRB-': {0},
             'Bohemian_Rhapsody': {0, 1, 2, 4, 7, 18},
             'Hugh_Jackman': {0, 1, 2, 3, 6, 8},
             'The_Prestige_-LRB-film-RRB-': {0, 1, 3, 4, 5, 8, 9},
             'Cate_Blanchett': {0, 1, 2, 3, 4, 7, 8, 9, 15, 16, 18},
             'Slash_-LRB-musician-RRB-': {0, 1, 2, 3, 5},
             'Drake_-LRB-musician-RRB-': {0, 2, 6, 7},
             'R._Madhavan': {0, 6, 7, 13, 14, 20},
             'James_and_the_Giant_Peach_-LRB-film-RRB-': {0, 1, 3},
             'Ayn_Rand': {0, 1, 3, 11},
             'Anne_Hathaway': {0, 1, 2, 3, 7, 8, 9, 14},
             'Oh_Yeon-seo': {0, 1},
             'Ben_Stiller': {0, 4, 5, 6, 10, 12},

In [26]:
# Normalize fever_index keys
normalized_fever_index = defaultdict(set)
for page, sent_id_set in fever_index.items():
    norm_page = normalize(page)
    normalized_fever_index[norm_page].update(sent_id_set)

# Normalize wiki_index keys
normalized_wiki_index = defaultdict(dict)
for page, sent_dict in wiki_index.items():
    norm_page = normalize(page)
    normalized_wiki_index[norm_page].update(sent_dict)

Now, we 'll try creating enriched index again and see the no. of missing pages now.

In [ ]:
# enriched_fever_index = defaultdict(list)

# # count how many lookups fail
# missing_sentences = 0

# for page, sentence_ids in normalized_fever_index.items():
#     for sentence_id in sentence_ids:
#         try:
#             sent_text = normalized_wiki_index[page][sentence_id]
#             enriched_fever_index[page].append((sentence_id, sent_text))
#         except KeyError:
#             enriched_fever_index[page].append((sentence_id, None))
#             missing_sentences += 1
        
# print(f"Enrichment complete. {missing_sentences} sentence(s) were not found.")

Enrichment complete. 0 sentence(s) were not found.

In [74]:
enriched_fever_index = defaultdict(dict)
missing_sentences = 0

for page, sentence_ids in fever_index.items():
    for sentence_id in sentence_ids:
        try:
            sent_text = wiki_index[page][sentence_id]
            enriched_fever_index[page][sentence_id] = sent_text
        except KeyError:
            enriched_fever_index[page][sentence_id] = None
            missing_sentences += 1

print(f"Enrichment complete. {missing_sentences} sentence(s) were not found.")

Enrichment complete. 0 sentence(s) were not found.

As there are no missing sentences, therefore, all the names have been successfully normalized. So, now we can safely replace old index with the new index

In [75]:
# Replacing the original fever_index and wiki_index with the normalized versions
fever_index = normalized_fever_index
wiki_index = normalized_wiki_index

In [76]:
enriched_fever_index

defaultdict(dict,
            {'Nikolaj_Coster-Waldau': {0: 'Nikolaj Coster-Waldau -LRB- -LSB- neɡ̊olaɪ̯ kʰʌsd̥ɐ ˈʋald̥ɑʊ̯ -RSB- ; born 27 July 1970 -RRB- is a Danish actor , producer and screenwriter .',
              2: "Coster-Waldau 's breakthrough performance in Denmark was his role in the film Nightwatch -LRB- 1994 -RRB- .",
              3: 'Since then he has appeared in numerous films in his native Scandinavia and Europe in general , including Headhunters -LRB- 2011 -RRB- and A Thousand Times Good Night -LRB- 2013 -RRB- .',
              7: 'He then played Detective John Amsterdam in the short-lived Fox television series New Amsterdam -LRB- 2008 -RRB- , as well as appearing as Frank Pike in the 2009 Fox television film Virtuality , originally intended as a pilot .',
              8: 'He became widely known to a broad audience for his current role as Ser Jaime Lannister , in the HBO series Game of Thrones .'},
             'Fox_Broadcasting_Company': {0: 'The Fox Broadcasting Company -LRB- often shortened to Fox and stylized as FOX -RRB- is an American English language commercial broadcast television network that is owned by the Fox Entertainment Group subsidiary of 21st Century Fox .',
              1: 'The network is headquartered at the 20th Century Fox studio lot on Pico Boulevard in the Century City section of Los Angeles , with additional major offices and production facilities at the Fox Television Center in nearby West Los Angeles and the Fox Broadcasting Center in the Yorkville neighborhood of Manhattan , New York City .',
              2: 'It is the third largest major television network in the world based on total revenues , assets , and international coverage .'},
             'Roman_Atwood': {0: 'Roman Bernard Atwood -LRB- born May 28 , 1983 -RRB- is an American YouTube personality , comedian , vlogger and pranker .',
              1: 'He is best known for his vlogs , where he posts updates about his life on a daily basis .'},
             'History_of_art': {0: 'The history of art is the history of any activity or product made by humans in a visual form for aesthetical or communicative purposes , expressing ideas , emotions or , in general , a worldview .',
              2: 'The subsequent expansion of the list of principal arts in the 20th century reached to nine : architecture , dance , sculpture , music , painting , poetry -LRB- described broadly as a form of literature with aesthetic purpose or function , which also includes the distinct genres of theatre and narrative -RRB- , film , photography and graphic arts .'},
             'Adrienne_Bailon': {0: 'Adrienne Eliza Houghton -LRB- née Bailon ; born October 24 , 1983 -RRB- is an American singer-songwriter , recording artist , actress , dancer and television personality .',
              8: "Aside from her work in 3LW and The Cheetah Girls , Bailon went on to develop her own acting career with roles in The Cheetah Girls films , Coach Carter and the MTV film All You 've Got .",
              1: "Adrienne Bailon first became publicly known when she rose to fame as one of the founding members and singer of both 3LW -LRB- 1999 -- 2007 -RRB- and Disney 's The Cheetah Girls -LRB- 2003 -- 2008 -RRB- ."},
             'Homeland_-LRB-TV_series-RRB-': {0: "Homeland is an American spy thriller television series developed by Howard Gordon and Alex Gansa based on the Israeli series Prisoners of War -LRB- Original title חטופים Hatufim , literally `` Abductees '' -RRB- , which was created by Gideon Raff .",
              3: 'The series stars Claire Danes as Carrie Mathison , a Central Intelligence Agency officer with bipolar disorder , and Damian Lewis as Nicholas Brody , a U.S. Marine Corps Scout Sniper .'},
             'Prisoners_of_War_-LRB-TV_series-RRB-': {0: "Prisoners of War -LRB- original title in -RRB- is an Israeli television drama series made by Keshet and originally aired on Israel 's Channel 2 from March to May 2010 ."},
             'Boston_Celtics': {0: 'The Boston Celtics -LRB- -LSB- ˈsɛltɪks -RSB- -RRB- are an American professional basketball team based in Boston , Massachusetts .',
              3: "The Celtics play their home games at the TD Garden , which they share with the National Hockey League -LRB- NHL -RRB- 's Boston Bruins ."},
             'The_Ten_Commandments_-LRB-1956_film-RRB-': {0: 'The Ten Commandments is a 1956 American biblical epic film produced , directed , and narrated by Cecil B. DeMille , shot in VistaVision -LRB- color by Technicolor -RRB- , and released by Paramount Pictures .'},
             'Tetris': {0: 'Tetris -LRB- , pronounced -LSB- ˈtɛtrʲɪs -RSB- -RRB- is a tile-matching puzzle video game , originally designed and programmed by Russian game designer Alexey Pajitnov .',
              18: 'In January 2010 , it was announced that the Tetris franchise had sold more than 170 million copies , approximately 70 million physical copies and over 100 million copies for cell phones , making it the best selling paid-downloaded game of all time .'},
             'Cyndi_Lauper': {0: "Cynthia Ann Stephanie `` Cyndi '' Lauper -LRB- born June 22 , 1953 -RRB- is an American singer , songwriter , actress and LGBTQ activist .",
              2: "Her debut solo album She 's So Unusual -LRB- 1983 -RRB- was the first debut female album to chart four top-five hits on the Billboard Hot 100 -- `` Girls Just Want to Have Fun '' , `` Time After Time '' , `` She Bop '' , and `` All Through the Night '' -- and earned Lauper the Best New Artist award at the 27th Grammy Awards in 1985 .",
              21: "Her debut album is included in Rolling Stone '' 's list of the 500 Greatest Albums of All Time , while Time After Time is included in Vh1 's list of the 100 Best Songs of the Past 25 years .",
              7: 'Since 1989 , Lauper has released nine studio albums and participated in many other projects .',
              26: "Her charitable efforts were acknowledged in 2013 when the singer was invited as a special guest to attend US President Barack Obama 's second-term inaugural ."},
             'The_Hunger_Games_-LRB-film-RRB-': {0: 'The Hunger Games is a 2012 American dystopian science fiction adventure film directed by Gary Ross and based on the novel of the same name by Suzanne Collins .',
              1: 'It is the first installment in The Hunger Games film series and was produced by Nina Jacobson and Jon Kilik , with a screenplay by Ross , Collins , and Billy Ray .',
              2: 'The film stars Jennifer Lawrence , Josh Hutcherson , Liam Hemsworth , Woody Harrelson , Elizabeth Banks , Lenny Kravitz , Stanley Tucci , and Donald Sutherland .',
              3: "The story takes place in a dystopian post-apocalyptic future in the nation of Panem , where boys and girls between the ages of 12 and 18 must take part in the Hunger Games , a televised annual event in which the `` tributes '' are required to fight to the death until there is only one survivor .",
              4: "Katniss Everdeen -LRB- Lawrence -RRB- volunteers to take her younger sister 's place .",
              8: 'Development of The Hunger Games began in March 2009 when Lions Gate Entertainment entered into a co-production agreement with Color Force , which had acquired the rights a few weeks earlier .',
              16: 'The film was released on March 21 , 2012 , in some European countries and in the US on March 23 , 2012 , in both conventional theaters and digital IMAX theaters .',
              18: 'When the film released , it set records for opening day -LRB- $ 67.3 million -RRB- and opening weekend for a non-sequel .',
              19: "At the time of its release , the film 's opening weekend gross -LRB- $ 152.5 million -RRB- was the third-largest of any movie in North America .",
              21: 'The film was a massive box-office success by grossing over $ 694 million worldwide against its budget of $ 78 million , making it the third-highest-grossing film in the United States and ninth-highest-grossing worldwide of 2012 .',
              24: 'A sequel , The Hunger Games : Catching Fire , was released on November 22 , 2013 , in the United States .',
              27: "The Hunger Games received positive reviews from critics , with praise for its themes and messages , as well as Jennifer Lawrence 's portrayal of Katniss , though there was criticism of the film 's use of shaky cam in the action sequences ."},
             'Ryan_Gosling': {0: 'Ryan Thomas Gosling -LRB- born November 12 , 1980 -RRB- is a Canadian actor and musician .',
              3: 'His first starring film role was as a Jewish neo-Nazi in The Believer -LRB- 2001 -RRB- , and he went on to star in several independent films , including Murder by Numbers -LRB- 2002 -RRB- , The Slaughter Rule -LRB- 2002 -RRB- , and The United States of Leland -LRB- 2003 -RRB- .',
              6: 'Gosling came to the attention of a wider audience in 2004 with a leading role in the commercially successful romantic drama The Notebook .',
              7: 'His performance as a drug-addicted teacher in Half Nelson -LRB- 2006 -RRB- was nominated for an Academy Award and his performance as a socially inept loner in Lars and the Real Girl -LRB- 2007 -RRB- was nominated for a Golden Globe Award .',
              8: 'After a three-year acting hiatus , Gosling starred in the marital drama Blue Valentine -LRB- 2010 -RRB- , earning him a second Golden Globe nomination .',
              9: 'Gosling co-starred in three mainstream films in 2011the romantic comedy-drama Crazy , Stupid , Love , the political drama The Ides of March , and the action thriller Driveand received two more Golden Globe nominations .',
              12: 'For the latter , he won a Golden Globe Award and received a second Oscar nomination .',
              17: 'He is a supporter of PETA , Invisible Children and the Enough Project and has traveled to Chad , Uganda and eastern Congo to raise awareness about conflicts in the regions .'},
             'Chad': {0: "Chad -LRB- -LSB- tʃæd -RSB- تشاد ; Tchad -LSB- tʃa -LRB- d -RRB- -RSB- -RRB- , officially the Republic of Chad -LRB- ; `` Republic of the Chad '' -RRB- , is a landlocked country in Central Africa ."},
             'Stranger_Things': {0: 'Stranger Things is an American science fiction-horror web television series created , written , directed and co-executive produced by the Duffer Brothers , as well as co-executive-produced by Shawn Levy and Dan Cohen .',
              1: 'The first season stars Winona Ryder , David Harbour , Finn Wolfhard , Millie Bobby Brown , Gaten Matarazzo , Caleb McLaughlin , Natalia Dyer , Charlie Heaton , Cara Buono , and Matthew Modine , with Noah Schnapp and Joe Keery in recurring roles .',
              2: 'The second season will see Schnapp and Keery promoted to series regulars , along with the addition of Sadie Sink and Dacre Montgomery .',
              5: "Set in the fictional town of Hawkins , Indiana in the 1980s , the first season focuses on the investigation into the disappearance of a young boy by his friends , older brother and traumatized mother and the local police chief , amid supernatural events occurring around the town including the appearance of a psychokinetic girl who helps the missing boy 's friends in their own search .",
              6: 'The second season is set a year after the first , and deals with attempts of the characters to return to normal and consequences from that season .',
              9: 'The Duffer Brothers developed the series as a mix of investigative drama alongside supernatural elements with childlike sensibilities , establishing its time frame in the 1980s and creating a homage #Noun to pop culture of that decade .',
              13: 'The series was released on Netflix on July 15 , 2016 .',
              14: 'It received critical acclaim for its characterization , pacing , atmosphere , acting , soundtrack , directing , writing and homages to 1980s genre films .',
              16: 'On August 31 , 2016 , Netflix renewed the series for a second season of nine episodes , which is set to be released on October 31 , 2017 .'},
             'Ryan_Seacrest': {0: 'Ryan John Seacrest -LRB- born December 24 , 1974 -RRB- is an American radio personality , television host and producer .'},
             'Puerto_Rico': {0: "Puerto Rico -LRB- Spanish for `` Rich Port '' -RRB- , officially the Commonwealth of Puerto Rico -LRB- Estado Libre Asociado de Puerto Rico , `` Free Associated State of Puerto Rico '' -RRB- and briefly called Porto Rico , is an unincorporated territory of the United States located in the northeast Caribbean Sea .",
              3: 'It is an archipelago that includes the main island of Puerto Rico and a number of smaller ones such as Mona , Culebra , and Vieques .',
              6: "The island 's population is approximately 3.4 million ."},
             'Michael_Giacchino': {0: 'Michael Giacchino -LRB- -LSB- dʒakˈkiːno -RSB- ; born October 10 , 1967 -RRB- is an American composer of music for films , television and video games .',
              1: "He composed the scores to the television series Lost , Alias and Fringe , the video ' game series Medal of Honor and Call of Duty and many films such as The Incredibles , Ratatouille , Up , Mission : Impossible - Ghost Protocol , Dawn of the Planet of the Apes , Jurassic World , Inside Out , Star Trek Beyond , Doctor Strange , Rogue One and Spider-Man : Homecoming ."},
             'Stranger_than_Fiction_-LRB-2006_film-RRB-': {0: 'Stranger than Fiction is a 2006 American fantasy comedy-drama film directed by Marc Forster , produced by Lindsay Doran , and written by Zach Helm .'},
             'Chris_Hemsworth': {0: 'Chris Hemsworth -LRB- born 11 August 1983 -RRB- is an Australian actor .',
              1: 'He is known for playing Kim Hyde in the Australian TV series Home and Away -LRB- 2004-07 -RRB- and Thor in the Marvel Cinematic Universe since 2011 .',
              2: 'Hemsworth has also appeared in the science fiction action film Star Trek -LRB- 2009 -RRB- , the thriller adventure A Perfect Getaway -LRB- 2009 -RRB- , the horror comedy The Cabin in the Woods -LRB- 2012 -RRB- , the dark-fantasy action film Snow White and the Huntsman -LRB- 2012 -RRB- , the war film Red Dawn -LRB- 2012 -RRB- , and the biographical sports drama film Rush -LRB- 2013 -RRB- .',
              7: 'Hemsworth will reprise his role as George Kirk in the upcoming Star Trek sequel .'},
             'Selena': {0: 'Selena Quintanilla-Pérez -LRB- -LSB- seˈlena kintaˈniʝa ˈpeɾes -RSB- or -LSB- seˈlena kintaˈniʎa ˈpeɾeθ -RSB- April 16 , 1971 -- March 31 , 1995 -RRB- was an American singer , songwriter , spokesperson , model , actress , and fashion designer .',
              33: 'In 1997 , Warner Bros. released Selena , a film about her life and career , which starred Jennifer Lopez as Selena and Lupe Ontiveros as Saldívar .',
              8: 'Selena began recording professionally in 1982 .',
              28: 'On March 31 , 1995 , Selena was shot dead by Yolanda Saldívar , her friend and former employee of her Selena Etc. boutiques .',
              15: "The album 's commercial success led music critics to call the album the `` breakthrough '' recording of her musical career ."},
             "Robert_J._O'Neill_-LRB-U.S._Navy_SEAL-RRB-": {0: "Robert J. `` Rob '' O'Neill -LRB- born April 10 , 1976 -RRB- is a former United States Navy sailor .",
              1: "A former U.S. Navy SEAL and special warfare operator , O'Neill is best known for claiming to have fired the head shots that killed Osama bin Laden during the raid on his Abbottabad compound on May 1 , 2011 ."},
             'The_Silence_of_the_Lambs_-LRB-film-RRB-': {0: 'The Silence of the Lambs is a 1991 American horror-thriller film directed by Jonathan Demme and starring Jodie Foster , Anthony Hopkins , and Scott Glenn .',
              1: 'Adapted by Ted Tally from the 1988 novel of the same name by Thomas Harris , his second to feature the character of Dr. Hannibal Lecter ; a brilliant psychiatrist and cannibalistic serial killer , the film was the second adaptation of a Harris novel featuring Lecter , preceded by the Michael Mann-directed Manhunter in 1986 .',
              2: "In the film , Clarice Starling , a young U.S. FBI trainee , seeks the advice of the imprisoned Dr. Lecter to apprehend another serial killer , known only as `` Buffalo Bill '' .",
              5: 'The Silence of the Lambs was released on February 14 , 1991 , and grossed $ 272.7 million worldwide against its $ 19 million budget .',
              6: "It was only the third film , the other two being It Happened One Night and One Flew Over the Cuckoo 's Nest , to win Academy Awards in all the top five categories : Best Picture , Best Actor , Best Actress , Best Director , and Adapted Screenplay ."},
             'Peggy_Sue_Got_Married': {0: 'Peggy Sue Got Married is a 1986 American comedy-drama film directed by Francis Ford Coppola starring Kathleen Turner as a woman on the verge of a divorce , who finds herself transported back to the days of her senior year in high school in 1960 .'},
             'Francis_Ford_Coppola': {0: 'Francis Ford Coppola -LRB- -LSB- pronˈkoʊpələ -RSB- born April 7 , 1939 -RRB- , also credited as Francis Coppola , is a semi-retired American film director , producer , and screenwriter .',
              4: 'After directing The Rain People -LRB- 1969 -RRB- , he co-wrote the 1970 film Patton , earning the Academy Award for Best Original Screenplay along with co-writer Edmund H. North .',
              5: 'His directorial prominence was cemented with the release in 1972 of The Godfather , a film which revolutionized movie-making in the gangster genre , earning praise from both critics and the public before winning three Academy Awards -- including his second Oscar -LRB- Best Adapted Screenplay , with Mario Puzo -RRB- , Best Picture , and his first nomination for Best Director .',
              8: 'He followed with The Godfather Part II in 1974 , which became the first sequel to win the Academy Award for Best Picture .',
              9: 'Highly regarded by critics , it brought him three more Academy Awards : Best Adapted Screenplay , Best Director and Best Picture , and made him the second director , after Billy Wilder , to be honored three times for the same film .',
              10: "The Conversation , which he directed , produced and wrote , was released that same year , winning the Palme d'Or at the 1974 Cannes Film Festival .",
              12: "While notorious for its lengthy and strenuous production , the film was widely acclaimed for its vivid and stark depiction of the Vietnam War , winning the Palme d'Or at the 1979 Cannes Film Festival ."},
             'Andy_Roddick': {0: "Andrew Stephen `` Andy '' Roddick -LRB- born August 30 , 1982 -RRB- is an American former professional tennis player .",
              3: 'He became a Grand Slam singles champion , and world number one , when he won the title at the 2003 US Open , defeating Juan Carlos Ferrero in the final .',
              7: "Roddick was ranked in the top 10 for nine consecutive years between 2002 and 2010 , at year 's end , and won five Masters Series in that period .",
              8: 'He is married to Brooklyn Decker , a former Sports Illustrated swimwear model and actress .',
              11: 'On August 30 , 2012 , during the 2012 US Open and on his 30th birthday , Roddick announced that he would retire after the tournament .',
              12: 'Following a fourth-round defeat by Juan Martín del Potro , Roddick retired from the sport with the aim of focusing on his foundation , the Andy Roddick Foundation , in future years .'},

In [29]:
enriched_fever_index

defaultdict(list,
            {'Nikolaj_Coster-Waldau': [(0,
               'Nikolaj Coster-Waldau -LRB- -LSB- neɡ̊olaɪ̯ kʰʌsd̥ɐ ˈʋald̥ɑʊ̯ -RSB- ; born 27 July 1970 -RRB- is a Danish actor , producer and screenwriter .'),
              (2,
               "Coster-Waldau 's breakthrough performance in Denmark was his role in the film Nightwatch -LRB- 1994 -RRB- ."),
              (3,
               'Since then he has appeared in numerous films in his native Scandinavia and Europe in general , including Headhunters -LRB- 2011 -RRB- and A Thousand Times Good Night -LRB- 2013 -RRB- .'),
              (7,
               'He then played Detective John Amsterdam in the short-lived Fox television series New Amsterdam -LRB- 2008 -RRB- , as well as appearing as Frank Pike in the 2009 Fox television film Virtuality , originally intended as a pilot .'),
              (8,
               'He became widely known to a broad audience for his current role as Ser Jaime Lannister , in the HBO series Game of Thrones .')],
             'Fox_Broadcasting_Company': [(0,
               'The Fox Broadcasting Company -LRB- often shortened to Fox and stylized as FOX -RRB- is an American English language commercial broadcast television network that is owned by the Fox Entertainment Group subsidiary of 21st Century Fox .'),
              (1,
               'The network is headquartered at the 20th Century Fox studio lot on Pico Boulevard in the Century City section of Los Angeles , with additional major offices and production facilities at the Fox Television Center in nearby West Los Angeles and the Fox Broadcasting Center in the Yorkville neighborhood of Manhattan , New York City .'),
              (2,
               'It is the third largest major television network in the world based on total revenues , assets , and international coverage .')],
             'Roman_Atwood': [(0,
               'Roman Bernard Atwood -LRB- born May 28 , 1983 -RRB- is an American YouTube personality , comedian , vlogger and pranker .'),
              (1,
               'He is best known for his vlogs , where he posts updates about his life on a daily basis .')],
             'History_of_art': [(0,
               'The history of art is the history of any activity or product made by humans in a visual form for aesthetical or communicative purposes , expressing ideas , emotions or , in general , a worldview .'),
              (2,
               'The subsequent expansion of the list of principal arts in the 20th century reached to nine : architecture , dance , sculpture , music , painting , poetry -LRB- described broadly as a form of literature with aesthetic purpose or function , which also includes the distinct genres of theatre and narrative -RRB- , film , photography and graphic arts .')],
             'Adrienne_Bailon': [(0,
               'Adrienne Eliza Houghton -LRB- née Bailon ; born October 24 , 1983 -RRB- is an American singer-songwriter , recording artist , actress , dancer and television personality .'),
              (8,
               "Aside from her work in 3LW and The Cheetah Girls , Bailon went on to develop her own acting career with roles in The Cheetah Girls films , Coach Carter and the MTV film All You 've Got ."),
              (1,
               "Adrienne Bailon first became publicly known when she rose to fame as one of the founding members and singer of both 3LW -LRB- 1999 -- 2007 -RRB- and Disney 's The Cheetah Girls -LRB- 2003 -- 2008 -RRB- .")],
             'Homeland_-LRB-TV_series-RRB-': [(0,
               "Homeland is an American spy thriller television series developed by Howard Gordon and Alex Gansa based on the Israeli series Prisoners of War -LRB- Original title חטופים Hatufim , literally `` Abductees '' -RRB- , which was created by Gideon Raff ."),
              (3,
               'The series stars Claire Danes as Carrie Mathison , a Central Intelligence Agency officer with bipolar disorder , and Damian Lewis as Nicholas Brody , a U.S. Marine Corps Scout Sniper .')],
             'Prisoners_of_War_-LRB-TV_series-RRB-': [(0,
               "Prisoners of War -LRB- original title in -RRB- is an Israeli television drama series made by Keshet and originally aired on Israel 's Channel 2 from March to May 2010 .")],
             'Boston_Celtics': [(0,
               'The Boston Celtics -LRB- -LSB- ˈsɛltɪks -RSB- -RRB- are an American professional basketball team based in Boston , Massachusetts .'),
              (3,
               "The Celtics play their home games at the TD Garden , which they share with the National Hockey League -LRB- NHL -RRB- 's Boston Bruins .")],
             'The_Ten_Commandments_-LRB-1956_film-RRB-': [(0,
               'The Ten Commandments is a 1956 American biblical epic film produced , directed , and narrated by Cecil B. DeMille , shot in VistaVision -LRB- color by Technicolor -RRB- , and released by Paramount Pictures .')],
             'Tetris': [(0,
               'Tetris -LRB- , pronounced -LSB- ˈtɛtrʲɪs -RSB- -RRB- is a tile-matching puzzle video game , originally designed and programmed by Russian game designer Alexey Pajitnov .'),
              (18,
               'In January 2010 , it was announced that the Tetris franchise had sold more than 170 million copies , approximately 70 million physical copies and over 100 million copies for cell phones , making it the best selling paid-downloaded game of all time .')],
             'Cyndi_Lauper': [(0,
               "Cynthia Ann Stephanie `` Cyndi '' Lauper -LRB- born June 22 , 1953 -RRB- is an American singer , songwriter , actress and LGBTQ activist ."),
              (2,
               "Her debut solo album She 's So Unusual -LRB- 1983 -RRB- was the first debut female album to chart four top-five hits on the Billboard Hot 100 -- `` Girls Just Want to Have Fun '' , `` Time After Time '' , `` She Bop '' , and `` All Through the Night '' -- and earned Lauper the Best New Artist award at the 27th Grammy Awards in 1985 ."),
              (21,
               "Her debut album is included in Rolling Stone '' 's list of the 500 Greatest Albums of All Time , while Time After Time is included in Vh1 's list of the 100 Best Songs of the Past 25 years ."),
              (7,
               'Since 1989 , Lauper has released nine studio albums and participated in many other projects .'),
              (26,
               "Her charitable efforts were acknowledged in 2013 when the singer was invited as a special guest to attend US President Barack Obama 's second-term inaugural .")],
             'The_Hunger_Games_-LRB-film-RRB-': [(0,
               'The Hunger Games is a 2012 American dystopian science fiction adventure film directed by Gary Ross and based on the novel of the same name by Suzanne Collins .'),
              (1,
               'It is the first installment in The Hunger Games film series and was produced by Nina Jacobson and Jon Kilik , with a screenplay by Ross , Collins , and Billy Ray .'),
              (2,
               'The film stars Jennifer Lawrence , Josh Hutcherson , Liam Hemsworth , Woody Harrelson , Elizabeth Banks , Lenny Kravitz , Stanley Tucci , and Donald Sutherland .'),
              (3,
               "The story takes place in a dystopian post-apocalyptic future in the nation of Panem , where boys and girls between the ages of 12 and 18 must take part in the Hunger Games , a televised annual event in which the `` tributes '' are required to fight to the death until there is only one survivor ."),
              (4,
               "Katniss Everdeen -LRB- Lawrence -RRB- volunteers to take her younger sister 's place ."),
              (8,
               'Development of The Hunger Games began in March 2009 when Lions Gate Entertainment entered into a co-production agreement with Color Force , which had acquired the rights a few weeks earlier .'),
              (16,
               'The film was released on March 21 , 2012 , in some European countries and in the US on March 23 , 2012 , in both conventional theaters and digital IMAX theaters .'),
              (18,
               'When the film released , it set records for opening day -LRB- $ 67.3 million -RRB- and opening weekend for a non-sequel .'),
              (19,
               "At the time of its release , the film 's opening weekend gross -LRB- $ 152.5 million -RRB- was the third-largest of any movie in North America ."),
              (21,
               'The film was a massive box-office success by grossing over $ 694 million worldwide against its budget of $ 78 million , making it the third-highest-grossing film in the United States and ninth-highest-grossing worldwide of 2012 .'),
              (24,
               'A sequel , The Hunger Games : Catching Fire , was released on November 22 , 2013 , in the United States .'),
              (27,
               "The Hunger Games received positive reviews from critics , with praise for its themes and messages , as well as Jennifer Lawrence 's portrayal of Katniss , though there was criticism of the film 's use of shaky cam in the action sequences .")],
             'Ryan_Gosling': [(0,
               'Ryan Thomas Gosling -LRB- born November 12 , 1980 -RRB- is a Canadian actor and musician .'),
              (3,
               'His first starring film role was as a Jewish neo-Nazi in The Believer -LRB- 2001 -RRB- , and he went on to star in several independent films , including Murder by Numbers -LRB- 2002 -RRB- , The Slaughter Rule -LRB- 2002 -RRB- , and The United States of Leland -LRB- 2003 -RRB- .'),
              (6,
               'Gosling came to the attention of a wider audience in 2004 with a leading role in the commercially successful romantic drama The Notebook .'),
              (7,
               'His performance as a drug-addicted teacher in Half Nelson -LRB- 2006 -RRB- was nominated for an Academy Award and his performance as a socially inept loner in Lars and the Real Girl -LRB- 2007 -RRB- was nominated for a Golden Globe Award .'),
              (8,
               'After a three-year acting hiatus , Gosling starred in the marital drama Blue Valentine -LRB- 2010 -RRB- , earning him a second Golden Globe nomination .'),
              (9,
               'Gosling co-starred in three mainstream films in 2011the romantic comedy-drama Crazy , Stupid , Love , the political drama The Ides of March , and the action thriller Driveand received two more Golden Globe nominations .'),
              (12,
               'For the latter , he won a Golden Globe Award and received a second Oscar nomination .'),
              (17,
               'He is a supporter of PETA , Invisible Children and the Enough Project and has traveled to Chad , Uganda and eastern Congo to raise awareness about conflicts in the regions .')],
             'Chad': [(0,
               "Chad -LRB- -LSB- tʃæd -RSB- تشاد ; Tchad -LSB- tʃa -LRB- d -RRB- -RSB- -RRB- , officially the Republic of Chad -LRB- ; `` Republic of the Chad '' -RRB- , is a landlocked country in Central Africa .")],
             'Stranger_Things': [(0,
               'Stranger Things is an American science fiction-horror web television series created , written , directed and co-executive produced by the Duffer Brothers , as well as co-executive-produced by Shawn Levy and Dan Cohen .'),
              (1,
               'The first season stars Winona Ryder , David Harbour , Finn Wolfhard , Millie Bobby Brown , Gaten Matarazzo , Caleb McLaughlin , Natalia Dyer , Charlie Heaton , Cara Buono , and Matthew Modine , with Noah Schnapp and Joe Keery in recurring roles .'),
              (2,
               'The second season will see Schnapp and Keery promoted to series regulars , along with the addition of Sadie Sink and Dacre Montgomery .'),
              (5,
               "Set in the fictional town of Hawkins , Indiana in the 1980s , the first season focuses on the investigation into the disappearance of a young boy by his friends , older brother and traumatized mother and the local police chief , amid supernatural events occurring around the town including the appearance of a psychokinetic girl who helps the missing boy 's friends in their own search ."),
              (6,
               'The second season is set a year after the first , and deals with attempts of the characters to return to normal and consequences from that season .'),
              (9,
               'The Duffer Brothers developed the series as a mix of investigative drama alongside supernatural elements with childlike sensibilities , establishing its time frame in the 1980s and creating a homage #Noun to pop culture of that decade .'),
              (13, 'The series was released on Netflix on July 15 , 2016 .'),
              (14,
               'It received critical acclaim for its characterization , pacing , atmosphere , acting , soundtrack , directing , writing and homages to 1980s genre films .'),
              (16,
               'On August 31 , 2016 , Netflix renewed the series for a second season of nine episodes , which is set to be released on October 31 , 2017 .')],
             'Ryan_Seacrest': [(0,
               'Ryan John Seacrest -LRB- born December 24 , 1974 -RRB- is an American radio personality , television host and producer .')],
             'Puerto_Rico': [(0,
               "Puerto Rico -LRB- Spanish for `` Rich Port '' -RRB- , officially the Commonwealth of Puerto Rico -LRB- Estado Libre Asociado de Puerto Rico , `` Free Associated State of Puerto Rico '' -RRB- and briefly called Porto Rico , is an unincorporated territory of the United States located in the northeast Caribbean Sea ."),
              (3,
               'It is an archipelago that includes the main island of Puerto Rico and a number of smaller ones such as Mona , Culebra , and Vieques .'),
              (6, "The island 's population is approximately 3.4 million .")],
             'Michael_Giacchino': [(0,
               'Michael Giacchino -LRB- -LSB- dʒakˈkiːno -RSB- ; born October 10 , 1967 -RRB- is an American composer of music for films , television and video games .'),
              (1,
               "He composed the scores to the television series Lost , Alias and Fringe , the video ' game series Medal of Honor and Call of Duty and many films such as The Incredibles , Ratatouille , Up , Mission : Impossible - Ghost Protocol , Dawn of the Planet of the Apes , Jurassic World , Inside Out , Star Trek Beyond , Doctor Strange , Rogue One and Spider-Man : Homecoming .")],
             'Stranger_than_Fiction_-LRB-2006_film-RRB-': [(0,
               'Stranger than Fiction is a 2006 American fantasy comedy-drama film directed by Marc Forster , produced by Lindsay Doran , and written by Zach Helm .')],
             'Chris_Hemsworth': [(0,
               'Chris Hemsworth -LRB- born 11 August 1983 -RRB- is an Australian actor .'),
              (1,
               'He is known for playing Kim Hyde in the Australian TV series Home and Away -LRB- 2004-07 -RRB- and Thor in the Marvel Cinematic Universe since 2011 .'),
              (2,
               'Hemsworth has also appeared in the science fiction action film Star Trek -LRB- 2009 -RRB- , the thriller adventure A Perfect Getaway -LRB- 2009 -RRB- , the horror comedy The Cabin in the Woods -LRB- 2012 -RRB- , the dark-fantasy action film Snow White and the Huntsman -LRB- 2012 -RRB- , the war film Red Dawn -LRB- 2012 -RRB- , and the biographical sports drama film Rush -LRB- 2013 -RRB- .'),
              (7,
               'Hemsworth will reprise his role as George Kirk in the upcoming Star Trek sequel .')],
             'Selena': [(0,
               'Selena Quintanilla-Pérez -LRB- -LSB- seˈlena kintaˈniʝa ˈpeɾes -RSB- or -LSB- seˈlena kintaˈniʎa ˈpeɾeθ -RSB- April 16 , 1971 -- March 31 , 1995 -RRB- was an American singer , songwriter , spokesperson , model , actress , and fashion designer .'),
              (33,
               'In 1997 , Warner Bros. released Selena , a film about her life and career , which starred Jennifer Lopez as Selena and Lupe Ontiveros as Saldívar .'),
              (8, 'Selena began recording professionally in 1982 .'),
              (28,
               'On March 31 , 1995 , Selena was shot dead by Yolanda Saldívar , her friend and former employee of her Selena Etc. boutiques .'),
              (15,
               "The album 's commercial success led music critics to call the album the `` breakthrough '' recording of her musical career .")],
             "Robert_J._O'Neill_-LRB-U.S._Navy_SEAL-RRB-": [(0,
               "Robert J. `` Rob '' O'Neill -LRB- born April 10 , 1976 -RRB- is a former United States Navy sailor ."),
              (1,
               "A former U.S. Navy SEAL and special warfare operator , O'Neill is best known for claiming to have fired the head shots that killed Osama bin Laden during the raid on his Abbottabad compound on May 1 , 2011 .")],
             'The_Silence_of_the_Lambs_-LRB-film-RRB-': [(0,
               'The Silence of the Lambs is a 1991 American horror-thriller film directed by Jonathan Demme and starring Jodie Foster , Anthony Hopkins , and Scott Glenn .'),
              (1,
               'Adapted by Ted Tally from the 1988 novel of the same name by Thomas Harris , his second to feature the character of Dr. Hannibal Lecter ; a brilliant psychiatrist and cannibalistic serial killer , the film was the second adaptation of a Harris novel featuring Lecter , preceded by the Michael Mann-directed Manhunter in 1986 .'),
              (2,
               "In the film , Clarice Starling , a young U.S. FBI trainee , seeks the advice of the imprisoned Dr. Lecter to apprehend another serial killer , known only as `` Buffalo Bill '' ."),
              (5,
               'The Silence of the Lambs was released on February 14 , 1991 , and grossed $ 272.7 million worldwide against its $ 19 million budget .'),
              (6,
               "It was only the third film , the other two being It Happened One Night and One Flew Over the Cuckoo 's Nest , to win Academy Awards in all the top five categories : Best Picture , Best Actor , Best Actress , Best Director , and Adapted Screenplay .")],
             'Peggy_Sue_Got_Married': [(0,
               'Peggy Sue Got Married is a 1986 American comedy-drama film directed by Francis Ford Coppola starring Kathleen Turner as a woman on the verge of a divorce , who finds herself transported back to the days of her senior year in high school in 1960 .')],
             'Francis_Ford_Coppola': [(0,
               'Francis Ford Coppola -LRB- -LSB- pronˈkoʊpələ -RSB- born April 7 , 1939 -RRB- , also credited as Francis Coppola , is a semi-retired American film director , producer , and screenwriter .'),
              (4,
               'After directing The Rain People -LRB- 1969 -RRB- , he co-wrote the 1970 film Patton , earning the Academy Award for Best Original Screenplay along with co-writer Edmund H. North .'),
              (5,
               'His directorial prominence was cemented with the release in 1972 of The Godfather , a film which revolutionized movie-making in the gangster genre , earning praise from both critics and the public before winning three Academy Awards -- including his second Oscar -LRB- Best Adapted Screenplay , with Mario Puzo -RRB- , Best Picture , and his first nomination for Best Director .'),
              (8,
               'He followed with The Godfather Part II in 1974 , which became the first sequel to win the Academy Award for Best Picture .'),
              (9,
               'Highly regarded by critics , it brought him three more Academy Awards : Best Adapted Screenplay , Best Director and Best Picture , and made him the second director , after Billy Wilder , to be honored three times for the same film .'),
              (10,

In [30]:
# Check if the page exists in FEVER_df without normalization
page_to_check = "José_María_Chacón"
any(page_to_check in str(group) for group in FEVER_df['golden_evidence_group'])

False

In [ ]:
# Checking for the same page name but this after normalization in FEVER_df
page_to_check = "José_María_Chacón"
exists = norm_page_exists_in_df(FEVER_df, page_to_check)
print(exists)

True

The above code returns true means the page is there but we are not able to find it because of the unicode mis-match. Therefore, page name in FEVER_df['golden_evidence_group'] also needs to be normalized.

## 4.8 Normalize FEVER_df

In [31]:
# Normalize page names inside golden_evidence_group
for row in FEVER_df.itertuples(index=False):
    group = row.golden_evidence_group
    if not group:
        continue
    for item in group:
        item[2] = normalize(item[2])

In [32]:
# Check if the page exists in FEVER_df
page_to_check = "José_María_Chacón"
any(page_to_check in str(group) for group in FEVER_df['golden_evidence_group'])

True

This indicates that normalization done successfully

## 4.9 Adding sentence text to 'FEVER_df'

In [77]:
FEVER_df.head()

,id,label,claim,evidence,golden_evidence_group,golden_evidence_text
0,75397,SUPPORTS,Nikolaj Coster-Waldau worked with the Fox Broa...,"[[[92206, 104971, Nikolaj_Coster-Waldau, 7], [...","[[92206, 104971, Nikolaj_Coster-Waldau, 7], [9...",
1,150448,SUPPORTS,Roman Atwood is a content creator.,"[[[174271, 187498, Roman_Atwood, 1]], [[174271...","[[174271, 187498, Roman_Atwood, 1]]",
2,214861,SUPPORTS,"History of art includes architecture, dance, s...","[[[255136, 254645, History_of_art, 2]]]","[[255136, 254645, History_of_art, 2]]",
3,156709,REFUTES,Adrienne Bailon is an accountant.,"[[[180804, 193183, Adrienne_Bailon, 0]]]","[[180804, 193183, Adrienne_Bailon, 0]]",
4,83235,NOT ENOUGH INFO,System of a Down briefly disbanded in limbo.,"[[[100277, None, None, None]]]","[[100277, None, None, None]]",EMPTY

In [ ]:
# Adding sentence text to the DataFrame

# To see the progress
tqdm.pandas()

# Apply to all rows
FEVER_df["golden_evidence_text"] = FEVER_df["golden_evidence_group"].progress_apply(
    lambda group: extract_evidence_text(group, enriched_fever_index)
)

FEVER_df.head()

100%|██████████| 165447/165447 [00:00<00:00, 745260.35it/s]

,id,label,claim,evidence,golden_evidence_group,golden_evidence_text
0,75397,SUPPORTS,Nikolaj Coster-Waldau worked with the Fox Broa...,"[[[92206, 104971, Nikolaj_Coster-Waldau, 7], [...","[[92206, 104971, Nikolaj_Coster-Waldau, 7], [9...",He then played Detective John Amsterdam in the...
1,150448,SUPPORTS,Roman Atwood is a content creator.,"[[[174271, 187498, Roman_Atwood, 1]], [[174271...","[[174271, 187498, Roman_Atwood, 1]]","He is best known for his vlogs , where he post..."
2,214861,SUPPORTS,"History of art includes architecture, dance, s...","[[[255136, 254645, History_of_art, 2]]]","[[255136, 254645, History_of_art, 2]]",The subsequent expansion of the list of princi...
3,156709,REFUTES,Adrienne Bailon is an accountant.,"[[[180804, 193183, Adrienne_Bailon, 0]]]","[[180804, 193183, Adrienne_Bailon, 0]]",Adrienne Eliza Houghton -LRB- née Bailon ; bor...
4,83235,NOT ENOUGH INFO,System of a Down briefly disbanded in limbo.,"[[[100277, None, None, None]]]","[[100277, None, None, None]]",

### 4.9.1 Verifying Created Dataframe

In this, we 'll check whether the sentence text has been added succesfully or not. For this, we visualize & analyse the data in 3 different parts as per the labels - 'SUPPORTS', 'REFUTES' & 'NOT ENOUGH INFO'

For each type of data, we do the following steps
1. Filter the data with the label type and use 'head()' to visualize first few entires.
2. We 'll count the no. of entries using the 'shape' on this filtered data
3. We 'll count no. of empty strings in the 'golden_evidence_text'.

#### 4.9.1.1 Verifying where label = 'NOT ENOUGH INFO'

In [81]:
FEVER_df[FEVER_df['label'] == 'NOT ENOUGH INFO'].head()

,id,label,claim,evidence,golden_evidence_group,golden_evidence_text
4,83235,NOT ENOUGH INFO,System of a Down briefly disbanded in limbo.,"[[[100277, None, None, None]]]","[[100277, None, None, None]]",
6,149579,NOT ENOUGH INFO,Beautiful reached number two on the Billboard ...,"[[[173384, None, None, None]]]","[[173384, None, None, None]]",
7,229289,NOT ENOUGH INFO,Neal Schon was named in 1954.,"[[[273626, None, None, None]]]","[[273626, None, None, None]]",
21,138117,NOT ENOUGH INFO,John Wick: Chapter 2 was theatrically released...,"[[[160895, None, None, None]]]","[[160895, None, None, None]]",
23,210010,NOT ENOUGH INFO,Afghanistan is the source of the Kushan dynasty.,"[[[248748, None, None, None]]]","[[248748, None, None, None]]",

In [90]:
FEVER_df[FEVER_df['label'] == 'NOT ENOUGH INFO'].shape

(42305, 6)

In [96]:
# Counting the no. of entries with empty 'golden_evidence_text'
print((FEVER_df[FEVER_df['label'] == 'NOT ENOUGH INFO']['golden_evidence_text']=='').sum())

42305

This is as expetced. As for such entries, we are entring empty string.

#### 4.9.1.2 Verifying where label = 'SUPPORTS'

In [82]:
FEVER_df[FEVER_df['label'] == 'SUPPORTS'].head()

,id,label,claim,evidence,golden_evidence_group,golden_evidence_text
0,75397,SUPPORTS,Nikolaj Coster-Waldau worked with the Fox Broa...,"[[[92206, 104971, Nikolaj_Coster-Waldau, 7], [...","[[92206, 104971, Nikolaj_Coster-Waldau, 7], [9...",He then played Detective John Amsterdam in the...
1,150448,SUPPORTS,Roman Atwood is a content creator.,"[[[174271, 187498, Roman_Atwood, 1]], [[174271...","[[174271, 187498, Roman_Atwood, 1]]","He is best known for his vlogs , where he post..."
2,214861,SUPPORTS,"History of art includes architecture, dance, s...","[[[255136, 254645, History_of_art, 2]]]","[[255136, 254645, History_of_art, 2]]",The subsequent expansion of the list of princi...
5,129629,SUPPORTS,Homeland is an American television spy thrille...,"[[[151831, 166598, Homeland_-LRB-TV_series-RRB...","[[151831, 166598, Homeland_-LRB-TV_series-RRB-...",Homeland is an American spy thriller televisio...
8,33078,SUPPORTS,The Boston Celtics play their home games at TD...,"[[[49158, 58489, Boston_Celtics, 3]], [[49159,...","[[49158, 58489, Boston_Celtics, 3]]",The Celtics play their home games at the TD Ga...

In [93]:
FEVER_df[FEVER_df['label'] == 'SUPPORTS'].shape

(86701, 6)

In [97]:
# Counting the no. of entries with empty 'golden_evidence_text'
print((FEVER_df[FEVER_df['label'] == 'SUPPORTS']['golden_evidence_text']=='').sum())

0

This is as exptected

#### 4.9.1.1 Verifying where label = 'REFUTES'

In [83]:
FEVER_df[FEVER_df['label'] == 'REFUTES'].head()

,id,label,claim,evidence,golden_evidence_group,golden_evidence_text
3,156709,REFUTES,Adrienne Bailon is an accountant.,"[[[180804, 193183, Adrienne_Bailon, 0]]]","[[180804, 193183, Adrienne_Bailon, 0]]",Adrienne Eliza Houghton -LRB- née Bailon ; bor...
14,138503,REFUTES,"Stranger Things is set in Bloomington, Indiana.","[[[161295, 175782, Stranger_Things, 5]]]","[[161295, 175782, Stranger_Things, 5]]","Set in the fictional town of Hawkins , Indiana..."
16,73170,REFUTES,Puerto Rico is not an unincorporated territory...,"[[[89957, 102650, Puerto_Rico, 0]]]","[[89957, 102650, Puerto_Rico, 0]]",Puerto Rico -LRB- Spanish for `` Rich Port '' ...
26,15812,REFUTES,Peggy Sue Got Married is a Egyptian film relea...,"[[[31205, 37902, Peggy_Sue_Got_Married, 0], [3...","[[31205, 37902, Peggy_Sue_Got_Married, 0], [31...",Peggy Sue Got Married is a 1986 American comed...
27,57330,REFUTES,Andy Roddick lost 5 Master Series between 2002...,"[[[73660, 84912, Andy_Roddick, 7]]]","[[73660, 84912, Andy_Roddick, 7]]",Roddick was ranked in the top 10 for nine cons...

In [99]:
FEVER_df[FEVER_df['label'] == 'REFUTES'].shape

(36441, 6)

In [98]:
# Counting the no. of entries with empty 'golden_evidence_text'
print((FEVER_df[FEVER_df['label'] == 'REFUTES']['golden_evidence_text']=='').sum())

0

This is as expected

## 4.10 Filtering the required data

Since, we only need 'label', 'claim' & 'golden_evidence_text' for our experiment, we can drop rest of the columns.

In [104]:
FEVER_df = FEVER_df[["label", "claim", "golden_evidence_text"]]
FEVER_df

,label,claim,golden_evidence_text
0,SUPPORTS,Nikolaj Coster-Waldau worked with the Fox Broa...,He then played Detective John Amsterdam in the...
1,SUPPORTS,Roman Atwood is a content creator.,"He is best known for his vlogs , where he post..."
2,SUPPORTS,"History of art includes architecture, dance, s...",The subsequent expansion of the list of princi...
3,REFUTES,Adrienne Bailon is an accountant.,Adrienne Eliza Houghton -LRB- née Bailon ; bor...
4,NOT ENOUGH INFO,System of a Down briefly disbanded in limbo.,
...,...,...,...
165442,NOT ENOUGH INFO,Heavy Metal music was first developed in the U...,
165443,NOT ENOUGH INFO,Bethany Hamilton was a philosopher.,
165444,NOT ENOUGH INFO,Mike Huckabee hosts Oprah.,
165445,NOT ENOUGH INFO,Excuse My French is a studio EP.,
165446,NOT ENOUGH INFO,Shinji Mikami reviewed Resident Evil.,

## 4.11 Saving the final Dataframe

In [105]:
# Saving the final DataFrame to a JSONL file
'''
'force_ascii=False' 'll help us to keep the diacritics in the text as it is, without
 converting them to escape sequences i.e.

 If not 'False', then, names like this in our dataset 'll be converted to

 "José" → "Jos\u00e9"
"Mārīa" → "M\u0101r\u012ba"

Where as if it is 'False', then, names like this in our dataset 'll be kept as it is
"Mārīa" → "Mārīa"
"José" → "José"
'''
output_path = os.path.join("..", "datasets", "FEVER", "pre-processed", "Final_FEVER_Dataset_Eng.jsonl")
FEVER_df.to_json(output_path, orient="records", lines=True, force_ascii=False)

## 4.12 Verifying the saved data

In [108]:
Final_FEVER_df = get_dataset_dataframe("FEVER", "pre-processed", "Final_FEVER_Dataset_Eng.jsonl")
Final_FEVER_df.head()

,label,claim,golden_evidence_text
0,SUPPORTS,Nikolaj Coster-Waldau worked with the Fox Broa...,He then played Detective John Amsterdam in the...
1,SUPPORTS,Roman Atwood is a content creator.,"He is best known for his vlogs , where he post..."
2,SUPPORTS,"History of art includes architecture, dance, s...",The subsequent expansion of the list of princi...
3,REFUTES,Adrienne Bailon is an accountant.,Adrienne Eliza Houghton -LRB- née Bailon ; bor...
4,NOT ENOUGH INFO,System of a Down briefly disbanded in limbo.,

# IMPORTANT NOTE - Need to do this later

Need to check for duplicates in the data. The below code I have tried in the previous notebook.

In [111]:
# Check for duplicate claims in FEVER_df
duplicate_claims = Final_FEVER_df[Final_FEVER_df.duplicated(keep=False)]
print(f"Number of duplicate claims: {duplicate_claims.shape[0]}")
duplicate_claims

Number of duplicate claims: 13468

,label,claim,golden_evidence_text
2,SUPPORTS,"History of art includes architecture, dance, s...",The subsequent expansion of the list of princi...
7,NOT ENOUGH INFO,Neal Schon was named in 1954.,
18,SUPPORTS,Stranger than Fiction is a film.,Stranger than Fiction is a 2006 American fanta...
24,NOT ENOUGH INFO,Marilyn Monroe worked with Warner Brothers.,
31,SUPPORTS,The Jim Henson Company produced The Muppet Mov...,"The company has also produced many films , inc..."
...,...,...,...
165313,SUPPORTS,Lockhead Martin F-35 Lightning II was an expen...,The program is the most expensive military wea...
165360,NOT ENOUGH INFO,Polynesian languages includes several languages.,
165377,NOT ENOUGH INFO,Noel Fisher starred in Game of Thrones.,
165382,NOT ENOUGH INFO,Edmund H. North won an Emmy Award.,
165407,SUPPORTS,Nicholas Brody is a character on Homeland.,"Nicholas `` Nick '' Brody , played by actor Da..."

# END